<?php

namespace Database\Seeders;

use App\Models\Job;
use Illuminate\Database\Seeder;

class JobSeeder extends Seeder
{
    public function run(): void
    {
        $jobs = [
            [
                'title' => 'Senior PR Manager',
                'slug' => 'senior-pr-manager',
                'department' => 'Public Relations',
                'location' => 'Noida, India',
                'job_type' => 'full-time',
                'experience' => '6-8 years',
                'salary_range' => '₹15-22 LPA',
                'status' => 'active',
                'description' => 'Lead the overall PR strategy for enterprise clients. Develop and execute comprehensive communications plans that drive brand visibility and reputation management.',
                'responsibilities' => 'Develop PR strategies aligned with business objectives. Manage media relationships and press coverage. Lead crisis communications planning. Oversee PR campaigns from concept to execution. Mentor junior team members.',
                'requirements' => '6-8 years of experience in PR/Communications. Proven track record of managing enterprise accounts. Strong media network and relationships. Excellent written and verbal communication skills. MBA or relevant postgraduate degree preferred.',
            ],
            [
                'title' => 'PR Executive',
                'slug' => 'pr-executive',
                'department' => 'Public Relations',
                'location' => 'Mumbai, India',
                'job_type' => 'full-time',
                'experience' => '2-4 years',
                'salary_range' => '₹5-8 LPA',
                'status' => 'active',
                'description' => 'Support the PR team in executing communications campaigns and maintaining client relationships.',
                'responsibilities' => 'Assist in drafting press releases and media materials. Monitor media coverage and generate reports. Coordinate with media houses for coverage. Support event coordination. Maintain media lists and databases.',
                'requirements' => '2-4 years of PR experience. Excellent writing skills. Strong attention to detail. Ability to work under deadlines. Mass Communication/Journalism degree preferred.',
            ],
            [
                'title' => 'Media Relations Specialist',
                'slug' => 'media-relations-specialist',
                'department' => 'Media',
                'location' => 'Delhi NCR',
                'job_type' => 'full-time',
                'experience' => '3-5 years',
                'salary_range' => '₹8-12 LPA',
                'status' => 'active',
                'description' => 'Build and maintain strong relationships with media contacts to secure optimal coverage for clients.',
                'responsibilities' => 'Cultivate relationships with journalists and editors. Pitch stories to media outlets. Organize press conferences and media briefings. Track and analyze media coverage. Develop media kits and press materials.',
                'requirements' => '3-5 years in media relations. Extensive media network in India. Excellent pitching and negotiation skills. Strong analytical abilities. Journalism/Communications background.',
            ],
            [
                'title' => 'Content Writer',
                'slug' => 'content-writer',
                'department' => 'Content',
                'location' => 'Noida, India',
                'job_type' => 'full-time',
                'experience' => '2-3 years',
                'salary_range' => '₹4-6 LPA',
                'status' => 'active',
                'description' => 'Create compelling content for various platforms including websites, blogs, social media, and marketing materials.',
                'responsibilities' => 'Write engaging content for digital platforms. Create thought leadership articles. Develop social media content calendars. Edit and proofread content. Collaborate with design team.',
                'requirements' => '2-3 years of content writing experience. Exceptional writing and editing skills. Understanding of SEO best practices. Portfolio of published work. English/Humanities degree preferred.',
            ],
            [
                'title' => 'Senior Content Strategist',
                'slug' => 'senior-content-strategist',
                'department' => 'Content',
                'location' => 'Bangalore, India',
                'job_type' => 'full-time',
                'experience' => '5-7 years',
                'salary_range' => '₹12-18 LPA',
                'status' => 'active',
                'description' => 'Develop comprehensive content strategies that align with brand objectives and drive audience engagement.',
                'responsibilities' => 'Create content strategy roadmaps. Define content governance frameworks. Analyze content performance metrics. Lead content ideation sessions. Collaborate with cross-functional teams.',
                'requirements' => '5-7 years in content strategy. Proven experience in B2B content. Data-driven approach to content. Strong project management skills. Journalism/Marketing degree.',
            ],
            [
                'title' => 'Digital Marketing Manager',
                'slug' => 'digital-marketing-manager',
                'department' => 'Marketing',
                'location' => 'Noida, India',
                'job_type' => 'full-time',
                'experience' => '4-6 years',
                'salary_range' => '₹10-16 LPA',
                'status' => 'active',
                'description' => 'Plan and execute digital marketing campaigns to drive brand awareness and lead generation.',
                'responsibilities' => 'Manage digital advertising campaigns. Optimize SEO/SEM strategies. Analyze campaign performance metrics. Manage social media advertising budgets. Coordinate with creative team.',
                'requirements' => '4-6 years in digital marketing. Google Ads and Analytics certified. Experience with marketing automation. Strong analytical skills. MBA in Marketing preferred.',
            ],
            [
                'title' => 'Social Media Executive',
                'slug' => 'social-media-executive',
                'department' => 'Social Media',
                'location' => 'Mumbai, India',
                'job_type' => 'full-time',
                'experience' => '1-3 years',
                'salary_range' => '₹3-5 LPA',
                'status' => 'active',
                'description' => 'Manage social media presence and create engaging content across various platforms.',
                'responsibilities' => 'Create and schedule social media posts. Monitor social media channels. Respond to comments and messages. Track social media metrics. Stay updated on social media trends.',
                'requirements' => '1-3 years social media experience. Knowledge of all major platforms. Excellent writing skills. Creative mindset. Journalism/Marketing degree.',
            ],
            [
                'title' => 'Brand Communications Lead',
                'slug' => 'brand-communications-lead',
                'department' => 'Brand',
                'location' => 'Noida, India',
                'job_type' => 'full-time',
                'experience' => '7-10 years',
                'salary_range' => '₹20-30 LPA',
                'status' => 'active',
                'description' => 'Lead brand communications initiatives and ensure consistent brand voice across all channels.',
                'responsibilities' => 'Define brand communication strategy. Ensure brand consistency. Lead brand campaigns. Manage brand guidelines. Oversee brand positioning.',
                'requirements' => '7-10 years in brand management. Experience with global brands. Strong strategic thinking. Excellent leadership skills. MBA in Brand/Marketing required.',
            ],
            [
                'title' => 'Client Servicing Manager',
                'slug' => 'client-servicing-manager',
                'department' => 'Client Services',
                'location' => 'Delhi NCR',
                'job_type' => 'full-time',
                'experience' => '4-6 years',
                'salary_range' => '₹10-14 LPA',
                'status' => 'active',
                'description' => 'Manage client relationships and ensure delivery of PR services exceed expectations.',
                'responsibilities' => 'Act as primary client contact. Manage client expectations. Coordinate internal teams. Handle escalations professionally. Drive client satisfaction.',
                'requirements' => '4-6 years in client servicing. Excellent relationship management. Strong presentation skills. PR/Marketing background. MBA preferred.',
            ],
            [
                'title' => 'Graphic Designer',
                'slug' => 'graphic-designer',
                'department' => 'Design',
                'location' => 'Noida, India',
                'job_type' => 'full-time',
                'experience' => '2-4 years',
                'salary_range' => '₹4-7 LPA',
                'status' => 'active',
                'description' => 'Create visually appealing designs for marketing materials, social media, and client presentations.',
                'responsibilities' => 'Design social media graphics. Create presentation decks. Design marketing collateral. Collaborate with content team. Maintain brand consistency.',
                'requirements' => '2-4 years graphic design experience. Proficiency in Adobe Creative Suite. Portfolio required. Understanding of design principles. Visual Communications degree preferred.',
            ],
            [
                'title' => 'Video Editor',
                'slug' => 'video-editor',
                'department' => 'Media',
                'location' => 'Noida, India',
                'job_type' => 'full-time',
                'experience' => '2-5 years',
                'salary_range' => '₹5-9 LPA',
                'status' => 'active',
                'description' => 'Edit video content for social media, websites, and promotional materials.',
                'responsibilities' => 'Edit video content. Add effects and transitions. Create short-form videos. Manage video libraries. Work with creative team.',
                'requirements' => '2-5 years video editing experience. Proficiency in Premiere Pro. Understanding of social formats. Creative eye for details. Portfolio required.',
            ],
            [
                'title' => 'PR Intern',
                'slug' => 'pr-intern',
                'department' => 'Public Relations',
                'location' => 'Noida, India',
                'job_type' => 'internship',
                'experience' => 'Fresher',
                'salary_range' => '₹10,000-15,000/month',
                'status' => 'active',
                'description' => 'Gain hands-on experience in PR while supporting the team with various tasks.',
                'responsibilities' => 'Research media contacts. Assist in press release writing. Monitor media coverage. Coordinate meeting logistics. Support event preparation.',
                'requirements' => 'Currently pursuing/completed degree. Strong writing skills. Eager to learn. Good communication skills. Journalism/Mass Comm students preferred.',
            ],
            [
                'title' => 'Copywriter',
                'slug' => 'copywriter',
                'department' => 'Content',
                'location' => 'Mumbai, India',
                'job_type' => 'full-time',
                'experience' => '2-4 years',
                'salary_range' => '₹5-8 LPA',
                'status' => 'active',
                'description' => 'Write persuasive copy for advertising campaigns, websites, and marketing materials.',
                'responsibilities' => 'Write advertising copy. Create tagline concepts. Develop brand voice guidelines. Write for digital platforms. Collaborate with creative team.',
                'requirements' => '2-4 years copywriting experience. Strong portfolio of ad copy. Creative thinking. Understanding of marketing. English/Journalism degree.',
            ],
            [
                'title' => 'Media Analyst',
                'slug' => 'media-analyst',
                'department' => 'Analytics',
                'location' => 'Noida, India',
                'job_type' => 'full-time',
                'experience' => '2-3 years',
                'salary_range' => '₹5-7 LPA',
                'status' => 'active',
                'description' => 'Analyze media coverage and provide insights to improve PR strategies.',
                'responsibilities' => 'Track media coverage. Generate analytics reports. Provide media insights. Monitor competitor coverage. Use media monitoring tools.',
                'requirements' => '2-3 years in media analysis. Proficiency in analytics tools. Strong Excel skills. Attention to detail. Statistics/Marketing degree.',
            ],
            [
                'title' => 'Account Director',
                'slug' => 'account-director',
                'department' => 'Client Services',
                'location' => 'Delhi NCR',
                'job_type' => 'full-time',
                'experience' => '10-15 years',
                'salary_range' => '₹30-45 LPA',
                'status' => 'active',
                'description' => 'Lead strategic client relationships and drive business growth for major accounts.',
                'responsibilities' => 'Manage senior client relationships. Lead strategic planning. Drive revenue growth. Mentor team members. Handle high-level negotiations.',
                'requirements' => '10-15 years in PR/Communications. Experience with Fortune 500 clients. Strong business acumen. Executive presence. MBA from top institute preferred.',
            ],
            [
                'title' => 'SEO Specialist',
                'slug' => 'seo-specialist',
                'department' => 'Digital',
                'location' => 'Noida, India',
                'job_type' => 'full-time',
                'experience' => '2-4 years',
                'salary_range' => '₹4-7 LPA',
                'status' => 'active',
                'description' => 'Optimize client websites and content for search engines to improve organic visibility.',
                'responsibilities' => 'Conduct SEO audits. Optimize on-page content. Build backlinks. Track keyword rankings. Report SEO performance.',
                'requirements' => '2-4 years SEO experience. Knowledge of Google algorithms. Experience with SEO tools. Strong analytical skills. Digital Marketing degree preferred.',
            ],
            [
                'title' => 'Events Manager',
                'slug' => 'events-manager',
                'department' => 'Events',
                'location' => 'Noida, India',
                'job_type' => 'full-time',
                'experience' => '4-6 years',
                'salary_range' => '₹8-12 LPA',
                'status' => 'active',
                'description' => 'Plan and execute corporate events, product launches, and press conferences.',
                'responsibilities' => 'Plan event logistics. Coordinate with vendors. Manage event budgets. Oversee event execution. Post-event analysis.',
                'requirements' => '4-6 years event management experience. Strong organizational skills. Vendor management experience. Budget handling. Hospitality/Management degree.',
            ],
            [
                'title' => 'Communications Consultant',
                'slug' => 'communications-consultant',
                'department' => 'Consulting',
                'location' => 'Remote',
                'job_type' => 'contract',
                'experience' => '5-8 years',
                'salary_range' => '₹15-25 LPA',
                'status' => 'active',
                'description' => 'Provide expert communications counsel to enterprise clients on strategic initiatives.',
                'responsibilities' => 'Advise on communication strategy. Conduct communication audits. Train spokespersons. Develop crisis protocols. Review communication materials.',
                'requirements' => '5-8 years consulting experience. Strong analytical skills. Excellent presentation. PR agency background. MBA preferred.',
            ],
            [
                'title' => 'Press Release Writer',
                'slug' => 'press-release-writer',
                'department' => 'Content',
                'location' => 'Work from Home',
                'job_type' => 'part-time',
                'experience' => '1-3 years',
                'salary_range' => '₹3-5 LPA',
                'status' => 'active',
                'description' => 'Write compelling press releases for various industries and announcements.',
                'responsibilities' => 'Write newsworthy press releases. Follow AP style guidelines. Meet quick turnaround times. Work with client teams. Edit based on feedback.',
                'requirements' => '1-3 years PR writing experience. Strong AP style knowledge. Fast writer. Attention to detail. Journalism degree preferred.',
            ],
            [
                'title' => 'Crisis Communications Expert',
                'slug' => 'crisis-communications-expert',
                'department' => 'Public Relations',
                'location' => 'Delhi NCR',
                'job_type' => 'full-time',
                'experience' => '8-12 years',
                'salary_range' => '₹25-40 LPA',
                'status' => 'active',
                'description' => 'Guide clients through reputational crises with strategic communications response.',
                'responsibilities' => 'Develop crisis response plans. Manage crisis situations. Train spokespersons. Coordinate with legal teams. Monitor crisis developments.',
                'requirements' => '8-12 years crisis experience. Experience in corporate crises. Calm under pressure. Strong media contacts. Communications/PR degree.',
            ],
            [
                'title' => 'Thought Leadership Consultant',
                'slug' => 'thought-leadership-consultant',
                'department' => 'Consulting',
                'location' => 'Noida, India',
                'job_type' => 'contract',
                'experience' => '6-10 years',
                'salary_range' => '₹20-35 LPA',
                'status' => 'active',
                'description' => 'Help executives build their personal brand and establish thought leadership in their industries.',
                'responsibilities' => 'Develop thought leadership strategies. Ghostwrite executive content. Create speaking opportunities. Build personal brand presence. Measure thought leadership impact.',
                'requirements' => '6-10 years in communications. Experience with C-suite clients. Exceptional writing skills. Understanding of LinkedIn. Business/Media degree.',
            ],
            [
                'title' => 'Community Manager',
                'slug' => 'community-manager',
                'department' => 'Social Media',
                'location' => 'Bangalore, India',
                'job_type' => 'full-time',
                'experience' => '2-4 years',
                'salary_range' => '₹5-8 LPA',
                'status' => 'active',
                'description' => 'Build and engage online communities around brands on social media platforms.',
                'responsibilities' => 'Manage brand communities. Moderate community discussions. Respond to queries. Identify brand advocates. Track engagement metrics.',
                'requirements' => '2-4 years community management. Excellent communication skills. Social media expertise. Customer service background. Marketing degree preferred.',
            ],
            [
                'title' => 'Research Analyst',
                'slug' => 'research-analyst',
                'department' => 'Analytics',
                'location' => 'Noida, India',
                'job_type' => 'full-time',
                'experience' => '1-2 years',
                'salary_range' => '₹3-5 LPA',
                'status' => 'active',
                'description' => 'Conduct research to support PR strategies and media campaigns.',
                'responsibilities' => 'Research industry trends. Analyze media landscape. Prepare briefing documents. Support strategy development. Track competitor activities.',
                'requirements' => '1-2 years research experience. Strong analytical skills. Proficiency in MS Office. Research methodology knowledge. Any graduate degree.',
            ],
            [
                'title' => 'CXO Ghostwriter',
                'slug' => 'cxo-ghostwriter',
                'department' => 'Content',
                'location' => 'Remote',
                'job_type' => 'contract',
                'experience' => '5-10 years',
                'salary_range' => '₹18-30 LPA',
                'status' => 'active',
                'description' => 'Write articles, speeches, and opinion pieces for C-suite executives and founders.',
                'responsibilities' => 'Ghostwrite executive articles. Develop speech content. Create LinkedIn posts. Maintain executive voice. Conduct interview research.',
                'requirements' => '5-10 years writing experience. Portfolio of executive content. Ability to match executive voice. Fast turnaround capability. Journalism/Literature degree.',
            ],
            [
                'title' => 'Photography Intern',
                'slug' => 'photography-intern',
                'department' => 'Media',
                'location' => 'Noida, India',
                'job_type' => 'internship',
                'experience' => 'Fresher',
                'salary_range' => '₹8,000-12,000/month',
                'status' => 'active',
                'description' => 'Assist with photography for events, corporate shoots, and social media content.',
                'responsibilities' => 'Assist in photo shoots. Edit photos for web. Organize photo library. Support event coverage. Maintain photography gear.',
                'requirements' => 'Knowledge of DSLR photography. Basic photo editing skills. Eager to learn. Own camera preferred. Photography/Design background.',
            ],
        ];

        foreach ($jobs as $job) {
            $existing = Job::where('slug', $job['slug'])->first();
            if (! $existing) {
                Job::create($job);
                echo 'Created: '.$job['title']."\n";
            } else {
                echo 'Skipped (exists): '.$job['title']."\n";
            }
        }

        echo "\nTotal Jobs: ".Job::count()."\n";
        echo 'Active Jobs: '.Job::active()->count()."\n";
    }
}
