<?php

/**
 * Automobile industry category page content.
 */
return [
    'meta' => [
        'title' => 'Automobile HR Solutions | Accessories, Services & Dealerships | Mirashka',
        'description' => 'Mirashka HR solutions for automobile — technician hiring, service advisor recruitment, dealership sales staffing, HRaaS, payroll coordination and leadership hiring for accessories, service and mobility businesses.',
        'keywords' => 'automobile HR solutions, car service staffing, dealership hiring, automobile technician recruitment, Mirashka automobile',
    ],
    'hero' => [
        'label' => 'Automobile HR Solutions',
        'heading' => 'People Systems for Automobile Sales, Service and Mobility Growth',
        'subheading' => ['Automobile businesses need people who can sell with trust, service with skill, manage customers with care and execute operations with discipline.', 'Mirashka helps automobile companies build structured HR systems through technician hiring, service advisor recruitment, sales staffing, accessories team hiring, payroll coordination, HRaaS, compliance documentation, employee engagement and leadership hiring.', 'Whether you operate an automobile accessories business, detailing studio, car service centre, dealership, mobility company, workshop chain or automotive retail business, Mirashka helps you build a workforce that supports growth, service quality and customer trust.'],
        'ctas' => [
            [
                'label' => 'Book Automobile HR Consultation',
                'href' => '#industry-form',
            ],
            [
                'label' => 'Request Automobile HR Health Check',
                'href' => '#industry-health-check',
            ],
        ],
        'image' => 'assets/frontend/img/Whatwedo/we-build-influence-banner.webp',
        'image_fallback' => 'assets/frontend/img/Whatwedo/we-build-influence-banner.webp',
    ],
    'reality' => [
        'section_name' => 'Automobile HR Reality',
        'before_title' => 'The Automobile Workforce Challenge',
        'label' => 'The Automobile Workforce Challenge',
        'heading' => 'In automobile businesses, people decide the customer\'s trust before the vehicle moves',
        'paragraphs' => ['Automobile businesses operate in a highly customer-sensitive environment. A poorly trained technician, delayed service advisor, weak sales consultant, careless installation executive or unstructured workshop team can affect customer satisfaction, repeat business and brand reputation.', 'The automobile sector needs people who are technically skilled, process-oriented, disciplined, presentable and customer-focused. HR must support hiring, onboarding, payroll, attendance, documentation, training, retention and performance clarity.', 'Mirashka understands that automobile HR is not only about filling vacancies. It is about building a service-ready, sales-ready and customer-ready workforce.'],
        'challenges_heading' => 'Key Challenges',
        'pain_points' => ['Shortage of skilled automobile technicians', 'High attrition in sales and service roles', 'Workshop and service team coordination issues', 'Need for trained accessories installation teams', 'Payroll and incentive coordination complexity', 'Weak onboarding and training discipline', 'Customer-facing communication gaps', 'Attendance and shift tracking challenges', 'Multi-location dealership or service network management', 'Leadership gaps in showroom, service and operations teams'],
        'cta' => 'Discuss Automobile Workforce Challenges',
        'cta_href' => '#industry-form',
        'section_bg' => 'assets/frontend/img/tab-sec-bg.jpg',
        'image' => 'assets/frontend/img/industries/healthcare-workforce-challenge.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-risk.png',
        'image_alt' => 'Automobile workshop and HR dashboard for manpower, training and payroll',
        'standout' => [
            'before_title' => 'The Automobile Workforce Challenge',
            'heading' => 'In automobile businesses, people decide the customer\'s trust before the vehicle moves',
            'list_use_fontawesome' => true,
            'grid' => [
                'left_image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'left_image_fallback' => 'assets/frontend/img/compliance/cwi-card-training.png',
                'left_card' => [
                    'icon' => 'ri-car-line',
                    'title' => 'Key Challenges',
                    'list' => ['Shortage of skilled automobile technicians', 'High attrition in sales and service roles', 'Workshop and service team coordination issues', 'Need for trained accessories installation teams', 'Payroll and incentive coordination complexity'],
                ],
                'center' => [
                    'icon' => 'ri-car-line',
                    'title' => 'Why Automobile Workforce Management Is Different',
                    'paragraphs' => ['Automobile businesses operate in a highly customer-sensitive environment. A poorly trained technician, delayed service advisor, weak sales consultant, careless installation executive or unstructured workshop team can affect customer satisfaction, repeat business and brand reputation.', 'The automobile sector needs people who are technically skilled, process-oriented, disciplined, presentable and customer-focused. HR must support hiring, onboarding, payroll, attendance, documentation, training, retention and performance clarity.', 'Mirashka understands that automobile HR is not only about filling vacancies. It is about building a service-ready, sales-ready and customer-ready workforce.'],
                    'cta' => 'Discuss Automobile Workforce Challenges',
                    'cta_url' => '#industry-form',
                ],
                'right_card' => [
                    'icon' => 'ri-shield-check-line',
                    'title' => 'Key Challenges',
                    'list' => ['Weak onboarding and training discipline', 'Customer-facing communication gaps', 'Attendance and shift tracking challenges', 'Multi-location dealership or service network management', 'Leadership gaps in showroom, service and operations teams'],
                ],
                'right_image' => 'assets/frontend/img/compliance/cwi-integrity.png',
                'right_image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
            ],
        ],
    ],
    'sub_industries' => [
        'label' => 'Automobile Segments',
        'heading' => 'HR solutions for every major automobile business model',
        'content' => 'Automobile accessories, service businesses and dealerships operate differently. An accessories business needs installation and product knowledge. A service centre needs technicians and service advisors. A dealership needs sales, CRM, finance, insurance, delivery and operations teams. Mirashka builds HR solutions according to each business model.',
        'kicker' => 'Automobile',
        'section_bg' => 'assets/frontend/img/tab-sec-bg.jpg',
        'cta' => 'Speak to an Automobile HR Advisor',
        'cta_href' => '#industry-form',
        'cards' => [
            [
                'title' => 'Automobile Accessories',
                'kicker' => 'Automobile',
                'subcategories' => ['Accessories sales executives', 'Fitment technicians', 'Installation specialists', 'Store managers', 'Inventory executives', 'Product advisors', 'Customer support teams', 'Channel sales executives', 'Business leaders'],
                'description' => 'For automobile accessories brands, car accessory retailers, fitment centres, car audio businesses, aftermarket product companies and accessories distributors, Mirashka supports sales hiring, installation technician hiring, store staffing, customer support, payroll coordination and leadership hiring.',
                'cta' => 'Explore Automobile Accessories HR Solutions',
                'href' => '#automobile-accessories',
                'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-services.png',
            ],
            [
                'title' => 'Automobile Services',
                'kicker' => 'Automobile',
                'subcategories' => ['Service advisors', 'Automobile technicians', 'Detailing professionals', 'PPF installers', 'Ceramic coating experts', 'Washing staff', 'Workshop supervisors', 'Quality controllers', 'Customer care executives', 'Operations managers'],
                'description' => 'For car service centres, detailing studios, car care businesses, workshop chains, PPF and coating studios, repair workshops and maintenance businesses, Mirashka supports technician hiring, service advisor recruitment, detailing staff hiring, payroll coordination, HRaaS and operations leadership hiring.',
                'cta' => 'Explore Automobile Services HR Solutions',
                'href' => '#automobile-services',
                'image' => 'assets/frontend/img/hraas/hraas-hero-split.webp',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
            [
                'title' => 'Automobile Dealerships & Mobility',
                'kicker' => 'Automobile',
                'subcategories' => ['Sales consultants', 'Team leaders', 'CRM executives', 'Finance executives', 'Insurance executives', 'Delivery coordinators', 'Showroom managers', 'Fleet coordinators', 'Operations managers', 'Business heads'],
                'description' => 'For automobile dealerships, EV dealerships, used car businesses, mobility companies, fleet operators, leasing businesses and automotive retail groups, Mirashka supports sales teams, CRM, finance and insurance roles, delivery teams, operations staffing and leadership hiring.',
                'cta' => 'Explore Automobile Dealerships & Mobility HR Solutions',
                'href' => '#automobile-dealerships-mobility',
                'image' => 'assets/frontend/img/workforce/wfm-reporting-team-hands.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
            ],
        ],
    ],
    'pulse' => [
        'label' => 'PULSE for Automobile',
        'heading' => 'A people framework for technical skill, customer trust and operational scale',
        'content' => 'Mirashka applies its PULSE Framework to automobile businesses by connecting workforce discipline, HR operations, leadership hiring, technical staffing and HRaaS into one practical people system.',
        'cards' => [
            [
                'letter' => 'P',
                'title' => 'Protect',
                'subtitle' => 'Compliance & Workplace Integrity',
                'text' => 'Protect automobile businesses through employee documentation, workplace policies, POSH readiness, workshop conduct guidelines, customer handling standards and HR audits.',
                'image' => 'assets/img/protect.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-card-policy.png',
            ],
            [
                'letter' => 'U',
                'title' => 'Unify',
                'subtitle' => 'Workforce Management',
                'text' => 'Unify payroll inputs, attendance records, shift data, employee files, onboarding, exits, workshop records, showroom records and HR reporting.',
                'image' => 'assets/img/unify.png',
                'image_fallback' => 'assets/frontend/img/workforce/wfm-card-payroll.png',
            ],
            [
                'letter' => 'L',
                'title' => 'Lead',
                'subtitle' => 'Leadership & Organizational Excellence',
                'text' => 'Build leadership capability through showroom leaders, service heads, workshop managers, operations heads, sales heads and business leaders.',
                'image' => 'assets/img/lead.png',
                'image_fallback' => 'assets/frontend/img/leadership/ldr-board-advisory.png',
            ],
            [
                'letter' => 'S',
                'title' => 'Source',
                'subtitle' => 'Talent Acquisition & Staffing',
                'text' => 'Source technicians, service advisors, sales consultants, accessories fitment teams, detailing professionals, CRM teams and leadership talent.',
                'image' => 'assets/img/source.png',
                'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-card-executive-search.png',
            ],
            [
                'letter' => 'E',
                'title' => 'Empower',
                'subtitle' => 'HR as a Service',
                'text' => 'Empower automobile businesses with HR outsourcing, employee engagement, retention systems, employer branding, performance communication and HR technology.',
                'image' => 'assets/img/empower.png',
                'image_fallback' => 'assets/frontend/img/hraas/hraas-card-engagement.png',
            ],
        ],
        'cta' => [
            'label' => 'Apply PULSE to My Automobile Business',
            'href' => '#industry-form',
        ],
    ],
    'services' => [
        'label' => 'What Mirashka Delivers',
        'heading' => 'Complete HR support for automobile businesses that need skilled teams and customer-ready execution',
        'image' => 'assets/frontend/img/home/home-why-mirashka-hero.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
        'image_secondary' => 'assets/frontend/img/compliance/cwi-services.png',
        'image_secondary_fallback' => 'assets/frontend/img/hraas/hraas-page-partner.png',
        'cards' => [
            [
                'title' => 'Automobile Technician Hiring',
                'text' => 'Hiring support for mechanics, service technicians, electrical technicians, diagnostic technicians and workshop staff.',
                'icon' => 'ri-tools-line',
            ],
            [
                'title' => 'Service Advisor Recruitment',
                'text' => 'Recruitment for service advisors, customer care executives, workshop coordinators and service reception teams.',
                'icon' => 'ri-customer-service-line',
            ],
            [
                'title' => 'Accessories & Fitment Team Hiring',
                'text' => 'Hiring support for accessories sales executives, fitment technicians, installation experts, product advisors and store teams.',
                'icon' => 'ri-store-2-line',
            ],
            [
                'title' => 'Detailing & Car Care Staffing',
                'text' => 'Hiring support for car wash teams, detailing professionals, PPF installers, coating experts, polishers and quality controllers.',
                'icon' => 'ri-drop-line',
            ],
            [
                'title' => 'Dealership Sales Hiring',
                'text' => 'Recruitment for sales consultants, team leaders, showroom executives, CRM teams, finance executives and insurance executives.',
                'icon' => 'ri-car-line',
            ],
            [
                'title' => 'Operations & Workshop Leadership Hiring',
                'text' => 'Search support for workshop managers, showroom managers, operations heads, service heads, sales heads and business leaders.',
                'icon' => 'ri-user-star-line',
            ],
            [
                'title' => 'HRaaS & HR Outsourcing',
                'text' => 'Dedicated HR support for automobile businesses that need structured HR execution without building a large internal HR department.',
                'icon' => 'ri-customer-service-2-line',
            ],
            [
                'title' => 'Payroll, Attendance & Incentive Coordination',
                'text' => 'Attendance inputs, shift records, overtime data, incentives, commissions, salary changes, deductions and payroll communication.',
                'icon' => 'ri-money-dollar-circle-line',
            ],
            [
                'title' => 'Policy, Documentation & HR Audits',
                'text' => 'Employee handbooks, appointment letters, workshop conduct guidelines, customer handling standards, exit documents, HR audits and compliance checklists.',
                'icon' => 'ri-file-list-3-line',
            ],
            [
                'title' => 'HR Technology & Reporting',
                'text' => 'Dashboards for hiring, attendance, payroll, training, employee records, workshop manpower, sales teams, attrition and HR action plans.',
                'icon' => 'ri-computer-line',
            ],
        ],
        'cta' => [
            'label' => 'Explore Automobile HR Services',
            'href' => 'whatwedo',
        ],
    ],
    'hiring_strategy' => [
        'section_id' => 'industry-hiring-strategy',
        'label' => 'Workforce Strategy',
        'heading' => 'Automobile hiring needs skill-fit, service-fit, sales-fit and reliability-fit',
        'intro' => ['Automobile roles are highly practical and customer-facing. A technician must diagnose accurately. A service advisor must communicate clearly. A sales consultant must build trust. A detailing professional must work with precision. A workshop manager must control people, quality, timelines and customer experience.', 'Mirashka helps automobile businesses define workforce needs before sourcing. We map role expectations, technical skill, customer interaction level, showroom or workshop requirement, location needs, salary range, incentive structure, training needs and retention risk.'],
        'groups' => [
            [
                'title' => 'Hiring Strategy Includes',
                'items' => ['Role and KRA definition', 'Location-wise manpower planning', 'Workshop or showroom team mapping', 'Candidate sourcing and screening', 'Technical skill and service-fit review', 'Customer communication-fit review', 'Interview coordination', 'Salary and incentive alignment', 'Joining and documentation checklist', 'Weekly hiring dashboard'],
            ],
            [
                'title' => 'Workforce Strategy Includes',
                'items' => ['Workshop manpower planning', 'Service bay and technician mapping', 'Showroom staffing structure', 'Attendance and shift coordination', 'Incentive and commission tracking support', 'Training and onboarding support', 'Attrition tracking', 'Performance communication rhythm', 'Monthly HR reporting'],
            ],
        ],
        'image' => 'assets/frontend/img/industries/healthcare-hiring-workforce-strategy.webp',
        'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
        'image_alt' => 'Automobile hiring funnel with filters: Technical Fit, Service Fit, Sales Fit, Customer Fit and Retention Fit',
        'image_secondary' => 'assets/frontend/img/industries/healthcare-workforce-challenge.webp',
        'image_secondary_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
        'image_secondary_alt' => 'Automobile workforce planning and structured hiring support',
        'cta' => [
            'label' => 'Build My Automobile Talent Pipeline',
            'href' => '#industry-form',
        ],
    ],
    'compliance' => [
        'label' => 'HR Operations',
        'heading' => 'Create people discipline across workshops, showrooms, studios and service teams',
        'intro' => ['Automobile businesses often operate through workshops, service bays, showrooms, accessories stores, detailing studios, field teams and customer support desks. This creates the need for structured attendance, payroll inputs, incentives, employee documentation, onboarding, training records and exit processes.', 'Mirashka helps automobile businesses create HR operating systems that improve workforce visibility, reduce confusion and support consistent customer experience.'],
        'image' => 'assets/frontend/img/industries/healthcare-compliance-documentation-hr-operations.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-card-policy.png',
        'image_alt' => 'Automobile employee file, attendance dashboard and workshop conduct handbook visual',
        'cta' => 'Request Automobile HR Documentation Review',
        'cta_href' => '#industry-form',
        'cards' => [
            [
                'title' => 'Employee Documentation',
                'text' => 'Appointment letters, joining forms, ID proofs, qualification records, experience records, skill records and employee files.',
                'icon' => 'ri-file-list-3-line',
                'image' => 'assets/frontend/img/compliance/cwi-card-policy.png',
            ],
            [
                'title' => 'Attendance & Shift Process',
                'text' => 'Shift rosters, attendance inputs, weekly offs, late marks, overtime, leave records and manager approvals.',
                'icon' => 'ri-calendar-check-line',
                'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'active' => true,
            ],
            [
                'title' => 'Workshop & Showroom Conduct Guidelines',
                'text' => 'Customer handling standards, uniform rules, service discipline, tool usage, vehicle handling process, escalation protocol and workplace behavior guidelines.',
                'icon' => 'ri-book-2-line',
                'image' => 'assets/frontend/img/compliance/cwi-risk.png',
            ],
            [
                'title' => 'Incentive & Payroll Coordination',
                'text' => 'Salary inputs, attendance data, incentives, commissions, overtime, deductions, reimbursements and payroll communication.',
                'icon' => 'ri-money-dollar-circle-line',
                'image' => 'assets/frontend/img/workforce/wfm-card-payroll.png',
                'active' => true,
            ],
            [
                'title' => 'Training & Skill Records',
                'text' => 'Technician training records, product training, service advisor training, detailing process training, SOP acknowledgement and performance improvement tracking.',
                'icon' => 'ri-graduation-cap-line',
                'image' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
            [
                'title' => 'Exit Management',
                'text' => 'Resignation documentation, tool or asset return, customer handover, clearance checklist, full and final coordination and exit feedback.',
                'icon' => 'ri-logout-box-r-line',
                'image' => 'assets/frontend/img/compliance/cwi-services.png',
                'active' => true,
            ],
        ],
    ],
    'use_cases' => [
        'label' => 'Automobile HR Support in Action',
        'heading' => 'Practical people solutions for automobile growth challenges',
        'tags' => ['Skilled Technicians', 'Better Service', 'Stronger Sales', 'Cleaner Payroll'],
        'cards' => [
            [
                'tab_id' => 'tech-hiring',
                'tab_label' => 'Technicians',
                'title' => 'Case Study 1: Technician Hiring for Service Centre Expansion',
                'pane_heading' => 'Workshop-wise manpower plan and technical screening for service expansion.',
                'challenge' => 'An automobile service business needed skilled technicians, service advisors and workshop support staff for expansion.',
                'approach' => 'Created workshop-wise manpower plan, technical screening checklist, sourcing process and joining coordination system.',
                'outcome' => 'Faster hiring, better technical fit and stronger service centre readiness.',
                'image' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
            ],
            [
                'tab_id' => 'detailing',
                'tab_label' => 'Detailing',
                'title' => 'Case Study 2: Detailing Studio Workforce Structuring',
                'pane_heading' => 'Structured hiring for detailers, PPF installers and coating experts.',
                'challenge' => 'A car care and detailing business needed structured hiring for detailers, PPF installers, coating experts and washing teams.',
                'approach' => 'Defined role expectations, mapped skill requirements, created training and onboarding checklist and hiring dashboard.',
                'outcome' => 'Improved staffing clarity, stronger process discipline and better customer experience consistency.',
                'image' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
                'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
            ],
            [
                'tab_id' => 'dealership',
                'tab_label' => 'Dealership',
                'title' => 'Case Study 3: Dealership Sales Team Hiring',
                'pane_heading' => 'Showroom-wise hiring plan with communication-fit screening.',
                'challenge' => 'An automobile dealership needed sales consultants, CRM executives and delivery coordinators to improve showroom performance.',
                'approach' => 'Created showroom-wise hiring plan, communication-fit screening and interview coordination process.',
                'outcome' => 'Better customer-facing fit, faster shortlisting and stronger showroom team visibility.',
                'image' => 'assets/frontend/img/workforce/wfm-hero.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-services.png',
            ],
            [
                'tab_id' => 'payroll',
                'tab_label' => 'Payroll',
                'title' => 'Case Study 4: Payroll and Incentive Structuring',
                'pane_heading' => 'Attendance input rhythm and incentive tracking across sales and service teams.',
                'challenge' => 'An automobile business had unclear attendance, incentive and commission inputs across sales and service teams.',
                'approach' => 'Designed attendance input rhythm, incentive tracking format, payroll coordination process and monthly HR dashboard.',
                'outcome' => 'Cleaner payroll inputs, better management visibility and reduced internal confusion.',
                'image' => 'assets/frontend/img/compliance/cwi-card-policy.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
        ],
        'cta' => [
            'label' => 'Discuss a Similar Automobile Case',
            'href' => '#industry-form',
        ],
    ],
    'health_check' => [
        'label' => 'Start With Diagnosis',
        'heading' => 'How ready is your automobile HR system for growth?',
        'content' => 'Mirashka\'s Automobile HR Health Check helps accessories businesses, service centres, detailing studios, dealerships, mobility companies and workshop chains identify gaps in hiring, payroll, attendance, documentation, employee engagement, training, leadership and HR technology.',
        'covers' => ['Hiring process quality', 'Role clarity and KRAs', 'Technician and service team gaps', 'Showroom or workshop manpower gaps', 'Attendance and shift process', 'Payroll and incentive input discipline', 'Employee documentation', 'Training and skill record readiness', 'POSH and workplace ethics readiness', 'Attrition and retention risk', 'Customer-facing behavior standards', 'Leadership gap assessment', 'HR technology readiness', 'Reporting and dashboard maturity'],
        'output' => 'A practical HR improvement roadmap with risk areas, priority actions and recommended Mirashka service plan.',
        'cta' => [
            'label' => 'Request Automobile HR Health Check',
            'href' => '#industry-form',
        ],
        'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
    ],
    'form' => [
        'label' => 'Talk to Mirashka',
        'heading' => 'Build a stronger automobile workforce with Mirashka',
        'content' => 'Share your automobile HR requirement. Mirashka will help identify whether you need technician hiring, service advisor recruitment, accessories staffing, dealership sales hiring, HRaaS, payroll coordination, documentation, employee engagement or a complete people operating model.',
        'lead_type' => 'automobile_hr_enquiry',
        'segments' => ['Automobile Accessories', 'Automobile Services', 'Automobile Dealerships & Mobility', 'Car Care / Detailing Studio', 'EV Dealership', 'Used Car Business', 'Workshop Chain', 'Automotive Retail Business', 'Other Automobile Business'],
        'services' => ['Technician Hiring', 'Service Advisor Hiring', 'Accessories Team Hiring', 'Detailing / PPF / Coating Staff Hiring', 'Dealership Sales Hiring', 'CRM / Customer Support Hiring', 'Workshop / Operations Leadership Hiring', 'HRaaS / HR Outsourcing', 'Payroll & Incentive Coordination', 'Policy Documentation', 'Training Records & HR Reporting', 'Employee Engagement', 'HR Technology', 'Not Sure — Need Consultation'],
        'submit' => 'Submit Automobile HR Enquiry',
        'secondary_cta' => [
            'label' => 'Book 30-Minute Automobile HR Consultation',
            'href' => 'https://calendly.com/elevateonemedia/30min',
        ],
        'image' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-page-partner.png',
    ],
    'faq_blog' => [
        'label' => 'Learn More',
        'heading' => 'Automobile HR questions answered',
        'faqs' => [
            [
                'question' => 'What automobile roles can Mirashka help hire for?',
                'answer' => 'Mirashka can support hiring for technicians, service advisors, sales consultants, accessories fitment teams, detailing professionals, CRM executives, workshop managers, showroom managers and leadership roles.',
            ],
            [
                'question' => 'Can Mirashka support hiring for car care and detailing businesses?',
                'answer' => 'Yes. Mirashka can support hiring for detailers, PPF installers, coating experts, washing teams, quality controllers, service advisors and studio managers.',
            ],
            [
                'question' => 'Can Mirashka help with dealership sales hiring?',
                'answer' => 'Yes. Mirashka can support hiring for sales consultants, team leaders, CRM executives, finance executives, insurance executives, delivery coordinators and showroom managers.',
            ],
            [
                'question' => 'Does Mirashka provide HRaaS for automobile businesses?',
                'answer' => 'Yes. Mirashka HRaaS is suitable for accessories businesses, service centres, dealerships, detailing studios, workshop chains and mobility companies.',
            ],
            [
                'question' => 'Can Mirashka help with payroll and incentive coordination?',
                'answer' => 'Yes. Mirashka can support attendance inputs, salary data, incentives, commissions, overtime, deductions, reimbursements and payroll communication.',
            ],
        ],
        'blogs' => [],
        'cta' => [
            'label' => 'Read Automobile HR Insights',
            'href' => '/blog',
        ],
        'image' => 'assets/frontend/img/industries/industry-form-consultant.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
    ],
];
