<?php

/**
 * Consumer & Retail industry category page content.
 */
return [
    'meta' => [
        'title' => 'Consumer & Retail HR Solutions | E-commerce, Fashion & F&B | Mirashka',
        'description' => 'Mirashka HR solutions for consumer and retail — staffing, recruitment, HRaaS, payroll coordination, store workforce planning and leadership hiring for e-commerce, fashion and food & beverage businesses.',
        'keywords' => 'consumer retail HR solutions, retail staffing, e-commerce hiring, fashion apparel HR, food beverage staffing, retail HRaaS, Mirashka consumer retail',
    ],

    'hero' => [
        'label' => 'Consumer & Retail HR Solutions',
        'heading' => 'People Systems for Brands That Sell, Serve and Scale',
        'subheading' => [
            'Consumer and retail businesses grow through people who can serve customers, manage operations, represent the brand and execute with consistency.',
            'Mirashka helps e-commerce companies, fashion and apparel brands, food and beverage businesses, retail chains and consumer product companies build structured HR systems through staffing, recruitment, payroll coordination, HRaaS, employee engagement, compliance documentation, store workforce planning and leadership hiring.',
            'Whether you need store teams, warehouse staff, customer support executives, sales promoters, category managers, operations managers or retail leaders, Mirashka helps you build a workforce that supports growth and customer experience.',
        ],
        'ctas' => [
            ['label' => 'Book Consumer & Retail HR Consultation', 'href' => '#industry-form'],
            ['label' => 'Request Retail HR Health Check', 'href' => '#industry-health-check'],
        ],
        'image' => 'assets/frontend/img/Whatwedo/we-build-influence-banner.webp',
        'image_fallback' => 'assets/frontend/img/Whatwedo/we-build-influence-banner.webp',
    ],

    'reality' => [
        'section_name' => 'Consumer & Retail HR Reality',
        'before_title' => 'The Retail Workforce Challenge',
        'label' => 'The Retail Workforce Challenge',
        'heading' => 'In consumer businesses, frontline people shape customer trust every day',
        'paragraphs' => [
            'Consumer and retail businesses operate in fast-moving environments. Customer experience, sales conversion, order fulfilment, inventory movement, store discipline, delivery coordination and brand perception depend heavily on people.',
            'The challenge is not only hiring quickly. Retail and consumer companies need people who are reliable, trained, presentable, process-oriented, customer-friendly and aligned with brand expectations.',
            'Mirashka understands that consumer and retail HR requires speed, structure and retention discipline. The right people must be hired, onboarded, scheduled, paid, engaged and monitored with clarity.',
        ],
        'challenges_heading' => 'Key Challenges',
        'pain_points' => [
            'High attrition in frontline and store roles',
            'Urgent hiring for sales, support and operations',
            'Multi-location workforce coordination',
            'Attendance and payroll input complexity',
            'Seasonal and festive hiring pressure',
            'Weak onboarding and training discipline',
            'Customer-facing behavior inconsistency',
            'Store and warehouse staffing gaps',
            'Leadership gaps in retail operations',
            'Lack of structured employee engagement',
        ],
        'cta' => 'Discuss Consumer & Retail Workforce Challenges',
        'cta_href' => '#industry-form',
        'section_bg' => 'assets/frontend/img/tab-sec-bg.jpg',
        'image' => 'assets/frontend/img/industries/healthcare-workforce-challenge.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-risk.png',
        'image_alt' => 'Retail store, e-commerce warehouse and HR dashboard for consumer businesses',
        'standout' => [
            'before_title' => 'The Retail Workforce Challenge',
            'heading' => 'In consumer businesses, frontline people shape customer trust every day',
            'list_use_fontawesome' => true,
            'grid' => [
                'left_image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'left_image_fallback' => 'assets/frontend/img/compliance/cwi-card-training.png',
                'left_card' => [
                    'icon' => 'ri-store-2-line',
                    'title' => 'Key Challenges',
                    'list' => [
                        'High attrition in frontline and store roles',
                        'Urgent hiring for sales, support and operations',
                        'Multi-location workforce coordination',
                        'Attendance and payroll input complexity',
                        'Seasonal and festive hiring pressure',
                    ],
                ],
                'center' => [
                    'icon' => 'ri-store-2-line',
                    'title' => 'Why Consumer & Retail Workforce Management Is Different',
                    'paragraphs' => [
                        'Consumer and retail businesses operate in fast-moving environments. Customer experience, sales conversion, order fulfilment, inventory movement, store discipline, delivery coordination and brand perception depend heavily on people.',
                        'The challenge is not only hiring quickly. Retail and consumer companies need people who are reliable, trained, presentable, process-oriented, customer-friendly and aligned with brand expectations.',
                        'Mirashka understands that consumer and retail HR requires speed, structure and retention discipline.',
                    ],
                    'cta' => 'Discuss Consumer & Retail Workforce Challenges',
                    'cta_url' => '#industry-form',
                ],
                'right_card' => [
                    'icon' => 'ri-shield-check-line',
                    'title' => 'Key Challenges',
                    'list' => [
                        'Weak onboarding and training discipline',
                        'Customer-facing behavior inconsistency',
                        'Store and warehouse staffing gaps',
                        'Leadership gaps in retail operations',
                        'Lack of structured employee engagement',
                    ],
                ],
                'right_image' => 'assets/frontend/img/compliance/cwi-integrity.png',
                'right_image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
            ],
        ],
    ],

    'sub_industries' => [
        'label' => 'Consumer & Retail Segments',
        'heading' => 'HR solutions for every major consumer-facing business model',
        'content' => 'A fashion brand, an e-commerce company and a food business have very different workforce needs. Mirashka builds HR solutions according to customer touchpoints, operating model, location spread, role type, seasonality and business scale.',
        'kicker' => 'Consumer & Retail',
        'section_bg' => 'assets/frontend/img/tab-sec-bg.jpg',
        'cta' => 'Speak to a Consumer & Retail HR Advisor',
        'cta_href' => '#industry-form',
        'cards' => [
            [
                'title' => 'E-commerce',
                'kicker' => 'Consumer & Retail',
                'subcategories' => [
                    'Warehouse executives',
                    'Customer support teams',
                    'Order processing staff',
                    'Category managers',
                    'Catalogue executives',
                    'Logistics coordinators',
                    'Digital marketing teams',
                    'Operations managers',
                    'Business leaders',
                ],
                'description' => 'For online marketplaces, D2C brands, fulfilment businesses, digital commerce platforms and online retail companies, Mirashka supports warehouse staffing, customer support hiring, category roles, operations hiring, HRaaS, payroll coordination and leadership hiring.',
                'cta' => 'Explore E-commerce HR Solutions',
                'href' => '#e-commerce',
                'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-services.png',
            ],
            [
                'title' => 'Fashion & Apparel',
                'kicker' => 'Consumer & Retail',
                'subcategories' => [
                    'Store managers',
                    'Fashion consultants',
                    'Sales executives',
                    'Merchandisers',
                    'Visual merchandisers',
                    'Inventory staff',
                    'Production coordinators',
                    'Retail operations managers',
                    'Brand leaders',
                ],
                'description' => 'For fashion brands, apparel manufacturers, retail stores, boutiques, lifestyle brands and multi-store apparel businesses, Mirashka supports store hiring, sales staffing, visual merchandising roles, production support, payroll coordination and leadership hiring.',
                'cta' => 'Explore Fashion & Apparel HR Solutions',
                'href' => '#fashion-apparel',
                'image' => 'assets/frontend/img/hraas/hraas-hero-split.webp',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
            [
                'title' => 'Food & Beverage',
                'kicker' => 'Consumer & Retail',
                'subcategories' => [
                    'Chefs',
                    'Kitchen helpers',
                    'Outlet managers',
                    'Service staff',
                    'Cashiers',
                    'Delivery coordinators',
                    'Quality executives',
                    'Inventory staff',
                    'Operations managers',
                    'Business heads',
                ],
                'description' => 'For restaurants, cloud kitchens, cafes, QSR brands, packaged food companies and F&B retail chains, Mirashka supports kitchen staff hiring, service staff, outlet teams, delivery coordination, payroll, shift planning, HRaaS and operations leadership hiring.',
                'cta' => 'Explore Food & Beverage HR Solutions',
                'href' => '#food-beverage',
                'image' => 'assets/frontend/img/workforce/wfm-reporting-team-hands.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
            ],
        ],
    ],

    'pulse' => [
        'label' => 'PULSE for Consumer & Retail',
        'heading' => 'A people framework for customer experience, operational discipline and retail scale',
        'content' => 'Mirashka applies its PULSE Framework to consumer and retail businesses by connecting workforce discipline, HR operations, leadership hiring, staffing and HRaaS into one practical people system.',
        'cards' => [
            [
                'letter' => 'P',
                'title' => 'Protect',
                'subtitle' => 'Compliance & Workplace Integrity',
                'text' => 'Protect retail businesses through employee documentation, workplace policies, POSH readiness, code of conduct, attendance rules and HR audits.',
                'image' => 'assets/img/protect.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-card-policy.png',
            ],
            [
                'letter' => 'U',
                'title' => 'Unify',
                'subtitle' => 'Workforce Management',
                'text' => 'Unify payroll inputs, attendance, shift records, employee files, onboarding, exits, store records and HR reporting across locations.',
                'image' => 'assets/img/unify.png',
                'image_fallback' => 'assets/frontend/img/workforce/wfm-card-payroll.png',
            ],
            [
                'letter' => 'L',
                'title' => 'Lead',
                'subtitle' => 'Leadership & Organizational Excellence',
                'text' => 'Build leadership capability through store leaders, operations managers, category heads, retail heads, supply chain leaders and business heads.',
                'image' => 'assets/img/lead.png',
                'image_fallback' => 'assets/frontend/img/leadership/ldr-board-advisory.png',
            ],
            [
                'letter' => 'S',
                'title' => 'Source',
                'subtitle' => 'Talent Acquisition & Staffing',
                'text' => 'Source frontline, store, warehouse, customer support, sales, operations, production and leadership talent.',
                'image' => 'assets/img/source.png',
                'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-card-executive-search.png',
            ],
            [
                'letter' => 'E',
                'title' => 'Empower',
                'subtitle' => 'HR as a Service',
                'text' => 'Empower consumer brands with HR outsourcing, employer branding, employee engagement, retention systems and HR technology.',
                'image' => 'assets/img/empower.png',
                'image_fallback' => 'assets/frontend/img/hraas/hraas-card-engagement.png',
            ],
        ],
        'cta' => ['label' => 'Apply PULSE to My Consumer Brand', 'href' => '#industry-form'],
    ],

    'services' => [
        'label' => 'What Mirashka Delivers',
        'heading' => 'Complete HR support for brands that need fast hiring and consistent execution',
        'image' => 'assets/frontend/img/home/home-why-mirashka-hero.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
        'image_secondary' => 'assets/frontend/img/compliance/cwi-services.png',
        'image_secondary_fallback' => 'assets/frontend/img/hraas/hraas-page-partner.png',
        'cards' => [
            ['title' => 'Retail Staffing', 'text' => 'Hiring support for store teams, sales executives, promoters, customer-facing staff and retail operations roles.', 'icon' => 'ri-store-2-line'],
            ['title' => 'E-commerce Workforce Hiring', 'text' => 'Support for warehouse teams, order processing, catalogue roles, customer support, logistics coordination and operations hiring.', 'icon' => 'ri-shopping-cart-line'],
            ['title' => 'Fashion & Apparel Talent Hiring', 'text' => 'Recruitment for store managers, fashion consultants, merchandisers, production coordinators and brand support roles.', 'icon' => 'ri-shirt-line'],
            ['title' => 'Food & Beverage Staffing', 'text' => 'Hiring support for chefs, kitchen staff, outlet teams, service staff, cashiers, delivery coordinators and operations teams.', 'icon' => 'ri-restaurant-line'],
            ['title' => 'Leadership Hiring', 'text' => 'Hiring support for retail heads, category heads, operations heads, supply chain leaders, brand heads and CXO roles.', 'icon' => 'ri-user-star-line'],
            ['title' => 'HRaaS & HR Outsourcing', 'text' => 'Dedicated HR support for consumer brands that need structured HR execution without building a large internal HR team.', 'icon' => 'ri-customer-service-2-line'],
            ['title' => 'Payroll & Shift Coordination', 'text' => 'Attendance inputs, shift data, overtime records, salary changes, reimbursement tracking and payroll communication.', 'icon' => 'ri-money-dollar-circle-line'],
            ['title' => 'Policy & Documentation Support', 'text' => 'Employee handbooks, appointment letters, attendance policies, store conduct guidelines, exit documents and HR policy manuals.', 'icon' => 'ri-file-list-3-line'],
            ['title' => 'Employee Engagement & Retention', 'text' => 'Employee feedback, attrition review, retention planning, performance communication and engagement programs.', 'icon' => 'ri-emotion-happy-line'],
            ['title' => 'HR Technology & Reporting', 'text' => 'Dashboards for hiring, attendance, payroll, attrition, employee records, store manpower and HR action plans.', 'icon' => 'ri-computer-line'],
        ],
        'cta' => ['label' => 'Explore Consumer & Retail HR Services', 'href' => 'whatwedo'],
    ],

    'hiring_strategy' => [
        'section_id' => 'industry-hiring-strategy',
        'label' => 'Talent Strategy',
        'heading' => 'Retail hiring needs speed-fit, service-fit, reliability-fit and brand-fit',
        'intro' => [
            'Consumer and retail roles are often customer-facing, location-sensitive and time-critical. A store executive must represent the brand. A warehouse employee must follow process. A customer support executive must communicate clearly. An outlet manager must manage people, inventory and service pressure.',
            'Mirashka helps consumer businesses define workforce needs before sourcing. We map role expectations, location needs, shift requirements, customer interaction level, salary range, experience requirement, training needs and retention risk.',
        ],
        'groups' => [
            [
                'title' => 'Hiring Strategy Includes',
                'items' => [
                    'Role and KRA definition',
                    'Location-wise hiring plan',
                    'Store or outlet manpower mapping',
                    'Candidate sourcing and screening',
                    'Communication and grooming fit review',
                    'Customer-facing aptitude review',
                    'Interview coordination',
                    'Salary and expectation alignment',
                    'Joining and documentation checklist',
                    'Weekly hiring dashboard',
                ],
            ],
            [
                'title' => 'Workforce Strategy Includes',
                'items' => [
                    'Store-wise manpower planning',
                    'Shift and attendance coordination',
                    'Seasonal hiring planning',
                    'Employee lifecycle documentation',
                    'Training and onboarding support',
                    'Payroll input discipline',
                    'Attrition tracking',
                    'Performance communication rhythm',
                    'Monthly HR reporting',
                ],
            ],
        ],
        'image' => 'assets/frontend/img/industries/healthcare-hiring-workforce-strategy.webp',
        'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
        'image_alt' => 'Retail hiring funnel with filters: Service Fit, Reliability Fit, Brand Fit, Location Fit and Retention Fit',
        'image_secondary' => 'assets/frontend/img/industries/healthcare-workforce-challenge.webp',
        'image_secondary_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
        'image_secondary_alt' => 'Consumer and retail workforce planning and structured hiring support',
        'cta' => [
            'label' => 'Build My Retail Talent Pipeline',
            'href' => '#industry-form',
        ],
    ],

    'compliance' => [
        'label' => 'HR Operations',
        'heading' => 'Create people discipline across stores, warehouses, outlets and support teams',
        'intro' => [
            'Consumer and retail businesses often operate across multiple locations, shifts, outlets, warehouses and customer touchpoints. This makes payroll, attendance, documentation, onboarding, exit process and HR reporting highly important.',
            'Mirashka helps consumer businesses create HR operating systems that improve control, reduce confusion and support consistent workforce execution.',
        ],
        'image' => 'assets/frontend/img/industries/healthcare-compliance-documentation-hr-operations.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-card-policy.png',
        'image_alt' => 'Retail employee file, attendance dashboard, store policy handbook and compliance shield visual',
        'cta' => 'Request Retail HR Documentation Review',
        'cta_href' => '#industry-form',
        'cards' => [
            [
                'title' => 'Employee Documentation',
                'text' => 'Appointment letters, joining forms, ID proofs, qualification records, experience records and employee files.',
                'icon' => 'ri-file-list-3-line',
                'image' => 'assets/frontend/img/compliance/cwi-card-policy.png',
            ],
            [
                'title' => 'Attendance & Shift Process',
                'text' => 'Shift roster, attendance inputs, late mark process, overtime inputs, weekly offs, leave records and manager approvals.',
                'icon' => 'ri-calendar-check-line',
                'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'active' => true,
            ],
            [
                'title' => 'Store / Outlet Conduct Guidelines',
                'text' => 'Dress code, customer interaction standards, escalation process, cash handling discipline, product knowledge expectations and service behavior.',
                'icon' => 'ri-book-2-line',
                'image' => 'assets/frontend/img/compliance/cwi-risk.png',
            ],
            [
                'title' => 'Payroll Coordination',
                'text' => 'Salary inputs, attendance data, incentives, overtime, reimbursements, deductions and payroll communication.',
                'icon' => 'ri-money-dollar-circle-line',
                'image' => 'assets/frontend/img/workforce/wfm-card-payroll.png',
                'active' => true,
            ],
            [
                'title' => 'HR Audit & Risk Review',
                'text' => 'Review of employee records, documentation gaps, attendance process, payroll inputs, exit process, POSH readiness and HR compliance gaps.',
                'icon' => 'ri-search-eye-line',
                'image' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
            [
                'title' => 'Exit Management',
                'text' => 'Resignation documentation, handover process, stock or asset return, clearance checklist, full and final coordination and exit feedback.',
                'icon' => 'ri-logout-box-r-line',
                'image' => 'assets/frontend/img/compliance/cwi-services.png',
                'active' => true,
            ],
        ],
    ],

    'use_cases' => [
        'label' => 'Consumer & Retail HR Support in Action',
        'heading' => 'Practical people solutions for customer-facing growth challenges',
        'tags' => ['Faster Hiring', 'Better Store Control', 'Lower Attrition', 'Stronger Operations'],
        'cards' => [
            [
                'tab_id' => 'store-team',
                'tab_label' => 'Store Team',
                'title' => 'Case Study 1: Store Team Hiring for a Growing Retail Brand',
                'pane_heading' => 'Structured hiring for store executives, sales staff and store managers across multiple locations.',
                'challenge' => 'A growing retail business needed store executives, sales staff and store managers across multiple locations.',
                'approach' => 'Created location-wise hiring plan, role clarity, screening process and joining coordination system.',
                'outcome' => 'Faster shortlisting, better candidate fit and stronger store workforce visibility.',
                'image' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
            ],
            [
                'tab_id' => 'ecommerce-ops',
                'tab_label' => 'E-commerce',
                'title' => 'Case Study 2: E-commerce Operations Staffing',
                'pane_heading' => 'Warehouse, catalogue, customer support and operations staff during growth season.',
                'challenge' => 'An e-commerce business needed warehouse, catalogue, customer support and operations staff during growth season.',
                'approach' => 'Mapped function-wise manpower needs, created sourcing plan and managed weekly hiring reporting.',
                'outcome' => 'Improved staffing speed and better operational readiness.',
                'image' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
                'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
            ],
            [
                'tab_id' => 'fb-shifts',
                'tab_label' => 'F&B Shifts',
                'title' => 'Case Study 3: F&B Shift Workforce Structuring',
                'pane_heading' => 'Shift roster visibility, attendance rhythm and role handover across outlets.',
                'challenge' => 'A food business faced attendance confusion, shift gaps and inconsistent role handovers across outlets.',
                'approach' => 'Designed shift roster visibility, attendance input rhythm, role handover checklist and HR reporting process.',
                'outcome' => 'Improved workforce control and smoother outlet operations.',
                'image' => 'assets/frontend/img/workforce/wfm-hero.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-services.png',
            ],
            [
                'tab_id' => 'retail-leadership',
                'tab_label' => 'Leadership',
                'title' => 'Case Study 4: Retail Leadership Hiring',
                'pane_heading' => 'Operations leader for stores, teams, inventory discipline and customer experience.',
                'challenge' => 'A consumer brand needed an operations leader to manage stores, teams, inventory discipline and customer experience.',
                'approach' => 'Defined leadership mandate, mapped relevant retail talent and supported structured evaluation.',
                'outcome' => 'Better leadership alignment and stronger expansion readiness.',
                'image' => 'assets/frontend/img/compliance/cwi-card-policy.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
        ],
        'cta' => ['label' => 'Discuss a Similar Retail Case', 'href' => '#industry-form'],
    ],

    'health_check' => [
        'label' => 'Start With Diagnosis',
        'heading' => 'How ready is your consumer business HR system for scale?',
        'content' => 'Mirashka’s Consumer & Retail HR Health Check helps e-commerce companies, fashion brands, apparel businesses, restaurants, cafes, retail chains and consumer product companies identify gaps in hiring, payroll, attendance, documentation, employee engagement, leadership and HR technology.',
        'covers' => [
            'Hiring process quality',
            'Role clarity and KRAs',
            'Store or location-wise manpower gaps',
            'Attendance and shift process',
            'Payroll input discipline',
            'Employee documentation',
            'Onboarding process',
            'POSH and workplace ethics readiness',
            'Attrition and retention risk',
            'Customer-facing behavior standards',
            'Leadership gap assessment',
            'HR technology readiness',
            'Reporting and dashboard maturity',
        ],
        'output' => 'A practical HR improvement roadmap with risk areas, priority actions and recommended Mirashka service plan.',
        'cta' => ['label' => 'Request Consumer & Retail HR Health Check', 'href' => '#industry-form'],
        'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
    ],

    'form' => [
        'label' => 'Talk to Mirashka',
        'heading' => 'Build a stronger consumer and retail workforce with Mirashka',
        'content' => 'Share your consumer or retail HR requirement. Mirashka will help identify whether you need staffing, recruitment, HRaaS, payroll coordination, attendance discipline, leadership hiring, employee engagement, documentation or a complete people operating model.',
        'lead_type' => 'consumer_retail_hr_enquiry',
        'segments' => [
            'E-commerce',
            'Fashion & Apparel',
            'Food & Beverage',
            'Retail Chain',
            'D2C Brand',
            'Consumer Product Company',
            'Lifestyle Brand',
            'Other Consumer Business',
        ],
        'services' => [
            'Retail Staffing',
            'E-commerce Operations Hiring',
            'Store Team Hiring',
            'F&B Staffing',
            'Leadership Hiring',
            'HRaaS / HR Outsourcing',
            'Payroll & Attendance Coordination',
            'Policy Documentation',
            'Compliance Audit',
            'Employee Engagement',
            'HR Technology',
            'Not Sure — Need Consultation',
        ],
        'submit' => 'Submit Consumer & Retail HR Enquiry',
        'secondary_cta' => ['label' => 'Book 30-Minute Retail HR Consultation', 'href' => 'https://calendly.com/elevateonemedia/30min'],
        'image' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-page-partner.png',
    ],

    'faq_blog' => [
        'label' => 'Learn More',
        'heading' => 'Consumer & retail HR questions answered',
        'faqs' => [
            [
                'question' => 'What consumer and retail roles can Mirashka help hire for?',
                'answer' => 'Mirashka can support hiring for store teams, sales executives, warehouse staff, customer support teams, outlet staff, operations managers, category roles and leadership positions.',
            ],
            [
                'question' => 'Can Mirashka support multi-location retail hiring?',
                'answer' => 'Yes. Mirashka can create location-wise hiring plans and manage candidate sourcing, screening, joining coordination and hiring dashboards.',
            ],
            [
                'question' => 'Does Mirashka provide HRaaS for retail and consumer brands?',
                'answer' => 'Yes. Mirashka HRaaS is suitable for retail chains, D2C brands, e-commerce businesses, food businesses, fashion brands and growing consumer companies.',
            ],
            [
                'question' => 'Can Mirashka help with attendance and payroll coordination?',
                'answer' => 'Yes. Mirashka can support attendance inputs, shift data, overtime records, salary changes, reimbursements, deductions and payroll communication.',
            ],
            [
                'question' => 'Can Mirashka help reduce frontline attrition?',
                'answer' => 'Yes. Mirashka can support attrition review, employee feedback, onboarding improvement, manager communication systems and retention action planning.',
            ],
        ],
        'blogs' => [],
        'cta' => ['label' => 'Read Consumer & Retail HR Insights', 'href' => '/blog'],
        'image' => 'assets/frontend/img/industries/industry-form-consultant.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
    ],
];
