<?php

/**
 * Financial Services industry category page content.
 */
return [
    'meta' => [
        'title' => 'Financial Services HR Solutions | Banking, Insurance & Asset Management | Mirashka',
        'description' => 'Mirashka HR solutions for financial services — recruitment, leadership hiring, HRaaS, compliance support, payroll coordination and policy documentation for banking, insurance and asset management businesses.',
        'keywords' => 'financial services HR, banking recruitment, insurance hiring, asset management HR, compliance HR, Mirashka financial services',
    ],
    'hero' => [
        'label' => 'Financial Services HR Solutions',
        'heading' => 'People Systems for Trust-Driven Financial Businesses',
        'subheading' => ['Banking, insurance and asset management businesses operate in a world where people decisions directly affect trust, compliance, customer experience and business continuity.', 'Mirashka helps financial services companies build reliable people systems through recruitment, HRaaS, compliance support, payroll coordination, policy documentation, leadership hiring, employee engagement and workforce strategy.', 'Whether you are building a sales team, strengthening branch operations, hiring senior leaders, managing compliance documentation or setting up structured HR processes, Mirashka works as your extended HR partner.'],
        'ctas' => [
            [
                'label' => 'Book Financial Services HR Consultation',
                'href' => '#industry-form',
            ],
            [
                'label' => 'Request HR Health Check',
                'href' => '#industry-health-check',
            ],
        ],
        'image' => 'assets/frontend/img/Whatwedo/we-build-influence-banner.webp',
        'image_fallback' => 'assets/frontend/img/Whatwedo/we-build-influence-banner.webp',
    ],
    'reality' => [
        'section_name' => 'Financial Services HR Reality',
        'before_title' => 'The Financial Services Reality',
        'label' => 'The Financial Services Reality',
        'heading' => 'In financial services, HR is not only about hiring. It is about trust, risk and continuity.',
        'paragraphs' => ['Financial services organizations depend on people who can manage sensitive information, follow process discipline, communicate clearly, handle customer responsibility and work within compliance expectations.', 'A weak hiring process, poor documentation, unclear roles, high attrition or leadership gaps can directly affect customer trust, operational stability and regulatory confidence.', 'Mirashka understands that financial services HR needs both speed and caution. The right talent must be hired quickly, but with strong verification, role clarity, documentation and performance alignment.'],
        'challenges_heading' => 'Key Challenges',
        'pain_points' => ['Compliance-sensitive hiring', 'High attrition in sales and advisory roles', 'Need for trust and background verification', 'Documentation and policy discipline', 'Branch and field workforce management', 'Payroll and incentive complexity', 'Leadership hiring for growth roles', 'Employee engagement and retention', 'Role clarity and performance measurement', 'Customer-facing behavior standards'],
        'cta' => 'Discuss Financial Services HR Challenges',
        'cta_href' => '#industry-form',
        'section_bg' => 'assets/frontend/img/tab-sec-bg.jpg',
        'image' => 'assets/frontend/img/industries/healthcare-workforce-challenge.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-risk.png',
        'image_alt' => 'Financial services professionals and compliance process dashboard',
        'standout' => [
            'before_title' => 'The Financial Services Reality',
            'heading' => 'In financial services, HR is not only about hiring. It is about trust, risk and continuity.',
            'list_use_fontawesome' => true,
            'grid' => [
                'left_image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'left_image_fallback' => 'assets/frontend/img/compliance/cwi-card-training.png',
                'left_card' => [
                    'icon' => 'ri-bank-line',
                    'title' => 'Key Challenges',
                    'list' => ['Compliance-sensitive hiring', 'High attrition in sales and advisory roles', 'Need for trust and background verification', 'Documentation and policy discipline', 'Branch and field workforce management'],
                ],
                'center' => [
                    'icon' => 'ri-bank-line',
                    'title' => 'Why Financial Services Workforce Management Is Different',
                    'paragraphs' => ['Financial services organizations depend on people who can manage sensitive information, follow process discipline, communicate clearly, handle customer responsibility and work within compliance expectations.', 'A weak hiring process, poor documentation, unclear roles, high attrition or leadership gaps can directly affect customer trust, operational stability and regulatory confidence.', 'Mirashka understands that financial services HR needs both speed and caution. The right talent must be hired quickly, but with strong verification, role clarity, documentation and performance alignment.'],
                    'cta' => 'Discuss Financial Services HR Challenges',
                    'cta_url' => '#industry-form',
                ],
                'right_card' => [
                    'icon' => 'ri-shield-check-line',
                    'title' => 'Key Challenges',
                    'list' => ['Payroll and incentive complexity', 'Leadership hiring for growth roles', 'Employee engagement and retention', 'Role clarity and performance measurement', 'Customer-facing behavior standards'],
                ],
                'right_image' => 'assets/frontend/img/compliance/cwi-integrity.png',
                'right_image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
            ],
        ],
    ],
    'sub_industries' => [
        'label' => 'Financial Services Segments',
        'heading' => 'HR solutions for every major financial services business model',
        'content' => 'Financial services is not one industry. A bank, an insurance company and an asset management firm have different people needs, sales structures, compliance expectations and leadership requirements. Mirashka builds HR solutions accordingly.',
        'kicker' => 'Financial Services',
        'section_bg' => 'assets/frontend/img/tab-sec-bg.jpg',
        'cta' => 'Speak to a Financial Services HR Advisor',
        'cta_href' => '#industry-form',
        'cards' => [
            [
                'title' => 'Banking',
                'kicker' => 'Financial Services',
                'subcategories' => ['Branch managers', 'Relationship managers', 'Credit officers', 'Operations executives', 'Customer service teams', 'Sales teams', 'Compliance coordinators', 'Senior leadership roles'],
                'description' => 'For banks, NBFCs, fintech-enabled lenders and branch-led financial institutions, Mirashka supports hiring, payroll coordination, compliance documentation, branch workforce structuring, leadership hiring and employee engagement.',
                'cta' => 'Explore Banking HR Solutions',
                'route' => 'industries.financial-services.sub',
                'slug' => 'banking',
                'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-services.png',
            ],
            [
                'title' => 'Insurance',
                'kicker' => 'Financial Services',
                'subcategories' => ['Insurance sales managers', 'Advisors', 'Branch heads', 'Relationship officers', 'Operations teams', 'Claims support', 'Training managers', 'Regional leadership roles'],
                'description' => 'For life insurance, general insurance, health insurance, insurance brokers and distribution-led insurance businesses, Mirashka supports sales hiring, advisor onboarding, compliance documentation, incentive structures, employee engagement and leadership hiring.',
                'cta' => 'Explore Insurance HR Solutions',
                'href' => '#industry-subcategories',
                'anchor' => 'insurance',
                'image' => 'assets/frontend/img/hraas/hraas-hero-split.webp',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
            [
                'title' => 'Asset Management',
                'kicker' => 'Financial Services',
                'subcategories' => ['Relationship managers', 'Wealth advisors', 'Fund operations professionals', 'Compliance executives', 'Research analysts', 'Business development managers', 'Senior leadership roles'],
                'description' => 'For asset management companies, wealth advisory firms, PMS firms, investment platforms and financial advisory organizations, Mirashka supports specialist hiring, leadership recruitment, compliance-oriented HR systems, employee policies and retention strategy.',
                'cta' => 'Explore Asset Management HR Solutions',
                'href' => '#industry-subcategories',
                'anchor' => 'asset-management',
                'image' => 'assets/frontend/img/workforce/wfm-reporting-team-hands.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
            ],
        ],
    ],
    'pulse' => [
        'label' => 'PULSE for Financial Services',
        'heading' => 'A financial-services-ready people framework',
        'content' => 'Mirashka applies the PULSE Framework to financial services businesses by combining compliance awareness, structured HR operations, leadership strength, talent sourcing and employee empowerment.',
        'cards' => [
            [
                'letter' => 'P',
                'title' => 'Protect',
                'subtitle' => 'Compliance & Workplace Integrity',
                'text' => 'Protect financial services businesses through HR policies, documentation, employee handbooks, workplace ethics, POSH training and HR risk reviews.',
                'image' => 'assets/img/protect.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-card-policy.png',
            ],
            [
                'letter' => 'U',
                'title' => 'Unify',
                'subtitle' => 'Workforce Management',
                'text' => 'Unify payroll, attendance, incentives, employee records, onboarding, documentation and HR operations across branches, teams and locations.',
                'image' => 'assets/img/unify.png',
                'image_fallback' => 'assets/frontend/img/workforce/wfm-card-payroll.png',
            ],
            [
                'letter' => 'L',
                'title' => 'Lead',
                'subtitle' => 'Leadership & Organizational Excellence',
                'text' => 'Build leadership capability through executive search, board and CEO advisory, succession planning, leadership assessment and transformation support.',
                'image' => 'assets/img/lead.png',
                'image_fallback' => 'assets/frontend/img/leadership/ldr-board-advisory.png',
            ],
            [
                'letter' => 'S',
                'title' => 'Source',
                'subtitle' => 'Talent Acquisition & Staffing',
                'text' => 'Source reliable financial services talent for banking, insurance, wealth, operations, sales, compliance and leadership roles.',
                'image' => 'assets/img/source.png',
                'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-card-executive-search.png',
            ],
            [
                'letter' => 'E',
                'title' => 'Empower',
                'subtitle' => 'HR as a Service',
                'text' => 'Empower financial businesses with HR outsourcing, employer branding, employee engagement, retention strategies and HR technology.',
                'image' => 'assets/img/empower.png',
                'image_fallback' => 'assets/frontend/img/hraas/hraas-card-engagement.png',
            ],
        ],
        'cta' => [
            'label' => 'Apply PULSE to My Financial Services Business',
            'href' => '#industry-form',
        ],
    ],
    'services' => [
        'label' => 'What Mirashka Delivers',
        'heading' => 'Complete HR support for regulated, trust-led and performance-driven businesses',
        'image' => 'assets/frontend/img/home/home-why-mirashka-hero.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
        'image_secondary' => 'assets/frontend/img/compliance/cwi-services.png',
        'image_secondary_fallback' => 'assets/frontend/img/hraas/hraas-page-partner.png',
        'cards' => [
            [
                'title' => 'Financial Services Recruitment',
                'text' => 'Role mapping, sourcing, screening, interview coordination and closure support for sales, operations, compliance and management roles.',
                'icon' => 'ri-user-search-line',
            ],
            [
                'title' => 'Leadership Hiring',
                'text' => 'CXO, regional head, business head, branch leadership, sales leadership and strategic hiring support.',
                'icon' => 'ri-user-star-line',
            ],
            [
                'title' => 'HRaaS & HR Outsourcing',
                'text' => 'Dedicated HR support for companies that need professional HR management without a large internal HR team.',
                'icon' => 'ri-customer-service-2-line',
            ],
            [
                'title' => 'Policy Documentation',
                'text' => 'Employee handbooks, HR policies, appointment formats, exit documents, code of conduct and workplace guidelines.',
                'icon' => 'ri-file-list-3-line',
            ],
            [
                'title' => 'Payroll & Incentive Coordination',
                'text' => 'Salary inputs, incentive data coordination, attendance tracking, reimbursement support and structured payroll communication.',
                'icon' => 'ri-money-dollar-circle-line',
            ],
            [
                'title' => 'Compliance & Risk Assessment',
                'text' => 'HR audits, documentation checks, workplace risk reviews and corrective action planning.',
                'icon' => 'ri-shield-check-line',
            ],
            [
                'title' => 'Employee Engagement',
                'text' => 'Employee surveys, retention plans, performance communication, feedback systems and engagement programs.',
                'icon' => 'ri-emotion-happy-line',
            ],
            [
                'title' => 'HR Technology & Reporting',
                'text' => 'Dashboards for hiring pipeline, employee records, attrition, payroll status, compliance calendar and HR actions.',
                'icon' => 'ri-computer-line',
            ],
        ],
        'cta' => [
            'label' => 'Explore Financial Services HR Services',
            'href' => 'whatwedo',
        ],
    ],
    'hiring_strategy' => [
        'section_id' => 'industry-hiring-strategy',
        'label' => 'Talent Strategy',
        'heading' => 'Hire people who understand responsibility, process and customer trust',
        'intro' => ['Financial services hiring cannot be handled only through resume matching. Every role needs context — customer responsibility, product understanding, compliance sensitivity, documentation discipline, communication ability and long-term reliability.', 'Mirashka helps businesses define the role properly before sourcing. We map expectations, required skills, reporting relationships, performance metrics and cultural fit before starting the hiring process.'],
        'groups' => [
            [
                'title' => 'Hiring Support Includes',
                'items' => ['Job description and role clarity', 'Candidate sourcing strategy', 'Screening and shortlisting', 'Interview coordination', 'Culture and communication fit review', 'Salary and expectation alignment', 'Joining coordination', 'Replacement and continuity support', 'Hiring dashboard and weekly reporting'],
            ],
            [
                'title' => 'Roles Mirashka Can Support',
                'items' => ['Relationship Managers', 'Branch Managers', 'Insurance Sales Managers', 'Wealth Advisors', 'Credit Officers', 'Operations Executives', 'Compliance Executives', 'Customer Support Teams', 'Business Development Managers', 'Regional Sales Leaders', 'CXO and senior leadership roles'],
            ],
        ],
        'image' => 'assets/frontend/img/industries/healthcare-hiring-workforce-strategy.webp',
        'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
        'image_alt' => 'Financial services recruitment pipeline with candidate stages',
        'image_secondary' => 'assets/frontend/img/industries/healthcare-workforce-challenge.webp',
        'image_secondary_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
        'image_secondary_alt' => 'Financial services hiring and workforce strategy support',
        'cta' => [
            'label' => 'Start Financial Services Hiring Support',
            'href' => '#industry-form',
        ],
    ],
    'compliance' => [
        'label' => 'Compliance & Integrity',
        'heading' => 'Build documentation discipline before people issues become business risks',
        'intro' => ['In financial services, documentation, policy clarity and employee conduct standards are critical. Mirashka helps businesses build HR systems that reduce confusion, improve consistency and support workplace integrity.', 'Mirashka supports employee handbooks, HR policy frameworks, HR audits, POSH training and exit documentation for trust-led organizations.'],
        'image' => 'assets/frontend/img/industries/healthcare-compliance-documentation-hr-operations.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-card-policy.png',
        'image_alt' => 'Compliance checklist, employee handbook and financial office visual',
        'cta' => 'Request Compliance & Documentation Review',
        'cta_href' => '#industry-form',
        'cards' => [
            [
                'title' => 'Employee Handbooks',
                'text' => 'Clear employee policies, code of conduct, leave rules, escalation process and workplace expectations.',
                'icon' => 'ri-book-2-line',
                'image' => 'assets/frontend/img/compliance/cwi-card-policy.png',
            ],
            [
                'title' => 'HR Policy Frameworks',
                'text' => 'Policies aligned with business culture, role requirements, workplace discipline and compliance awareness.',
                'icon' => 'ri-file-list-3-line',
                'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'active' => true,
            ],
            [
                'title' => 'HR Audit & Risk Review',
                'text' => 'Review of employee records, documentation gaps, payroll coordination, exit process and workplace compliance readiness.',
                'icon' => 'ri-search-eye-line',
                'image' => 'assets/frontend/img/compliance/cwi-risk.png',
            ],
            [
                'title' => 'POSH & Workplace Ethics Training',
                'text' => 'Awareness programs to promote safe, respectful and legally aware workplaces.',
                'icon' => 'ri-group-2-line',
                'image' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
            [
                'title' => 'Exit & Disciplinary Documentation',
                'text' => 'Structured formats and processes for exits, warnings, disciplinary actions and handovers.',
                'icon' => 'ri-logout-box-r-line',
                'image' => 'assets/frontend/img/compliance/cwi-services.png',
                'active' => true,
            ],
        ],
    ],
    'use_cases' => [
        'label' => 'Relevant Use Cases',
        'heading' => 'Practical HR solutions for real financial services situations',
        'tags' => ['Faster Hiring', 'Cleaner Records', 'Stronger Leadership', 'Lower HR Risk'],
        'cards' => [
            [
                'tab_id' => 'rm-team',
                'tab_label' => 'RM Team',
                'title' => 'Case Study 1: Scaling a Relationship Manager Team',
                'pane_heading' => 'Role mapping, sourcing and interview coordination for customer-facing roles.',
                'challenge' => 'A growing financial services company needed faster hiring for customer-facing roles.',
                'approach' => 'Role mapping, candidate sourcing, screening process and interview coordination.',
                'outcome' => 'Better hiring clarity, faster shortlisting and stronger candidate fit.',
                'image' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
            ],
            [
                'tab_id' => 'branch-hr',
                'tab_label' => 'Branch HR',
                'title' => 'Case Study 2: Creating HR Structure for a Branch-Led Business',
                'pane_heading' => 'Documentation framework and employee lifecycle tracking.',
                'challenge' => 'Employee records, joining documents, attendance and payroll inputs were scattered.',
                'approach' => 'HR documentation framework, payroll coordination rhythm and employee lifecycle tracking.',
                'outcome' => 'Cleaner HR operations and better leadership visibility.',
                'image' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
                'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
            ],
            [
                'tab_id' => 'fs-leadership',
                'tab_label' => 'Leadership',
                'title' => 'Case Study 3: Leadership Hiring for Expansion',
                'pane_heading' => 'Leadership role definition, talent mapping and evaluation support.',
                'challenge' => 'The company needed a senior leader who could manage growth, teams and process discipline.',
                'approach' => 'Leadership role definition, talent mapping, evaluation and interview support.',
                'outcome' => 'Better leadership alignment and stronger growth readiness.',
                'image' => 'assets/frontend/img/workforce/wfm-hero.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-services.png',
            ],
            [
                'tab_id' => 'compliance-review',
                'tab_label' => 'Compliance',
                'title' => 'Case Study 4: Compliance Readiness Review',
                'pane_heading' => 'Policy review, employee handbook creation and HR audit.',
                'challenge' => 'HR documentation and workplace policies were not standardized.',
                'approach' => 'Policy review, employee handbook creation, HR audit and action plan.',
                'outcome' => 'Reduced HR risk and improved workplace clarity.',
                'image' => 'assets/frontend/img/compliance/cwi-card-policy.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
        ],
        'cta' => [
            'label' => 'Discuss a Similar Case',
            'href' => '#industry-form',
        ],
    ],
    'health_check' => [
        'label' => 'Start With Diagnosis',
        'heading' => 'How ready is your financial services HR system?',
        'content' => 'Mirashka\'s Financial Services HR Health Check helps banking, insurance and asset management businesses identify gaps across hiring, documentation, compliance, payroll, employee engagement, leadership and HR technology.',
        'covers' => ['Hiring process quality', 'Role clarity and KRAs', 'Employee documentation', 'Appointment and exit formats', 'Payroll and incentive coordination', 'Compliance exposure', 'Employee handbook readiness', 'POSH and ethics readiness', 'Attrition and retention risk', 'Leadership gap assessment', 'HR technology readiness', 'Reporting and dashboard maturity'],
        'output' => 'A practical HR improvement roadmap with risk areas, priority actions and recommended Mirashka service plan.',
        'cta' => [
            'label' => 'Request Financial Services HR Health Check',
            'href' => '#industry-form',
        ],
        'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
    ],
    'form' => [
        'label' => 'Talk to Mirashka',
        'heading' => 'Build a stronger people system for your financial services business',
        'content' => 'Share your financial services HR requirement. Mirashka will help identify whether you need recruitment, HRaaS, payroll coordination, compliance documentation, leadership hiring, employee engagement or a complete people operating model.',
        'lead_type' => 'financial_services_hr_enquiry',
        'segments' => ['Banking', 'Insurance', 'Asset Management', 'NBFC', 'Wealth Advisory', 'Fintech', 'Other Financial Services'],
        'services' => ['Recruitment / Staffing', 'Leadership Hiring', 'HRaaS / HR Outsourcing', 'Payroll Support', 'Compliance Audit', 'Policy Documentation', 'POSH / Workplace Training', 'Employee Engagement', 'HR Technology', 'Not Sure — Need Consultation'],
        'submit' => 'Submit Financial Services HR Enquiry',
        'secondary_cta' => [
            'label' => 'Book 30-Minute Consultation',
            'href' => 'https://calendly.com/elevateonemedia/30min',
        ],
        'image' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-page-partner.png',
    ],
    'faq_blog' => [
        'label' => 'Learn More',
        'heading' => 'Financial services HR questions answered',
        'faqs' => [
            [
                'question' => 'What financial services roles can Mirashka help hire for?',
                'answer' => 'Mirashka can support hiring for sales, relationship management, branch operations, customer support, compliance, HR, operations, wealth advisory and leadership roles.',
            ],
            [
                'question' => 'Can Mirashka support insurance sales hiring?',
                'answer' => 'Yes. Mirashka can support insurance sales teams, advisors, branch-level roles, regional sales roles and leadership hiring.',
            ],
            [
                'question' => 'Does Mirashka provide HRaaS for small financial firms?',
                'answer' => 'Yes. Mirashka HRaaS is suitable for small and growing financial services firms that need professional HR support without a large internal HR department.',
            ],
            [
                'question' => 'Can Mirashka help with employee documentation and policies?',
                'answer' => 'Yes. Mirashka supports employee handbooks, HR policies, appointment formats, exit documents, conduct guidelines and compliance documentation.',
            ],
            [
                'question' => 'Can Mirashka support leadership hiring in financial services?',
                'answer' => 'Yes. Mirashka supports senior leadership hiring, CXO search, business head hiring, regional leadership and succession planning.',
            ],
        ],
        'blogs' => [],
        'cta' => [
            'label' => 'Read Financial Services HR Insights',
            'href' => '/blog',
        ],
        'image' => 'assets/frontend/img/industries/industry-form-consultant.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
    ],
];
