<?php

/**
 * Healthcare industry category page content.
 */
return [
    'meta' => [
        'title' => 'Healthcare HR Solutions | Pharmaceuticals, Hospitals & Medical Devices | Mirashka',
        'description' => 'Mirashka HR solutions for healthcare — recruitment, HRaaS, payroll coordination, compliance documentation, leadership hiring and workforce management for pharma, hospitals and medical device businesses.',
        'keywords' => 'healthcare HR solutions, hospital staffing, pharma recruitment, medical device hiring, healthcare HRaaS, healthcare compliance HR, Mirashka healthcare',
    ],

    'hero' => [
        'label' => 'Healthcare HR Solutions',
        'heading' => 'People Systems for Care, Compliance and Healthcare Growth',
        'subheading' => [
            'Healthcare businesses depend on people who can combine skill, empathy, discipline, documentation and trust.',
            'Mirashka helps healthcare companies build structured HR systems through recruitment, HRaaS, payroll coordination, compliance documentation, employee engagement, leadership hiring, workforce planning and HR technology.',
            'Whether you operate a hospital, clinic, pharmaceutical company, medical device business or healthcare service organization, Mirashka works as your extended HR partner to help you hire, manage, engage and retain the right people.',
        ],
        'ctas' => [
            ['label' => 'Book Healthcare HR Consultation', 'href' => '#industry-form'],
            ['label' => 'Request Healthcare HR Health Check', 'href' => '#industry-health-check'],
        ],
        'image' => 'assets/frontend/img/Whatwedo/we-build-influence-banner.webp',
        'image_fallback' => 'assets/frontend/img/Whatwedo/we-build-influence-banner.webp',
    ],

    'reality' => [
        'section_name' => 'Healthcare HR Reality',
        'before_title' => 'The Healthcare Workforce Challenge',
        'label' => 'The Healthcare Workforce Challenge',
        'heading' => 'In healthcare, people quality directly affects trust, care and continuity',
        'paragraphs' => [
            'Healthcare is one of the most sensitive sectors for workforce management. Every role, from doctor and nurse to medical sales executive, pharmacist, technician, hospital administrator and compliance professional, carries responsibility.',
            'A weak hiring process, incomplete documentation, high attrition, poor onboarding or unclear role expectations can affect patient experience, operational efficiency, regulatory confidence and brand reputation.',
            'Mirashka understands that healthcare HR needs both speed and responsibility. The right people must be hired, trained, documented and retained with care.',
        ],
        'challenges_heading' => 'Key Challenges',
        'pain_points' => [
            'Shortage of skilled healthcare talent',
            'High attrition in frontline and field roles',
            'Compliance-sensitive documentation',
            'Shift-based workforce complexity',
            'Payroll and attendance challenges',
            'Need for background and qualification verification',
            'Leadership gaps in hospitals and healthcare companies',
            'Weak onboarding and training discipline',
            'Employee burnout and retention issues',
            'Lack of structured HR technology and reporting',
        ],
        'cta' => 'Discuss Healthcare Workforce Challenges',
        'cta_href' => '#industry-form',
        'section_bg' => 'assets/frontend/img/tab-sec-bg.jpg',
        'image' => 'assets/frontend/img/industries/healthcare-workforce-challenge.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-risk.png',
        'image_alt' => 'Hospital workforce and HR compliance dashboard for healthcare organizations',
        'standout' => [
            'before_title' => 'The Healthcare Workforce Challenge',
            'heading' => 'In healthcare, people quality directly affects trust, care and continuity',
            'list_use_fontawesome' => true,
            'grid' => [
                'left_image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'left_image_fallback' => 'assets/frontend/img/compliance/cwi-card-training.png',
                'left_card' => [
                    'icon' => 'ri-hospital-line',
                    'title' => 'Key Challenges',
                    'list' => [
                        'Shortage of skilled healthcare talent',
                        'High attrition in frontline and field roles',
                        'Compliance-sensitive documentation',
                        'Shift-based workforce complexity',
                        'Payroll and attendance challenges',
                    ],
                ],
                'center' => [
                    'icon' => 'ri-heart-pulse-line',
                    'title' => 'Why Healthcare Workforce Management Is Different',
                    'paragraphs' => [
                        'Healthcare is one of the most sensitive sectors for workforce management. Every role, from doctor and nurse to medical sales executive, pharmacist, technician, hospital administrator and compliance professional, carries responsibility.',
                        'A weak hiring process, incomplete documentation, high attrition, poor onboarding or unclear role expectations can affect patient experience, operational efficiency, regulatory confidence and brand reputation.',
                        'Mirashka understands that healthcare HR needs both speed and responsibility. The right people must be hired, trained, documented and retained with care.',
                    ],
                    'cta' => 'Discuss Healthcare Workforce Challenges',
                    'cta_url' => '#industry-form',
                ],
                'right_card' => [
                    'icon' => 'ri-shield-check-line',
                    'title' => 'Key Challenges',
                    'list' => [
                        'Need for background and qualification verification',
                        'Leadership gaps in hospitals and healthcare companies',
                        'Weak onboarding and training discipline',
                        'Employee burnout and retention issues',
                        'Lack of structured HR technology and reporting',
                    ],
                ],
                'right_image' => 'assets/frontend/img/compliance/cwi-integrity.png',
                'right_image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
            ],
        ],
    ],

    'sub_industries' => [
        'label' => 'Healthcare Segments',
        'heading' => 'HR solutions for every major healthcare business model',
        'content' => 'Healthcare is not one single workforce model. A hospital, a pharmaceutical company and a medical device business need very different hiring, compliance, payroll and leadership systems. Mirashka builds healthcare HR solutions according to the business model.',
        'kicker' => 'Healthcare',
        'section_bg' => 'assets/frontend/img/tab-sec-bg.jpg',
        'cta' => 'Speak to a Healthcare HR Advisor',
        'cta_href' => '#industry-form',
        'cards' => [
            [
                'title' => 'Pharmaceuticals',
                'kicker' => 'Healthcare',
                'subcategories' => [
                    'Medical representatives',
                    'Area sales managers',
                    'Regional managers',
                    'Product managers',
                    'Quality executives',
                    'Regulatory support',
                    'Production staff',
                    'Operations teams',
                    'Senior leadership roles',
                ],
                'description' => 'For pharmaceutical companies, pharma distributors, formulation businesses and healthcare product companies, Mirashka supports sales hiring, medical representative recruitment, compliance documentation, payroll coordination, employee engagement and leadership hiring.',
                'cta' => 'Explore Pharmaceutical HR Solutions',
                'href' => '#pharmaceuticals',
                'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-services.png',
            ],
            [
                'title' => 'Hospitals & Clinics',
                'kicker' => 'Healthcare',
                'subcategories' => [
                    'Doctors',
                    'Nurses',
                    'Technicians',
                    'Front-office teams',
                    'Patient care coordinators',
                    'Hospital administrators',
                    'Billing executives',
                    'Operations managers',
                    'HR teams',
                    'Leadership roles',
                ],
                'description' => 'For hospitals, clinics, diagnostic centres, wellness centres and specialty healthcare units, Mirashka supports clinical hiring, non-clinical staffing, payroll coordination, shift workforce management, documentation and HRaaS.',
                'cta' => 'Explore Hospitals & Clinics HR Solutions',
                'href' => '#hospitals-clinics',
                'image' => 'assets/frontend/img/hraas/hraas-hero-split.webp',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
            [
                'title' => 'Medical Devices',
                'kicker' => 'Healthcare',
                'subcategories' => [
                    'Biomedical engineers',
                    'Sales executives',
                    'Service engineers',
                    'Product specialists',
                    'Application specialists',
                    'Regulatory executives',
                    'Operations teams',
                    'Business leaders',
                ],
                'description' => 'For medical device manufacturers, distributors, equipment companies and healthcare technology businesses, Mirashka supports technical hiring, sales hiring, service teams, compliance documentation, training coordination and leadership hiring.',
                'cta' => 'Explore Medical Devices HR Solutions',
                'href' => '#medical-devices',
                'image' => 'assets/frontend/img/workforce/wfm-reporting-team-hands.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
            ],
        ],
    ],

    'pulse' => [
        'label' => 'PULSE for Healthcare',
        'heading' => 'A healthcare-ready people framework for trust, skill and continuity',
        'content' => 'Mirashka applies its PULSE Framework to healthcare businesses by connecting compliance awareness, structured HR operations, leadership hiring, talent sourcing and HRaaS into one reliable people system.',
        'cards' => [
            [
                'letter' => 'P',
                'title' => 'Protect',
                'subtitle' => 'Compliance & Workplace Integrity',
                'text' => 'Protect healthcare organizations through employee documentation, workplace policies, qualification records, conduct guidelines, HR audits, POSH readiness and ethics training.',
                'image' => 'assets/img/protect.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-card-policy.png',
            ],
            [
                'letter' => 'U',
                'title' => 'Unify',
                'subtitle' => 'Workforce Management',
                'text' => 'Unify payroll, attendance, shift records, employee files, onboarding, exits, documentation and remote HR operations.',
                'image' => 'assets/img/unify.png',
                'image_fallback' => 'assets/frontend/img/workforce/wfm-card-payroll.png',
            ],
            [
                'letter' => 'L',
                'title' => 'Lead',
                'subtitle' => 'Leadership & Organizational Excellence',
                'text' => 'Build leadership capability through hospital leadership hiring, pharma sales leadership, business heads, operations leaders, succession planning and transformation support.',
                'image' => 'assets/img/lead.png',
                'image_fallback' => 'assets/frontend/img/leadership/ldr-board-advisory.png',
            ],
            [
                'letter' => 'S',
                'title' => 'Source',
                'subtitle' => 'Talent Acquisition & Staffing',
                'text' => 'Source healthcare talent across clinical, non-clinical, sales, technical, operational and leadership roles.',
                'image' => 'assets/img/source.png',
                'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-card-executive-search.png',
            ],
            [
                'letter' => 'E',
                'title' => 'Empower',
                'subtitle' => 'HR as a Service',
                'text' => 'Empower healthcare businesses with HR outsourcing, employer branding, employee engagement, retention strategies and HR technology.',
                'image' => 'assets/img/empower.png',
                'image_fallback' => 'assets/frontend/img/hraas/hraas-card-engagement.png',
            ],
        ],
        'cta' => ['label' => 'Apply PULSE to My Healthcare Business', 'href' => '#industry-form'],
    ],

    'services' => [
        'label' => 'What Mirashka Delivers',
        'heading' => 'Complete HR support for healthcare organizations that need reliability and discipline',
        'image' => 'assets/frontend/img/home/home-why-mirashka-hero.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
        'image_secondary' => 'assets/frontend/img/compliance/cwi-services.png',
        'image_secondary_fallback' => 'assets/frontend/img/hraas/hraas-page-partner.png',
        'cards' => [
            ['title' => 'Healthcare Recruitment', 'text' => 'Hiring support for clinical, non-clinical, sales, operations, technical and administrative roles.', 'icon' => 'ri-user-search-line'],
            ['title' => 'Pharmaceutical Sales Hiring', 'text' => 'Structured hiring for medical representatives, area managers, regional managers and pharma business teams.', 'icon' => 'ri-medicine-bottle-line'],
            ['title' => 'Hospital & Clinic Staffing', 'text' => 'Support for doctors, nurses, technicians, front office, patient care, billing, administration and operations roles.', 'icon' => 'ri-hospital-line'],
            ['title' => 'Medical Device Talent Hiring', 'text' => 'Hiring support for biomedical engineers, sales teams, product specialists, service engineers and technical support roles.', 'icon' => 'ri-stethoscope-line'],
            ['title' => 'Leadership Hiring', 'text' => 'Hiring support for hospital administrators, business heads, sales heads, operations heads, regional leaders and CXO roles.', 'icon' => 'ri-user-star-line'],
            ['title' => 'HRaaS & HR Outsourcing', 'text' => 'Dedicated HR support for healthcare companies that need professional HR execution without building a large internal HR team.', 'icon' => 'ri-customer-service-2-line'],
            ['title' => 'Compliance & Documentation', 'text' => 'Employee records, appointment letters, policies, training records, qualification documents, HR audits and workplace conduct guidelines.', 'icon' => 'ri-shield-check-line'],
            ['title' => 'Payroll & Workforce Administration', 'text' => 'Payroll input coordination, attendance data, shift records, reimbursement tracking and employee lifecycle documentation.', 'icon' => 'ri-money-dollar-circle-line'],
            ['title' => 'Employee Engagement & Retention', 'text' => 'Employee feedback, retention planning, performance communication, burnout risk review and engagement programs.', 'icon' => 'ri-emotion-happy-line'],
            ['title' => 'HR Technology & Reporting', 'text' => 'Dashboards for hiring, attendance, payroll, employee records, compliance calendar, attrition and HR actions.', 'icon' => 'ri-computer-line'],
        ],
        'cta' => ['label' => 'Explore Healthcare HR Services', 'href' => 'whatwedo'],
    ],

    'hiring_strategy' => [
        'section_id' => 'industry-hiring-strategy',
        'label' => 'Talent Strategy',
        'heading' => 'Healthcare hiring needs skill-fit, empathy-fit and responsibility-fit',
        'intro' => [
            'Healthcare hiring cannot be treated like generic recruitment. A clinical role needs qualification and patient sensitivity. A hospital front-office role needs empathy and communication. A pharma sales role needs scientific understanding and persistence. A medical device role needs product knowledge and technical credibility.',
            'Mirashka helps healthcare businesses define the role before sourcing. We map qualification requirements, experience level, patient or customer interaction, reporting structure, shift expectations, salary range, location needs and performance expectations.',
        ],
        'groups' => [
            [
                'title' => 'Hiring Strategy Includes',
                'items' => [
                    'Role and KRA definition',
                    'Qualification and experience mapping',
                    'Location-wise hiring plan',
                    'Candidate sourcing strategy',
                    'Screening and shortlisting',
                    'Background and document coordination support',
                    'Interview scheduling',
                    'Salary and expectation alignment',
                    'Joining coordination',
                    'Weekly hiring dashboard',
                ],
            ],
            [
                'title' => 'Workforce Strategy Includes',
                'items' => [
                    'Shift planning support',
                    'Attendance and payroll input discipline',
                    'Employee lifecycle documentation',
                    'Training and onboarding support',
                    'Retention and engagement planning',
                    'HR reporting structure',
                    'Leadership and succession planning',
                    'Role clarity and performance communication',
                ],
            ],
        ],
        'image' => 'assets/frontend/img/industries/healthcare-hiring-workforce-strategy.webp',
        'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
        'image_alt' => 'Healthcare hiring funnel with filters: Skill Fit, Empathy Fit, Compliance Fit, Shift Fit and Culture Fit',
        'image_secondary' => 'assets/frontend/img/industries/healthcare-workforce-challenge.webp',
        'image_secondary_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
        'image_secondary_alt' => 'Healthcare workforce planning and structured hiring support',
        'cta' => [
            'label' => 'Build My Healthcare Talent Pipeline',
            'href' => '#industry-form',
        ],
    ],

    'compliance' => [
        'label' => 'Compliance & HR Operations',
        'heading' => 'Build documentation discipline across every healthcare employee touchpoint',
        'intro' => [
            'Healthcare organizations need strong employee records, qualification documents, training records, attendance systems, appointment letters, code of conduct, workplace policies and exit documentation.',
            'Mirashka helps healthcare businesses create structured HR operations that reduce confusion, improve accountability and support leadership visibility.',
        ],
        'image' => 'assets/frontend/img/industries/healthcare-compliance-documentation-hr-operations.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-card-policy.png',
        'image_alt' => 'Healthcare employee records, policy handbook, training checklist and compliance shield visual',
        'cta' => 'Request Healthcare HR Documentation Review',
        'cta_href' => '#industry-form',
        'cards' => [
            [
                'title' => 'Employee Documentation',
                'text' => 'Appointment letters, joining forms, ID proofs, qualification certificates, experience records, training records and employee files.',
                'icon' => 'ri-file-list-3-line',
                'image' => 'assets/frontend/img/compliance/cwi-card-policy.png',
            ],
            [
                'title' => 'Policy Framework',
                'text' => 'Leave policy, attendance policy, shift policy, code of conduct, workplace behavior guidelines, escalation process and patient interaction standards.',
                'icon' => 'ri-book-2-line',
                'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'active' => true,
            ],
            [
                'title' => 'HR Audit & Risk Review',
                'text' => 'Review of documentation gaps, employee records, payroll inputs, exit process, workplace conduct and HR compliance readiness.',
                'icon' => 'ri-search-eye-line',
                'image' => 'assets/frontend/img/compliance/cwi-risk.png',
            ],
            [
                'title' => 'Payroll & Attendance Coordination',
                'text' => 'Attendance inputs, shift records, salary changes, reimbursement data, incentive records and payroll communication.',
                'icon' => 'ri-money-dollar-circle-line',
                'image' => 'assets/frontend/img/workforce/wfm-card-payroll.png',
                'active' => true,
            ],
            [
                'title' => 'POSH & Workplace Ethics',
                'text' => 'Awareness programs to promote safe, respectful and legally aware workplaces.',
                'icon' => 'ri-group-2-line',
                'image' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
            [
                'title' => 'Exit Management',
                'text' => 'Resignation documentation, handover process, clearance checklist, full and final coordination and exit feedback.',
                'icon' => 'ri-logout-box-r-line',
                'image' => 'assets/frontend/img/compliance/cwi-services.png',
                'active' => true,
            ],
        ],
    ],

    'use_cases' => [
        'label' => 'Healthcare HR Support in Action',
        'heading' => 'Practical people solutions for healthcare workforce challenges',
        'tags' => ['Faster Hiring', 'Cleaner Documentation', 'Stronger Workforce', 'Better Compliance'],
        'cards' => [
            [
                'tab_id' => 'hospital-staffing',
                'tab_label' => 'Hospital Staffing',
                'title' => 'Case Study 1: Hospital Staffing Structuring',
                'pane_heading' => 'Structured hiring for front office, nursing, technicians and patient coordination roles.',
                'challenge' => 'A growing hospital needed structured hiring for front office, nursing, technicians and patient coordination roles.',
                'approach' => 'Created role clarity, hiring priority map, screening process and onboarding checklist.',
                'outcome' => 'Faster role closure, clearer employee documentation and smoother onboarding.',
                'image' => 'assets/frontend/img/industries/healthcare-hiring-workforce-strategy.webp',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
            ],
            [
                'tab_id' => 'pharma-sales',
                'tab_label' => 'Pharma Sales',
                'title' => 'Case Study 2: Pharma Sales Team Hiring',
                'pane_heading' => 'Territory-wise hiring for medical representatives and area sales managers.',
                'challenge' => 'A pharmaceutical business needed medical representatives and area sales managers across multiple locations.',
                'approach' => 'Mapped territory-wise hiring needs, created sourcing plan, screened candidates and coordinated interviews.',
                'outcome' => 'Better candidate relevance, improved hiring visibility and stronger sales team readiness.',
                'image' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
                'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
            ],
            [
                'tab_id' => 'medical-device',
                'tab_label' => 'Medical Device',
                'title' => 'Case Study 3: Medical Device Service Team Hiring',
                'pane_heading' => 'Technical hiring for service engineers and product support professionals.',
                'challenge' => 'A medical device company needed technically capable service engineers and product support professionals.',
                'approach' => 'Defined technical role requirements, screened for product understanding and coordinated hiring.',
                'outcome' => 'Improved technical fit and faster hiring for customer-support-critical roles.',
                'image' => 'assets/frontend/img/workforce/wfm-hero.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-services.png',
            ],
            [
                'tab_id' => 'documentation-review',
                'tab_label' => 'Documentation',
                'title' => 'Case Study 4: Healthcare HR Documentation Review',
                'pane_heading' => 'Documentation discipline across employee records, policies and HR audits.',
                'challenge' => 'A healthcare company had scattered employee files, incomplete joining documents and unclear policies.',
                'approach' => 'Created documentation checklist, employee record structure, policy framework and HR audit report.',
                'outcome' => 'Cleaner documentation, stronger HR control and improved compliance readiness.',
                'image' => 'assets/frontend/img/compliance/cwi-card-policy.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
        ],
        'cta' => ['label' => 'Discuss a Similar Healthcare Case', 'href' => '#industry-form'],
    ],

    'health_check' => [
        'label' => 'Start With Diagnosis',
        'heading' => 'How ready is your healthcare HR system?',
        'content' => 'Mirashka’s Healthcare HR Health Check helps hospitals, clinics, pharma companies, medical device businesses and healthcare service organizations identify gaps in hiring, documentation, payroll, compliance, employee engagement, leadership and HR technology.',
        'covers' => [
            'Hiring process quality',
            'Role clarity and KRAs',
            'Qualification documentation',
            'Employee records',
            'Appointment and exit formats',
            'Payroll and attendance process',
            'Shift workforce management',
            'Compliance exposure',
            'Employee handbook readiness',
            'POSH and ethics readiness',
            'Attrition and retention risk',
            'Leadership gap assessment',
            'HR technology readiness',
            'Reporting and dashboard maturity',
        ],
        'output' => 'A practical HR improvement roadmap with risk areas, priority actions and recommended Mirashka service plan.',
        'cta' => ['label' => 'Request Healthcare HR Health Check', 'href' => '#industry-form'],
        'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
    ],

    'form' => [
        'label' => 'Talk to Mirashka',
        'heading' => 'Build a stronger healthcare workforce with Mirashka',
        'content' => 'Share your healthcare HR requirement. Mirashka will help identify whether you need recruitment, HRaaS, payroll coordination, compliance documentation, leadership hiring, employee engagement or a complete people operating model.',
        'lead_type' => 'healthcare_hr_enquiry',
        'segments' => [
            'Pharmaceuticals',
            'Hospitals & Clinics',
            'Medical Devices',
            'Diagnostics',
            'Wellness Centre',
            'Healthcare Services',
            'Other Healthcare Business',
        ],
        'services' => [
            'Recruitment / Staffing',
            'Leadership Hiring',
            'HRaaS / HR Outsourcing',
            'Payroll Support',
            'Compliance Audit',
            'Policy Documentation',
            'POSH / Workplace Training',
            'Employee Engagement',
            'HR Technology',
            'Not Sure — Need Consultation',
        ],
        'submit' => 'Submit Healthcare HR Enquiry',
        'secondary_cta' => ['label' => 'Book 30-Minute Healthcare HR Consultation', 'href' => 'https://calendly.com/elevateonemedia/30min'],
        'image' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-page-partner.png',
    ],

    'faq_blog' => [
        'label' => 'Learn More',
        'heading' => 'Healthcare HR questions answered',
        'faqs' => [
            [
                'question' => 'What healthcare roles can Mirashka help hire for?',
                'answer' => 'Mirashka can support hiring for clinical, non-clinical, pharma sales, medical device, technical, operations, administrative and leadership roles.',
            ],
            [
                'question' => 'Can Mirashka support hospital and clinic staffing?',
                'answer' => 'Yes. Mirashka can support hiring for doctors, nurses, technicians, front-office teams, patient care coordinators, billing executives, administrators and operations roles.',
            ],
            [
                'question' => 'Can Mirashka hire for pharmaceutical sales teams?',
                'answer' => 'Yes. Mirashka can support medical representative hiring, area sales manager hiring, regional sales roles, product roles and pharma leadership hiring.',
            ],
            [
                'question' => 'Does Mirashka provide HRaaS for healthcare businesses?',
                'answer' => 'Yes. Mirashka HRaaS is suitable for hospitals, clinics, diagnostic centres, pharma companies, medical device businesses and healthcare service firms.',
            ],
            [
                'question' => 'Can Mirashka help with employee documentation and HR audits?',
                'answer' => 'Yes. Mirashka supports employee records, appointment formats, qualification documentation, HR policy frameworks, compliance audits and workplace ethics training.',
            ],
        ],
        'blogs' => [],
        'cta' => ['label' => 'Read Healthcare HR Insights', 'href' => '/blog'],
        'image' => 'assets/frontend/img/industries/industry-form-consultant.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
    ],
];
