<?php

/**
 * Industrial & Energy industry category page content.
 */
return [
    'meta' => [
        'title' => 'Industrial & Energy HR Solutions | Manufacturing, Oil & Gas & Renewable | Mirashka',
        'description' => 'Mirashka HR solutions for industrial and energy — technical manpower hiring, plant staffing, safety role recruitment, HRaaS, payroll coordination and leadership hiring for manufacturing, oil & gas and renewable energy businesses.',
        'keywords' => 'industrial HR solutions, manufacturing staffing, oil gas workforce, renewable energy hiring, plant manpower, Mirashka industrial energy',
    ],
    'hero' => [
        'label' => 'Industrial & Energy HR Solutions',
        'heading' => 'People Systems for Operations, Safety and Industrial Growth',
        'subheading' => ['Industrial and energy businesses need people who can work with discipline, technical skill, safety awareness and operational responsibility.', 'Mirashka helps manufacturing companies, oil and gas businesses, renewable energy companies, industrial service providers and plant-led organizations build structured HR systems through manpower hiring, technical staffing, payroll coordination, compliance documentation, HRaaS, employee engagement, workforce planning and leadership hiring.', 'Whether you need plant workers, engineers, supervisors, safety officers, operators, field technicians, project teams, maintenance staff, production leaders or business heads, Mirashka helps you build a reliable people system for industrial scale.'],
        'ctas' => [
            [
                'label' => 'Book Industrial HR Consultation',
                'href' => '#industry-form',
            ],
            [
                'label' => 'Request Industrial HR Health Check',
                'href' => '#industry-health-check',
            ],
        ],
        'image' => 'assets/frontend/img/Whatwedo/we-build-influence-banner.webp',
        'image_fallback' => 'assets/frontend/img/Whatwedo/we-build-influence-banner.webp',
    ],
    'reality' => [
        'section_name' => 'Industrial & Energy HR Reality',
        'before_title' => 'The Industrial Workforce Challenge',
        'label' => 'The Industrial Workforce Challenge',
        'heading' => 'In industrial businesses, workforce gaps directly affect production, safety and delivery',
        'paragraphs' => ['Industrial and energy businesses operate in environments where people discipline matters every hour. A missing operator, untrained technician, weak supervisor, delayed engineer or incomplete safety documentation can affect production schedules, plant efficiency, compliance readiness and worker safety.', 'These businesses need people who are skilled, punctual, safety-conscious, process-oriented and capable of working in demanding operational environments.', 'Mirashka understands that industrial HR is not only about hiring manpower. It is about building a structured workforce system that supports productivity, compliance, safety and continuity.'],
        'challenges_heading' => 'Key Challenges',
        'pain_points' => ['Shortage of skilled technical manpower', 'Plant and site workforce coordination', 'Shift-based attendance and payroll complexity', 'Safety and compliance documentation gaps', 'High dependency on supervisors and operators', 'Contract and permanent workforce management', 'Field technician and project manpower pressure', 'High attrition in operational roles', 'Leadership gaps in production, operations and projects', 'Weak HR reporting across plants, sites and locations'],
        'cta' => 'Discuss Industrial Workforce Challenges',
        'cta_href' => '#industry-form',
        'section_bg' => 'assets/frontend/img/tab-sec-bg.jpg',
        'image' => 'assets/frontend/img/industries/healthcare-workforce-challenge.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-risk.png',
        'image_alt' => 'Manufacturing plant operations and industrial workforce HR dashboard',
        'standout' => [
            'before_title' => 'The Industrial Workforce Challenge',
            'heading' => 'In industrial businesses, workforce gaps directly affect production, safety and delivery',
            'list_use_fontawesome' => true,
            'grid' => [
                'left_image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'left_image_fallback' => 'assets/frontend/img/compliance/cwi-card-training.png',
                'left_card' => [
                    'icon' => 'ri-building-2-line',
                    'title' => 'Key Challenges',
                    'list' => ['Shortage of skilled technical manpower', 'Plant and site workforce coordination', 'Shift-based attendance and payroll complexity', 'Safety and compliance documentation gaps', 'High dependency on supervisors and operators'],
                ],
                'center' => [
                    'icon' => 'ri-building-2-line',
                    'title' => 'Why Industrial Workforce Management Is Different',
                    'paragraphs' => ['Industrial and energy businesses operate in environments where people discipline matters every hour. A missing operator, untrained technician, weak supervisor, delayed engineer or incomplete safety documentation can affect production schedules, plant efficiency, compliance readiness and worker safety.', 'These businesses need people who are skilled, punctual, safety-conscious, process-oriented and capable of working in demanding operational environments.', 'Mirashka understands that industrial HR is not only about hiring manpower. It is about building a structured workforce system that supports productivity, compliance, safety and continuity.'],
                    'cta' => 'Discuss Industrial Workforce Challenges',
                    'cta_url' => '#industry-form',
                ],
                'right_card' => [
                    'icon' => 'ri-shield-check-line',
                    'title' => 'Key Challenges',
                    'list' => ['Contract and permanent workforce management', 'Field technician and project manpower pressure', 'High attrition in operational roles', 'Leadership gaps in production, operations and projects', 'Weak HR reporting across plants, sites and locations'],
                ],
                'right_image' => 'assets/frontend/img/compliance/cwi-integrity.png',
                'right_image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
            ],
        ],
    ],
    'sub_industries' => [
        'label' => 'Industrial & Energy Segments',
        'heading' => 'HR solutions for operations-heavy and safety-sensitive industries',
        'content' => 'Manufacturing, oil and gas, and renewable energy businesses have very different workforce models. A factory floor, an oilfield project and a solar energy site need different hiring, safety, payroll, attendance and leadership systems. Mirashka builds HR solutions according to operating realities.',
        'kicker' => 'Industrial & Energy',
        'section_bg' => 'assets/frontend/img/tab-sec-bg.jpg',
        'cta' => 'Speak to an Industrial HR Advisor',
        'cta_href' => '#industry-form',
        'cards' => [
            [
                'title' => 'Manufacturing',
                'kicker' => 'Industrial & Energy',
                'subcategories' => ['Production operators', 'Machine operators', 'Quality executives', 'Maintenance technicians', 'Supervisors', 'Plant HR', 'Store executives', 'Purchase teams', 'Production managers', 'Plant heads', 'Operations leaders'],
                'description' => 'For manufacturing units, factories, industrial product companies, automotive component manufacturers, packaging units, engineering companies and production-led businesses, Mirashka supports plant manpower hiring, technical recruitment, supervisor hiring, payroll coordination, HRaaS, compliance documentation and leadership hiring.',
                'cta' => 'Explore Manufacturing HR Solutions',
                'href' => '#manufacturing',
                'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-services.png',
            ],
            [
                'title' => 'Oil & Gas',
                'kicker' => 'Industrial & Energy',
                'subcategories' => ['Field technicians', 'Safety officers', 'Project engineers', 'Site supervisors', 'Maintenance teams', 'Logistics coordinators', 'Operations staff', 'Project managers', 'HSE professionals', 'Senior leaders'],
                'description' => 'For oil and gas companies, energy contractors, field service providers, EPC businesses, equipment suppliers and project-based energy operations, Mirashka supports technical manpower hiring, safety role hiring, site workforce planning, payroll coordination, documentation and leadership hiring.',
                'cta' => 'Explore Oil & Gas HR Solutions',
                'href' => '#oil-gas',
                'image' => 'assets/frontend/img/hraas/hraas-hero-split.webp',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
            [
                'title' => 'Renewable Energy',
                'kicker' => 'Industrial & Energy',
                'subcategories' => ['Solar technicians', 'Project engineers', 'Installation teams', 'Site supervisors', 'O&M teams', 'Sales executives', 'Energy consultants', 'Safety officers', 'Project managers', 'Business leaders'],
                'description' => 'For solar, wind, bioenergy, EV infrastructure, energy storage and green technology businesses, Mirashka supports project manpower hiring, technical staffing, sales hiring, field service teams, HRaaS, compliance documentation and leadership search.',
                'cta' => 'Explore Renewable Energy HR Solutions',
                'href' => '#renewable-energy',
                'image' => 'assets/frontend/img/workforce/wfm-reporting-team-hands.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
            ],
        ],
    ],
    'pulse' => [
        'label' => 'PULSE for Industrial & Energy',
        'heading' => 'A workforce framework for safety, productivity and operational scale',
        'content' => 'Mirashka applies its PULSE Framework to industrial and energy businesses by connecting compliance discipline, workforce management, leadership hiring, manpower sourcing and HRaaS into one structured people system.',
        'cards' => [
            [
                'letter' => 'P',
                'title' => 'Protect',
                'subtitle' => 'Compliance & Workplace Integrity',
                'text' => 'Protect industrial businesses through employee documentation, safety records, workplace policies, HR audits, POSH readiness, conduct guidelines and compliance documentation.',
                'image' => 'assets/img/protect.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-card-policy.png',
            ],
            [
                'letter' => 'U',
                'title' => 'Unify',
                'subtitle' => 'Workforce Management',
                'text' => 'Unify attendance, shift records, payroll inputs, employee files, onboarding, exits, contractor records, site manpower and HR reporting.',
                'image' => 'assets/img/unify.png',
                'image_fallback' => 'assets/frontend/img/workforce/wfm-card-payroll.png',
            ],
            [
                'letter' => 'L',
                'title' => 'Lead',
                'subtitle' => 'Leadership & Organizational Excellence',
                'text' => 'Build leadership capability through plant heads, operations heads, project heads, production leaders, safety leaders and business heads.',
                'image' => 'assets/img/lead.png',
                'image_fallback' => 'assets/frontend/img/leadership/ldr-board-advisory.png',
            ],
            [
                'letter' => 'S',
                'title' => 'Source',
                'subtitle' => 'Talent Acquisition & Staffing',
                'text' => 'Source technical, operational, field, plant, project, safety, maintenance, sales and leadership talent.',
                'image' => 'assets/img/source.png',
                'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-card-executive-search.png',
            ],
            [
                'letter' => 'E',
                'title' => 'Empower',
                'subtitle' => 'HR as a Service',
                'text' => 'Empower industrial businesses with HR outsourcing, employee engagement, retention systems, workforce reporting and HR technology.',
                'image' => 'assets/img/empower.png',
                'image_fallback' => 'assets/frontend/img/hraas/hraas-card-engagement.png',
            ],
        ],
        'cta' => [
            'label' => 'Apply PULSE to My Industrial Business',
            'href' => '#industry-form',
        ],
    ],
    'services' => [
        'label' => 'What Mirashka Delivers',
        'heading' => 'Complete HR support for businesses that need skilled manpower and workforce control',
        'image' => 'assets/frontend/img/home/home-why-mirashka-hero.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
        'image_secondary' => 'assets/frontend/img/compliance/cwi-services.png',
        'image_secondary_fallback' => 'assets/frontend/img/hraas/hraas-page-partner.png',
        'cards' => [
            [
                'title' => 'Technical Manpower Hiring',
                'text' => 'Hiring support for technicians, operators, engineers, maintenance staff, quality teams and production professionals.',
                'icon' => 'ri-tools-line',
            ],
            [
                'title' => 'Plant & Site Staffing',
                'text' => 'Support for plant workers, site teams, supervisors, store teams, project manpower and field service professionals.',
                'icon' => 'ri-building-2-line',
            ],
            [
                'title' => 'Manufacturing Workforce Support',
                'text' => 'Recruitment and HR support for production, maintenance, quality, purchase, stores, administration and plant operations.',
                'icon' => 'ri-settings-3-line',
            ],
            [
                'title' => 'Energy Project Workforce Support',
                'text' => 'Hiring support for oil and gas projects, renewable energy sites, installation teams, O&M teams and project execution roles.',
                'icon' => 'ri-flashlight-line',
            ],
            [
                'title' => 'Safety & Compliance Role Hiring',
                'text' => 'Recruitment support for safety officers, HSE professionals, compliance coordinators, audit support executives and training coordinators.',
                'icon' => 'ri-shield-check-line',
            ],
            [
                'title' => 'Leadership Hiring',
                'text' => 'Hiring support for plant heads, production heads, project heads, operations heads, safety leaders, regional heads and CXO roles.',
                'icon' => 'ri-user-star-line',
            ],
            [
                'title' => 'HRaaS & HR Outsourcing',
                'text' => 'Dedicated HR support for industrial businesses that need structured HR execution without building a large internal HR team.',
                'icon' => 'ri-customer-service-2-line',
            ],
            [
                'title' => 'Payroll, Attendance & Shift Coordination',
                'text' => 'Attendance inputs, shift records, overtime data, contractor records, salary changes, deductions and payroll communication.',
                'icon' => 'ri-money-dollar-circle-line',
            ],
            [
                'title' => 'Policy, Documentation & HR Audits',
                'text' => 'Employee handbooks, appointment letters, safety documentation, conduct rules, exit documents, HR audits and compliance checklists.',
                'icon' => 'ri-file-list-3-line',
            ],
            [
                'title' => 'HR Technology & Reporting',
                'text' => 'Dashboards for hiring, attendance, payroll, manpower deployment, employee records, compliance, attrition and HR action plans.',
                'icon' => 'ri-computer-line',
            ],
        ],
        'cta' => [
            'label' => 'Explore Industrial & Energy HR Services',
            'href' => 'whatwedo',
        ],
    ],
    'hiring_strategy' => [
        'section_id' => 'industry-hiring-strategy',
        'label' => 'Workforce Strategy',
        'heading' => 'Industrial hiring needs skill-fit, safety-fit, shift-fit and reliability-fit',
        'intro' => ['Industrial roles require discipline and practical capability. A machine operator must understand process. A technician must respond quickly. A supervisor must manage people and output. A safety officer must protect both workers and the organization. A plant leader must balance productivity, cost and compliance.', 'Mirashka helps industrial businesses define workforce requirements before sourcing. We map skill requirements, shift expectations, safety exposure, site location, experience level, salary range, contractor or permanent role type, reporting structure and productivity expectations.'],
        'groups' => [
            [
                'title' => 'Hiring Strategy Includes',
                'items' => ['Role and KRA definition', 'Skill and experience mapping', 'Plant-wise or site-wise manpower planning', 'Shift requirement mapping', 'Candidate sourcing and screening', 'Safety and reliability-fit review', 'Interview coordination', 'Salary and expectation alignment', 'Joining and documentation checklist', 'Weekly hiring dashboard'],
            ],
            [
                'title' => 'Workforce Strategy Includes',
                'items' => ['Plant-wise manpower planning', 'Site deployment planning', 'Shift roster visibility', 'Contract and permanent workforce separation', 'Attendance input discipline', 'Overtime coordination', 'Training and safety record tracking', 'HR reporting structure', 'Leadership and succession planning'],
            ],
        ],
        'image' => 'assets/frontend/img/industries/healthcare-hiring-workforce-strategy.webp',
        'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
        'image_alt' => 'Industrial hiring funnel with filters: Skill Fit, Safety Fit, Shift Fit, Site Fit and Reliability Fit',
        'image_secondary' => 'assets/frontend/img/industries/healthcare-workforce-challenge.webp',
        'image_secondary_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
        'image_secondary_alt' => 'Industrial workforce planning and structured hiring support',
        'cta' => [
            'label' => 'Build My Industrial Workforce Plan',
            'href' => '#industry-form',
        ],
    ],
    'compliance' => [
        'label' => 'HR Operations',
        'heading' => 'Create workforce discipline across plants, sites, shifts and project locations',
        'intro' => ['Industrial and energy businesses often operate through shifts, plants, sites, warehouses, project locations and field teams. This creates the need for structured attendance, payroll inputs, overtime records, safety documentation, employee files, onboarding and exit processes.', 'Mirashka helps industrial businesses create HR operating systems that improve visibility, reduce confusion and support consistent execution.'],
        'image' => 'assets/frontend/img/industries/healthcare-compliance-documentation-hr-operations.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-card-policy.png',
        'image_alt' => 'Industrial employee file, shift roster, safety checklist and compliance shield visual',
        'cta' => 'Request Industrial HR Documentation Review',
        'cta_href' => '#industry-form',
        'cards' => [
            [
                'title' => 'Employee Documentation',
                'text' => 'Appointment letters, joining forms, ID proofs, qualification records, experience records, skill records and employee files.',
                'icon' => 'ri-file-list-3-line',
                'image' => 'assets/frontend/img/compliance/cwi-card-policy.png',
            ],
            [
                'title' => 'Attendance & Shift Process',
                'text' => 'Shift rosters, attendance inputs, late marks, overtime records, weekly offs, leave records and supervisor approvals.',
                'icon' => 'ri-calendar-check-line',
                'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'active' => true,
            ],
            [
                'title' => 'Safety & Training Records',
                'text' => 'Safety induction records, PPE acknowledgement, site training documentation, SOP acknowledgement and safety compliance checklists.',
                'icon' => 'ri-shield-check-line',
                'image' => 'assets/frontend/img/compliance/cwi-risk.png',
            ],
            [
                'title' => 'Contractor & Site Workforce Records',
                'text' => 'Contract manpower records, site deployment lists, supervisor mapping, work allocation records and monthly workforce reporting.',
                'icon' => 'ri-team-line',
                'image' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
            [
                'title' => 'Payroll Coordination',
                'text' => 'Salary inputs, attendance data, overtime, deductions, reimbursements, incentives, contractor inputs and payroll communication.',
                'icon' => 'ri-money-dollar-circle-line',
                'image' => 'assets/frontend/img/workforce/wfm-card-payroll.png',
                'active' => true,
            ],
            [
                'title' => 'Exit Management',
                'text' => 'Resignation documentation, tool or asset return, handover process, clearance checklist, full and final coordination and exit feedback.',
                'icon' => 'ri-logout-box-r-line',
                'image' => 'assets/frontend/img/compliance/cwi-services.png',
                'active' => true,
            ],
        ],
    ],
    'use_cases' => [
        'label' => 'Industrial & Energy HR Support in Action',
        'heading' => 'Practical people solutions for industrial workforce challenges',
        'tags' => ['Skilled Manpower', 'Safer Operations', 'Better Control', 'Stronger Leadership'],
        'cards' => [
            [
                'tab_id' => 'plant-manpower',
                'tab_label' => 'Plant',
                'title' => 'Case Study 1: Plant Manpower Planning for a Manufacturing Unit',
                'pane_heading' => 'Plant-wise manpower plan and shift roster visibility.',
                'challenge' => 'A manufacturing unit needed structured manpower planning across production, maintenance and quality teams.',
                'approach' => 'Created plant-wise manpower plan, shift roster visibility, attendance input rhythm and HR reporting format.',
                'outcome' => 'Improved workforce visibility, better shift control and stronger production readiness.',
                'image' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
            ],
            [
                'tab_id' => 'energy-project',
                'tab_label' => 'Energy',
                'title' => 'Case Study 2: Energy Project Workforce Deployment',
                'pane_heading' => 'Site deployment planning for installation and O&M teams.',
                'challenge' => 'A renewable energy business needed installation and O&M teams across multiple project sites.',
                'approach' => 'Mapped site-wise manpower needs, created deployment plan, hiring tracker and contractor record structure.',
                'outcome' => 'Improved project staffing speed and stronger site workforce control.',
                'image' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
                'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
            ],
            [
                'tab_id' => 'safety-docs',
                'tab_label' => 'Safety',
                'title' => 'Case Study 3: Safety Documentation Structuring',
                'pane_heading' => 'Safety induction records, PPE acknowledgement and training documentation.',
                'challenge' => 'An industrial company had incomplete safety induction records and inconsistent training documentation.',
                'approach' => 'Designed safety induction checklist, PPE acknowledgement format, training record structure and HR audit report.',
                'outcome' => 'Stronger safety documentation discipline and improved compliance readiness.',
                'image' => 'assets/frontend/img/workforce/wfm-hero.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-services.png',
            ],
            [
                'tab_id' => 'ind-leadership',
                'tab_label' => 'Leadership',
                'title' => 'Case Study 4: Industrial Leadership Hiring',
                'pane_heading' => 'Plant or operations leader for productivity, safety and team discipline.',
                'challenge' => 'A growing industrial business needed a plant or operations leader to manage productivity, safety and team discipline.',
                'approach' => 'Defined leadership mandate, mapped relevant industrial talent and supported structured evaluation.',
                'outcome' => 'Better leadership alignment and stronger operational scale readiness.',
                'image' => 'assets/frontend/img/compliance/cwi-card-policy.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
        ],
        'cta' => [
            'label' => 'Discuss a Similar Industrial Case',
            'href' => '#industry-form',
        ],
    ],
    'health_check' => [
        'label' => 'Start With Diagnosis',
        'heading' => 'How ready is your industrial HR system for scale and compliance?',
        'content' => 'Mirashka\'s Industrial & Energy HR Health Check helps manufacturing units, oil and gas businesses, renewable energy companies and project-led organizations identify gaps in hiring, attendance, payroll, safety documentation, compliance, employee engagement, leadership and HR technology.',
        'covers' => ['Hiring process quality', 'Role clarity and KRAs', 'Plant or site manpower gaps', 'Attendance and shift process', 'Payroll and overtime input discipline', 'Employee documentation', 'Safety and training records', 'Contractor workforce records', 'POSH and workplace ethics readiness', 'Attrition and retention risk', 'Leadership gap assessment', 'HR technology readiness', 'Reporting and dashboard maturity'],
        'output' => 'A practical HR improvement roadmap with risk areas, priority actions and recommended Mirashka service plan.',
        'cta' => [
            'label' => 'Request Industrial HR Health Check',
            'href' => '#industry-form',
        ],
        'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
    ],
    'form' => [
        'label' => 'Talk to Mirashka',
        'heading' => 'Build a stronger industrial workforce with Mirashka',
        'content' => 'Share your industrial or energy HR requirement. Mirashka will help identify whether you need technical manpower hiring, plant staffing, site workforce planning, safety hiring, HRaaS, payroll coordination, documentation or a complete people operating model.',
        'lead_type' => 'industrial_energy_hr_enquiry',
        'segments' => ['Manufacturing', 'Oil & Gas', 'Renewable Energy', 'Industrial Services', 'Engineering Company', 'EPC / Project Business', 'Energy Equipment Business', 'Other Industrial Business'],
        'services' => ['Technical Manpower Hiring', 'Plant Staffing', 'Site Workforce Planning', 'Safety / HSE Hiring', 'Leadership Hiring', 'HRaaS / HR Outsourcing', 'Payroll & Attendance Coordination', 'Shift Workforce Planning', 'Policy Documentation', 'HR Compliance Audit', 'Employee Engagement', 'HR Technology', 'Not Sure — Need Consultation'],
        'submit' => 'Submit Industrial HR Enquiry',
        'secondary_cta' => [
            'label' => 'Book 30-Minute Industrial HR Consultation',
            'href' => 'https://calendly.com/elevateonemedia/30min',
        ],
        'image' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-page-partner.png',
    ],
    'faq_blog' => [
        'label' => 'Learn More',
        'heading' => 'Industrial & energy HR questions answered',
        'faqs' => [
            [
                'question' => 'What industrial and energy roles can Mirashka help hire for?',
                'answer' => 'Mirashka can support hiring for operators, technicians, engineers, supervisors, safety officers, project teams, plant staff, maintenance teams, quality teams and leadership roles.',
            ],
            [
                'question' => 'Can Mirashka support plant and site manpower planning?',
                'answer' => 'Yes. Mirashka can help create plant-wise or site-wise manpower plans, shift rosters, attendance input systems and HR reporting formats.',
            ],
            [
                'question' => 'Does Mirashka provide HRaaS for manufacturing and energy companies?',
                'answer' => 'Yes. Mirashka HRaaS is suitable for manufacturing units, industrial service providers, oil and gas contractors, renewable energy businesses and project-led companies.',
            ],
            [
                'question' => 'Can Mirashka help with payroll and overtime coordination?',
                'answer' => 'Yes. Mirashka can support attendance inputs, shift records, overtime data, contractor inputs, reimbursements, salary changes and payroll communication.',
            ],
            [
                'question' => 'Can Mirashka help with safety and compliance documentation?',
                'answer' => 'Yes. Mirashka can support employee records, safety induction records, PPE acknowledgement, training records, policy documentation and HR audit checklists.',
            ],
        ],
        'blogs' => [],
        'cta' => [
            'label' => 'Read Industrial & Energy HR Insights',
            'href' => '/blog',
        ],
        'image' => 'assets/frontend/img/industries/industry-form-consultant.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
    ],
];
