<?php

/**
 * Technology industry category page content.
 */
return [
    'meta' => [
        'title' => 'Technology HR Solutions | Software, SaaS & IT | Mirashka',
        'description' => 'Mirashka HR solutions for technology — IT recruitment, tech staffing, leadership hiring, HRaaS, remote HR, payroll coordination and employee engagement for SaaS, infrastructure and emerging tech businesses.',
        'keywords' => 'technology HR solutions, IT recruitment, tech staffing, SaaS hiring, remote HR, developer recruitment, Mirashka technology',
    ],
    'hero' => [
        'label' => 'Technology HR Solutions',
        'heading' => 'People Systems for Fast-Moving Technology Businesses',
        'subheading' => ['Technology companies need people who can build, solve, scale, support, innovate and adapt continuously.', 'Mirashka helps technology businesses build stronger HR systems through IT recruitment, tech staffing, leadership hiring, HRaaS, payroll coordination, employee engagement, policy documentation, remote HR support and HR technology solutions.', 'Whether you are a SaaS startup, software development company, IT infrastructure provider, hardware business, AI company, cybersecurity firm or emerging technology venture, Mirashka works as your extended HR partner to help you hire, manage and retain high-performing teams.'],
        'ctas' => [
            [
                'label' => 'Book Technology HR Consultation',
                'href' => '#industry-form',
            ],
            [
                'label' => 'Request Technology HR Health Check',
                'href' => '#industry-health-check',
            ],
        ],
        'image' => 'assets/frontend/img/Whatwedo/we-build-influence-banner.webp',
        'image_fallback' => 'assets/frontend/img/Whatwedo/we-build-influence-banner.webp',
    ],
    'reality' => [
        'section_name' => 'Technology HR Reality',
        'before_title' => 'The Technology Talent Challenge',
        'label' => 'The Technology Talent Challenge',
        'heading' => 'In technology, the right talent can accelerate or delay growth',
        'paragraphs' => ['Technology businesses move fast, but hiring often becomes the bottleneck. Product timelines, client delivery, platform stability, support quality and innovation depend on having the right people in the right roles at the right time.', 'The technology sector faces skill shortages, salary competition, remote team complexity, leadership gaps, project-based hiring pressure, retention challenges and constant need for upskilling.', 'Mirashka understands that technology HR is not only about filling technical positions. It is about building scalable, agile and performance-oriented people systems.'],
        'challenges_heading' => 'Key Challenges',
        'pain_points' => ['Shortage of skilled technical talent', 'Delayed hiring for critical technology roles', 'High competition for developers and engineers', 'Remote and hybrid workforce complexity', 'Salary benchmarking challenges', 'Attrition in technology teams', 'Weak onboarding for technical roles', 'Leadership gaps in product, engineering and delivery', 'Project-based staffing pressure', 'Need for HR systems that scale with growth'],
        'cta' => 'Discuss Technology Workforce Challenges',
        'cta_href' => '#industry-form',
        'section_bg' => 'assets/frontend/img/tab-sec-bg.jpg',
        'image' => 'assets/frontend/img/industries/healthcare-workforce-challenge.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-risk.png',
        'image_alt' => 'Product delivery pressure and technology hiring pipeline dashboard',
        'standout' => [
            'before_title' => 'The Technology Talent Challenge',
            'heading' => 'In technology, the right talent can accelerate or delay growth',
            'list_use_fontawesome' => true,
            'grid' => [
                'left_image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'left_image_fallback' => 'assets/frontend/img/compliance/cwi-card-training.png',
                'left_card' => [
                    'icon' => 'ri-cpu-line',
                    'title' => 'Key Challenges',
                    'list' => ['Shortage of skilled technical talent', 'Delayed hiring for critical technology roles', 'High competition for developers and engineers', 'Remote and hybrid workforce complexity', 'Salary benchmarking challenges'],
                ],
                'center' => [
                    'icon' => 'ri-cpu-line',
                    'title' => 'Why Technology Workforce Management Is Different',
                    'paragraphs' => ['Technology businesses move fast, but hiring often becomes the bottleneck. Product timelines, client delivery, platform stability, support quality and innovation depend on having the right people in the right roles at the right time.', 'The technology sector faces skill shortages, salary competition, remote team complexity, leadership gaps, project-based hiring pressure, retention challenges and constant need for upskilling.', 'Mirashka understands that technology HR is not only about filling technical positions. It is about building scalable, agile and performance-oriented people systems.'],
                    'cta' => 'Discuss Technology Workforce Challenges',
                    'cta_url' => '#industry-form',
                ],
                'right_card' => [
                    'icon' => 'ri-shield-check-line',
                    'title' => 'Key Challenges',
                    'list' => ['Attrition in technology teams', 'Weak onboarding for technical roles', 'Leadership gaps in product, engineering and delivery', 'Project-based staffing pressure', 'Need for HR systems that scale with growth'],
                ],
                'right_image' => 'assets/frontend/img/compliance/cwi-integrity.png',
                'right_image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
            ],
        ],
    ],
    'sub_industries' => [
        'label' => 'Technology Segments',
        'heading' => 'HR solutions for every major technology business model',
        'content' => 'Technology is not one workforce model. A SaaS company, hardware company and AI startup need different hiring methods, skill evaluation, team structures and leadership systems. Mirashka builds HR solutions according to the technology business model.',
        'kicker' => 'Technology',
        'section_bg' => 'assets/frontend/img/tab-sec-bg.jpg',
        'cta' => 'Speak to a Technology HR Advisor',
        'cta_href' => '#industry-form',
        'cards' => [
            [
                'title' => 'Software & SaaS',
                'kicker' => 'Technology',
                'subcategories' => ['Software developers', 'Frontend engineers', 'Backend engineers', 'Full-stack developers', 'Product managers', 'QA engineers', 'DevOps engineers', 'UI/UX designers', 'Customer success teams', 'Sales teams', 'Technology leaders'],
                'description' => 'For software companies, SaaS platforms, product startups, web application businesses and digital product companies, Mirashka supports developer hiring, product roles, sales hiring, customer success hiring, HRaaS, leadership hiring and employee engagement.',
                'cta' => 'Explore Software & SaaS HR Solutions',
                'href' => '#software-saas',
                'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-services.png',
            ],
            [
                'title' => 'Hardware & Infrastructure',
                'kicker' => 'Technology',
                'subcategories' => ['Network engineers', 'System administrators', 'Field engineers', 'Infrastructure sales executives', 'Project managers', 'Cloud engineers', 'Support engineers', 'Presales consultants', 'Service teams', 'Business leaders'],
                'description' => 'For IT infrastructure companies, hardware providers, networking businesses, system integrators, cloud infrastructure providers and data centre solution companies, Mirashka supports technical hiring, field teams, project teams, sales teams, service engineers and leadership roles.',
                'cta' => 'Explore Hardware & Infrastructure HR Solutions',
                'href' => '#hardware-infrastructure',
                'image' => 'assets/frontend/img/hraas/hraas-hero-split.webp',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
            [
                'title' => 'Emerging Technologies',
                'kicker' => 'Technology',
                'subcategories' => ['AI engineers', 'Data scientists', 'Cybersecurity analysts', 'Automation engineers', 'IoT specialists', 'Machine learning engineers', 'Cloud security professionals', 'Product innovators', 'Research teams', 'Emerging technology leaders'],
                'description' => 'For AI, cybersecurity, IoT, blockchain, automation, robotics, data analytics and next-generation technology ventures, Mirashka supports specialist hiring, leadership search, remote team management, HRaaS and scalable people systems.',
                'cta' => 'Explore Emerging Technologies HR Solutions',
                'href' => '#emerging-technologies',
                'image' => 'assets/frontend/img/workforce/wfm-reporting-team-hands.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
            ],
        ],
    ],
    'pulse' => [
        'label' => 'PULSE for Technology',
        'heading' => 'A technology-ready people framework for hiring speed, skill quality and scalable growth',
        'content' => 'Mirashka applies its PULSE Framework to technology businesses by connecting compliance, workforce operations, leadership hiring, tech recruitment and HRaaS into one agile people system.',
        'cards' => [
            [
                'letter' => 'P',
                'title' => 'Protect',
                'subtitle' => 'Compliance & Workplace Integrity',
                'text' => 'Protect technology businesses through employee documentation, IP and confidentiality guidelines, HR policies, workplace ethics, POSH readiness and compliance discipline.',
                'image' => 'assets/img/protect.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-card-policy.png',
            ],
            [
                'letter' => 'U',
                'title' => 'Unify',
                'subtitle' => 'Workforce Management',
                'text' => 'Unify onboarding, payroll inputs, remote employee records, role documentation, attendance, performance communication and HR reporting.',
                'image' => 'assets/img/unify.png',
                'image_fallback' => 'assets/frontend/img/workforce/wfm-card-payroll.png',
            ],
            [
                'letter' => 'L',
                'title' => 'Lead',
                'subtitle' => 'Leadership & Organizational Excellence',
                'text' => 'Build leadership capability through CTO, product, engineering, delivery, sales, operations and business leadership hiring.',
                'image' => 'assets/img/lead.png',
                'image_fallback' => 'assets/frontend/img/leadership/ldr-board-advisory.png',
            ],
            [
                'letter' => 'S',
                'title' => 'Source',
                'subtitle' => 'Talent Acquisition & Staffing',
                'text' => 'Source technology talent across software, cloud, infrastructure, support, cybersecurity, AI, product, sales and leadership roles.',
                'image' => 'assets/img/source.png',
                'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-card-executive-search.png',
            ],
            [
                'letter' => 'E',
                'title' => 'Empower',
                'subtitle' => 'HR as a Service',
                'text' => 'Empower technology businesses with HR outsourcing, employer branding, engagement, retention strategy, HR technology and remote HR support.',
                'image' => 'assets/img/empower.png',
                'image_fallback' => 'assets/frontend/img/hraas/hraas-card-engagement.png',
            ],
        ],
        'cta' => [
            'label' => 'Apply PULSE to My Technology Business',
            'href' => '#industry-form',
        ],
    ],
    'services' => [
        'label' => 'What Mirashka Delivers',
        'heading' => 'Complete HR support for technology companies that need speed without losing structure',
        'image' => 'assets/frontend/img/home/home-why-mirashka-hero.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
        'image_secondary' => 'assets/frontend/img/compliance/cwi-services.png',
        'image_secondary_fallback' => 'assets/frontend/img/hraas/hraas-page-partner.png',
        'cards' => [
            [
                'title' => 'IT Recruitment',
                'text' => 'Hiring support for developers, engineers, QA, DevOps, cloud, cybersecurity, data, product and technical roles.',
                'icon' => 'ri-code-s-slash-line',
            ],
            [
                'title' => 'Tech Staffing',
                'text' => 'Flexible staffing for project teams, field engineers, support teams, contract roles and specialized technology assignments.',
                'icon' => 'ri-cpu-line',
            ],
            [
                'title' => 'Leadership Hiring',
                'text' => 'Hiring support for CTOs, technology heads, product heads, engineering managers, delivery heads, sales leaders and CXO roles.',
                'icon' => 'ri-user-star-line',
            ],
            [
                'title' => 'HRaaS & HR Outsourcing',
                'text' => 'Dedicated HR support for technology companies that need professional HR execution without building a large internal HR team.',
                'icon' => 'ri-customer-service-2-line',
            ],
            [
                'title' => 'Remote HR Solutions',
                'text' => 'Support for remote onboarding, employee records, engagement, documentation, reporting and distributed workforce coordination.',
                'icon' => 'ri-global-line',
            ],
            [
                'title' => 'Payroll & Workforce Administration',
                'text' => 'Payroll input coordination, attendance records, reimbursement tracking, salary change data and employee lifecycle documentation.',
                'icon' => 'ri-money-dollar-circle-line',
            ],
            [
                'title' => 'Policy & Documentation Support',
                'text' => 'Employee handbooks, offer letters, appointment letters, IP guidelines, confidentiality clauses, code of conduct and HR policies.',
                'icon' => 'ri-file-list-3-line',
            ],
            [
                'title' => 'Employee Engagement & Retention',
                'text' => 'Employee surveys, retention plans, performance communication, tech team engagement and culture-building support.',
                'icon' => 'ri-emotion-happy-line',
            ],
            [
                'title' => 'Employer Branding',
                'text' => 'Positioning support to make technology companies more attractive to developers, engineers and specialist talent.',
                'icon' => 'ri-megaphone-line',
            ],
            [
                'title' => 'HR Technology & Reporting',
                'text' => 'Dashboards for hiring, employee records, onboarding, payroll, attrition, engagement, performance and HR actions.',
                'icon' => 'ri-computer-line',
            ],
        ],
        'cta' => [
            'label' => 'Explore Technology HR Services',
            'href' => 'whatwedo',
        ],
    ],
    'hiring_strategy' => [
        'section_id' => 'industry-hiring-strategy',
        'label' => 'Talent Strategy',
        'heading' => 'Technology hiring needs skill-fit, culture-fit, delivery-fit and growth-fit',
        'intro' => ['Technology hiring cannot be handled through keyword matching alone. A developer must fit the stack and the delivery culture. A DevOps engineer must understand uptime and responsibility. A product manager must think in users and business outcomes. A technology leader must balance innovation, execution and people management.', 'Mirashka helps technology companies define the role before sourcing. We map technology stack, project stage, experience level, business model, reporting structure, salary range, remote working expectations, delivery responsibility and long-term growth fit.'],
        'groups' => [
            [
                'title' => 'Hiring Strategy Includes',
                'items' => ['Role and KRA definition', 'Technology stack mapping', 'Experience and project exposure mapping', 'Candidate sourcing strategy', 'Screening and shortlisting', 'Technical evaluation coordination', 'Culture and communication fit review', 'Salary and expectation alignment', 'Offer and joining support', 'Weekly hiring dashboard'],
            ],
            [
                'title' => 'Workforce Strategy Includes',
                'items' => ['Project-wise manpower planning', 'Remote and hybrid team coordination', 'Onboarding documentation', 'Employee lifecycle management', 'Retention and engagement planning', 'Performance review formats', 'HR reporting structure', 'Leadership and succession planning'],
            ],
        ],
        'image' => 'assets/frontend/img/industries/healthcare-hiring-workforce-strategy.webp',
        'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
        'image_alt' => 'Technology hiring funnel with filters: Skill Fit, Stack Fit, Culture Fit, Delivery Fit and Growth Fit',
        'image_secondary' => 'assets/frontend/img/industries/healthcare-workforce-challenge.webp',
        'image_secondary_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
        'image_secondary_alt' => 'Technology workforce planning and structured hiring support',
        'cta' => [
            'label' => 'Build My Technology Talent Pipeline',
            'href' => '#industry-form',
        ],
    ],
    'compliance' => [
        'label' => 'Compliance & HR Operations',
        'heading' => 'Build HR discipline for teams that create intellectual value',
        'intro' => ['Technology companies need structured employment documentation, confidentiality clauses, intellectual property guidelines, remote work policies, attendance systems, payroll records, performance frameworks and exit documentation.', 'Mirashka helps technology businesses create HR operations that protect the organization, support employees and give leadership better visibility.'],
        'image' => 'assets/frontend/img/industries/healthcare-compliance-documentation-hr-operations.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-card-policy.png',
        'image_alt' => 'Technology employee file, IP policy document and HR handbook visual',
        'cta' => 'Request Technology HR Documentation Review',
        'cta_href' => '#industry-form',
        'cards' => [
            [
                'title' => 'Employee Documentation',
                'text' => 'Offer letters, appointment letters, joining forms, employee records, ID proofs, qualification details, experience records and employment files.',
                'icon' => 'ri-file-list-3-line',
                'image' => 'assets/frontend/img/compliance/cwi-card-policy.png',
            ],
            [
                'title' => 'IP & Confidentiality Guidelines',
                'text' => 'Confidentiality clauses, IP ownership references, data access expectations, device usage guidelines and exit handover process.',
                'icon' => 'ri-lock-line',
                'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'active' => true,
            ],
            [
                'title' => 'Policy Framework',
                'text' => 'Leave policy, remote work policy, attendance policy, reimbursement policy, code of conduct, workplace behavior guidelines and escalation process.',
                'icon' => 'ri-book-2-line',
                'image' => 'assets/frontend/img/compliance/cwi-risk.png',
            ],
            [
                'title' => 'Payroll & Workforce Administration',
                'text' => 'Attendance inputs, salary changes, reimbursements, incentive inputs, freelance or contract coordination and payroll communication.',
                'icon' => 'ri-money-dollar-circle-line',
                'image' => 'assets/frontend/img/workforce/wfm-card-payroll.png',
                'active' => true,
            ],
            [
                'title' => 'HR Audit & Risk Review',
                'text' => 'Review of employee records, documentation gaps, policy readiness, POSH compliance, exit process and HR operating discipline.',
                'icon' => 'ri-search-eye-line',
                'image' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
            [
                'title' => 'Exit Management',
                'text' => 'Resignation documentation, project handover, access revocation checklist, device return, full and final coordination and exit feedback.',
                'icon' => 'ri-logout-box-r-line',
                'image' => 'assets/frontend/img/compliance/cwi-services.png',
                'active' => true,
            ],
        ],
    ],
    'use_cases' => [
        'label' => 'Technology HR Support in Action',
        'heading' => 'Practical people solutions for technology workforce challenges',
        'tags' => ['Faster Hiring', 'Better Stack Fit', 'Stronger HR Structure', 'Leadership Readiness'],
        'cards' => [
            [
                'tab_id' => 'saas-dev',
                'tab_label' => 'SaaS',
                'title' => 'Case Study 1: Developer Hiring for a SaaS Product Team',
                'pane_heading' => 'Technology stack mapping and weekly hiring dashboard for product teams.',
                'challenge' => 'A SaaS company needed developers urgently but was receiving irrelevant profiles.',
                'approach' => 'Mapped the technology stack, defined role expectations, improved sourcing filters and created a weekly hiring dashboard.',
                'outcome' => 'Better candidate relevance, faster shortlisting and improved hiring visibility.',
                'image' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
            ],
            [
                'tab_id' => 'infra-field',
                'tab_label' => 'Infrastructure',
                'title' => 'Case Study 2: IT Infrastructure Field Team Hiring',
                'pane_heading' => 'Location-wise hiring plan for engineers and support professionals.',
                'challenge' => 'An infrastructure business needed engineers and support professionals across multiple locations.',
                'approach' => 'Created location-wise hiring plan, technical screening checklist, interview coordination process and joining tracker.',
                'outcome' => 'Improved field team readiness and stronger manpower visibility.',
                'image' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
                'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
            ],
            [
                'tab_id' => 'startup-hraas',
                'tab_label' => 'HRaaS',
                'title' => 'Case Study 3: HRaaS for a Lean Technology Startup',
                'pane_heading' => 'Documentation, onboarding and employee records without a full internal HR team.',
                'challenge' => 'A growing tech startup needed HR structure but could not build a full internal HR department.',
                'approach' => 'Provided HRaaS support, created documentation, onboarding process, employee records and engagement rhythm.',
                'outcome' => 'Cleaner HR operations, stronger employee experience and reduced founder dependency.',
                'image' => 'assets/frontend/img/workforce/wfm-hero.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-services.png',
            ],
            [
                'tab_id' => 'tech-leadership',
                'tab_label' => 'Leadership',
                'title' => 'Case Study 4: Leadership Hiring for Technology Expansion',
                'pane_heading' => 'Senior leader for product, engineering or delivery scale.',
                'challenge' => 'A technology company needed a senior leader to manage product, engineering or delivery scale.',
                'approach' => 'Defined leadership mandate, mapped relevant talent, evaluated business fit and supported interview discussions.',
                'outcome' => 'Improved leadership alignment and stronger growth readiness.',
                'image' => 'assets/frontend/img/compliance/cwi-card-policy.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
        ],
        'cta' => [
            'label' => 'Discuss a Similar Technology Case',
            'href' => '#industry-form',
        ],
    ],
    'health_check' => [
        'label' => 'Start With Diagnosis',
        'heading' => 'How ready is your technology HR system for scale?',
        'content' => 'Mirashka\'s Technology HR Health Check helps software companies, SaaS startups, infrastructure businesses and emerging technology ventures identify gaps in hiring, onboarding, documentation, payroll, employee engagement, leadership and HR technology.',
        'covers' => ['Hiring process quality', 'Role clarity and KRAs', 'Technology stack hiring gaps', 'Onboarding process', 'Employee documentation', 'Remote work policy readiness', 'Payroll and reimbursement process', 'IP and confidentiality documentation', 'POSH and workplace ethics readiness', 'Attrition and retention risk', 'Leadership gap assessment', 'HR technology readiness', 'Reporting and dashboard maturity'],
        'output' => 'A practical HR improvement roadmap with risk areas, priority actions and recommended Mirashka service plan.',
        'cta' => [
            'label' => 'Request Technology HR Health Check',
            'href' => '#industry-form',
        ],
        'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
    ],
    'form' => [
        'label' => 'Talk to Mirashka',
        'heading' => 'Build a stronger technology workforce with Mirashka',
        'content' => 'Share your technology HR requirement. Mirashka will help identify whether you need IT recruitment, tech staffing, HRaaS, payroll coordination, leadership hiring, employee engagement, HR documentation or a complete people operating model.',
        'lead_type' => 'technology_hr_enquiry',
        'segments' => ['Software & SaaS', 'Hardware & Infrastructure', 'Emerging Technologies', 'IT Services', 'System Integration', 'Cybersecurity', 'Cloud Services', 'AI / Data / Automation', 'Other Technology Business'],
        'services' => ['IT Recruitment', 'Tech Staffing', 'Leadership Hiring', 'HRaaS / HR Outsourcing', 'Payroll Support', 'Policy Documentation', 'Remote HR Support', 'Employee Engagement', 'Employer Branding', 'HR Technology', 'Not Sure — Need Consultation'],
        'submit' => 'Submit Technology HR Enquiry',
        'secondary_cta' => [
            'label' => 'Book 30-Minute Technology HR Consultation',
            'href' => 'https://calendly.com/elevateonemedia/30min',
        ],
        'image' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-page-partner.png',
    ],
    'faq_blog' => [
        'label' => 'Learn More',
        'heading' => 'Technology HR questions answered',
        'faqs' => [
            [
                'question' => 'What technology roles can Mirashka help hire for?',
                'answer' => 'Mirashka can support hiring for developers, QA engineers, DevOps engineers, cloud engineers, infrastructure professionals, cybersecurity talent, product roles, sales teams and leadership roles.',
            ],
            [
                'question' => 'Can Mirashka support IT staffing for project-based requirements?',
                'answer' => 'Yes. Mirashka can support staffing for project teams, field engineers, support teams, contract roles and specialized technology assignments.',
            ],
            [
                'question' => 'Does Mirashka provide HRaaS for technology startups?',
                'answer' => 'Yes. Mirashka HRaaS is suitable for SaaS startups, software firms, IT services companies, product companies and emerging technology ventures.',
            ],
            [
                'question' => 'Can Mirashka help with remote team HR management?',
                'answer' => 'Yes. Mirashka can support remote onboarding, employee records, policy documentation, engagement, payroll coordination and HR reporting.',
            ],
            [
                'question' => 'Can Mirashka support technology leadership hiring?',
                'answer' => 'Yes. Mirashka supports leadership hiring for CTO, product head, engineering head, delivery head, sales head, operations head and CXO roles.',
            ],
        ],
        'blogs' => [],
        'cta' => [
            'label' => 'Read Technology HR Insights',
            'href' => '/blog',
        ],
        'image' => 'assets/frontend/img/industries/industry-form-consultant.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
    ],
];
