<?php

/**
 * Financial Services industry subcategory pages.
 */
return [
    'banking' => [
        'meta' => [
            'title' => 'Banking HR Solutions | Banks, NBFCs & Branch-Led Institutions | Mirashka',
            'description' => 'Mirashka HR solutions for banks, NBFCs and branch-led financial institutions — recruitment, HRaaS, payroll coordination, compliance support, leadership hiring and employee engagement.',
            'keywords' => 'banking HR, bank recruitment, NBFC HR, branch hiring, banking compliance HR, Mirashka banking',
        ],
        'parent_label' => 'Financial Services',
        'parent_route' => 'industries.financial-services',
        'hero' => [
            'label' => 'Banking HR Solutions',
            'heading' => 'People Systems for Trust, Compliance and Branch-Led Growth',
            'subheading' => [
                'Banking businesses run on people who can manage trust, documentation, targets, compliance, customer relationships and operational discipline.',
                'Mirashka helps banks, NBFCs and branch-led financial institutions build stronger HR systems through recruitment, HRaaS, payroll coordination, compliance support, employee documentation, leadership hiring, branch workforce planning and employee engagement.',
                'From relationship managers and branch teams to credit officers, operations executives and senior leaders, Mirashka helps banking businesses hire, manage and retain the right people with structure and confidence.',
            ],
            'ctas' => [
                ['label' => 'Book Banking HR Consultation', 'href' => '#industry-form'],
                ['label' => 'Request Banking HR Health Check', 'href' => '#industry-form'],
            ],
            'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
            'image_fallback' => 'assets/frontend/img/Whatwedo/we-build-influence-banner.webp',
        ],
        'reality' => [
            'section_name' => 'The Banking Workforce Challenge',
            'before_title' => 'The Banking Workforce Challenge',
            'label' => 'The Banking Workforce Challenge',
            'heading' => 'In banking, every employee carries trust, process and responsibility',
            'paragraphs' => [
                'Banking is one of the most people-sensitive industries. A single role can influence customer trust, regulatory discipline, branch performance and business reputation. The workforce must be trained, verified, documented, target-oriented and process-driven.',
                'Banks and NBFCs often face hiring pressure, branch-level attrition, documentation gaps, payroll and incentive complexity, compliance-sensitive onboarding and leadership requirements for expansion.',
                'Mirashka understands that banking HR is not only about filling vacancies. It is about creating a stable, compliant and performance-oriented workforce.',
            ],
            'challenges_heading' => 'Key Challenges',
            'pain_points' => [
                'High attrition in sales and relationship roles',
                'Delay in branch-level hiring',
                'Need for strong background verification',
                'Payroll and incentive coordination complexity',
                'Incomplete employee documentation',
                'Weak role clarity and KRAs',
                'Compliance-sensitive onboarding',
                'Leadership gaps in expansion markets',
                'Customer-facing behavior issues',
                'Lack of structured employee engagement',
            ],
            'cta' => 'Discuss Banking Workforce Challenges',
            'cta_href' => '#industry-form',
            'section_bg' => 'assets/frontend/img/tab-sec-bg.jpg',
            'image' => 'assets/frontend/img/compliance/cwi-risk.png',
            'image_fallback' => 'assets/frontend/img/compliance/cwi-integrity.png',
            'image_alt' => 'Busy branch operations and HR compliance checklist',
            'standout' => [
                'before_title' => 'The Banking Workforce Challenge',
                'heading' => 'In banking, every employee carries trust, process and responsibility',
                'list_use_fontawesome' => true,
                'grid' => [
                    'left_image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                    'left_image_fallback' => 'assets/frontend/img/compliance/cwi-card-training.png',
                    'left_card' => [
                        'icon' => 'ri-bank-line',
                        'title' => 'Key Challenges',
                        'list' => [
                            'High attrition in sales and relationship roles',
                            'Delay in branch-level hiring',
                            'Need for strong background verification',
                            'Payroll and incentive coordination complexity',
                            'Incomplete employee documentation',
                        ],
                    ],
                    'center' => [
                        'icon' => 'ri-bank-line',
                        'title' => 'Why Banking Workforce Management Is Different',
                        'paragraphs' => [
                            'Banking is one of the most people-sensitive industries. A single role can influence customer trust, regulatory discipline, branch performance and business reputation.',
                            'Banks and NBFCs often face hiring pressure, branch-level attrition, documentation gaps, payroll complexity and leadership requirements for expansion.',
                            'Mirashka understands that banking HR is not only about filling vacancies. It is about creating a stable, compliant and performance-oriented workforce.',
                        ],
                        'cta' => 'Discuss Banking Workforce Challenges',
                        'cta_url' => '#industry-form',
                    ],
                    'right_card' => [
                        'icon' => 'ri-shield-check-line',
                        'title' => 'Key Challenges',
                        'list' => [
                            'Weak role clarity and KRAs',
                            'Compliance-sensitive onboarding',
                            'Leadership gaps in expansion markets',
                            'Customer-facing behavior issues',
                            'Lack of structured employee engagement',
                        ],
                    ],
                    'right_image' => 'assets/frontend/img/compliance/cwi-integrity.png',
                    'right_image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
                ],
            ],
        ],
        'role_coverage' => [
            'label' => 'Role Coverage',
            'heading' => 'From branch hiring to leadership search, Mirashka supports the complete banking talent chain',
            'content' => 'Banking businesses require different talent layers: frontline sales, branch operations, credit, customer service, risk, compliance, relationship management and leadership. Mirashka supports both volume hiring and strategic hiring.',
            'kicker' => 'Banking',
            'section_bg' => 'assets/frontend/img/tab-sec-bg.jpg',
            'cta' => 'Start Banking Hiring Support',
            'cta_href' => '#industry-form',
            'cards' => [
                [
                    'title' => 'Branch & Frontline Roles',
                    'kicker' => 'Banking',
                    'subcategories' => [
                        'Branch Managers',
                        'Assistant Branch Managers',
                        'Relationship Managers',
                        'Customer Service Executives',
                        'Teller / Cash Desk Support',
                        'Branch Operations Executives',
                    ],
                    'description' => 'Frontline and branch teams that represent your institution to customers every day.',
                    'cta' => 'Start Banking Hiring Support',
                    'href' => '#industry-form',
                    'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                    'image_fallback' => 'assets/frontend/img/compliance/cwi-services.png',
                ],
                [
                    'title' => 'Sales & Business Roles',
                    'kicker' => 'Banking',
                    'subcategories' => [
                        'Sales Officers',
                        'Business Development Managers',
                        'Loan Officers',
                        'CASA Sales Teams',
                        'Insurance / Cross-Sell Executives',
                        'Retail Banking Sales Teams',
                    ],
                    'description' => 'Target-driven sales and business development roles across branches and territories.',
                    'cta' => 'Start Banking Hiring Support',
                    'href' => '#industry-form',
                    'image' => 'assets/frontend/img/hraas/hraas-hero-split.webp',
                    'image_fallback' => 'assets/frontend/img/compliance/cwi-integrity.png',
                ],
                [
                    'title' => 'Credit, Risk & Operations',
                    'kicker' => 'Banking',
                    'subcategories' => [
                        'Credit Officers',
                        'Loan Processing Executives',
                        'Operations Managers',
                        'Documentation Executives',
                        'Risk Support Teams',
                        'Verification Coordinators',
                    ],
                    'description' => 'Process-driven roles where documentation discipline and compliance matter deeply.',
                    'cta' => 'Start Banking Hiring Support',
                    'href' => '#industry-form',
                    'image' => 'assets/frontend/img/workforce/wfm-reporting-team-hands.png',
                    'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
                ],
                [
                    'title' => 'Leadership Roles',
                    'kicker' => 'Banking',
                    'subcategories' => [
                        'Cluster Heads',
                        'Regional Managers',
                        'Zonal Sales Heads',
                        'Business Heads',
                        'Operations Heads',
                        'CXO and senior leadership roles',
                    ],
                    'description' => 'Strategic hiring for leaders who can manage teams, targets and compliance discipline.',
                    'cta' => 'Start Banking Hiring Support',
                    'href' => '#industry-form',
                    'image' => 'assets/frontend/img/leadership/ldr-board-advisory.png',
                    'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-card-executive-search.png',
                ],
            ],
        ],
        'pulse' => [
            'label' => 'PULSE for Banking',
            'heading' => 'A banking-ready people framework for compliance, hiring and growth',
            'content' => 'Mirashka applies its PULSE Framework to banking businesses by connecting compliance, HR operations, leadership, staffing and HRaaS into one structured people model.',
            'cards' => [
                [
                    'letter' => 'P',
                    'title' => 'Protect',
                    'subtitle' => 'Compliance & Workplace Integrity',
                    'text' => 'Build policy discipline, employee documentation, workplace ethics, POSH readiness and HR risk control.',
                    'image' => 'assets/img/protect.png',
                    'image_fallback' => 'assets/frontend/img/compliance/cwi-card-policy.png',
                ],
                [
                    'letter' => 'U',
                    'title' => 'Unify',
                    'subtitle' => 'Workforce Management',
                    'text' => 'Unify payroll inputs, attendance, incentives, employee records, onboarding and exit processes across branches.',
                    'image' => 'assets/img/unify.png',
                    'image_fallback' => 'assets/frontend/img/workforce/wfm-card-payroll.png',
                ],
                [
                    'letter' => 'L',
                    'title' => 'Lead',
                    'subtitle' => 'Leadership & Organizational Excellence',
                    'text' => 'Hire and develop branch leaders, regional managers, business heads and expansion-ready leadership teams.',
                    'image' => 'assets/img/lead.png',
                    'image_fallback' => 'assets/frontend/img/leadership/ldr-board-advisory.png',
                ],
                [
                    'letter' => 'S',
                    'title' => 'Source',
                    'subtitle' => 'Talent Acquisition & Staffing',
                    'text' => 'Source banking talent for sales, branch, credit, operations, customer support and leadership roles.',
                    'image' => 'assets/img/source.png',
                    'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-card-executive-search.png',
                ],
                [
                    'letter' => 'E',
                    'title' => 'Empower',
                    'subtitle' => 'HR as a Service',
                    'text' => 'Support banking businesses with HR outsourcing, engagement, employer branding, retention and HR technology.',
                    'image' => 'assets/img/empower.png',
                    'image_fallback' => 'assets/frontend/img/hraas/hraas-card-engagement.png',
                ],
            ],
            'cta' => [
                'label' => 'Apply PULSE to My Banking Business',
                'href' => '#industry-form',
            ],
        ],
        'services' => [
            'label' => 'What We Deliver',
            'heading' => 'Complete HR support for banking businesses that need speed with discipline',
            'image' => 'assets/frontend/img/home/home-why-mirashka-hero.png',
            'image_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
            'image_secondary' => 'assets/frontend/img/compliance/cwi-services.png',
            'image_secondary_fallback' => 'assets/frontend/img/hraas/hraas-page-partner.png',
            'cards' => [
                ['title' => 'Banking Recruitment & Staffing', 'text' => 'Role mapping, sourcing, screening and closure support for branch, sales, credit, operations and customer-facing roles.', 'icon' => 'ri-user-search-line'],
                ['title' => 'Branch Workforce Planning', 'text' => 'Support for branch-wise manpower structure, hiring priority, role clarity and staffing readiness.', 'icon' => 'ri-building-line'],
                ['title' => 'Leadership Hiring', 'text' => 'Hiring support for branch managers, cluster heads, regional managers, business heads and CXO roles.', 'icon' => 'ri-user-star-line'],
                ['title' => 'HRaaS & HR Outsourcing', 'text' => 'Dedicated HR support for banking businesses that need structured HR without expanding internal HR overhead.', 'icon' => 'ri-customer-service-2-line'],
                ['title' => 'Payroll & Incentive Coordination', 'text' => 'Salary input coordination, attendance data, incentive records, reimbursement coordination and payroll communication.', 'icon' => 'ri-money-dollar-circle-line'],
                ['title' => 'Compliance & Documentation', 'text' => 'Employee handbooks, appointment letters, code of conduct, exit documents, policy manuals and compliance checklists.', 'icon' => 'ri-file-list-3-line'],
                ['title' => 'Employee Engagement & Retention', 'text' => 'Employee feedback, retention planning, performance communication, branch-level engagement and attrition reduction support.', 'icon' => 'ri-emotion-happy-line'],
                ['title' => 'HR Technology & Reporting', 'text' => 'Hiring dashboard, employee records dashboard, payroll status, compliance calendar and HR performance reports.', 'icon' => 'ri-computer-line'],
            ],
            'cta' => [
                'label' => 'Explore Banking HR Services',
                'href' => '#industry-form',
            ],
        ],
        'hiring_strategy' => [
            'section_id' => 'industry-hiring-strategy',
            'label' => 'Talent Strategy',
            'heading' => 'Banking hiring needs more than resumes. It needs trust-fit, process-fit and performance-fit.',
            'intro' => [
                'Banking roles often look similar on paper, but the real difference lies in customer handling, process discipline, communication maturity, local market understanding and ability to work with targets.',
                'Mirashka helps banking businesses define the role before starting the search. We map the reporting structure, customer segment, product exposure, required experience, salary range, incentive structure, local market conditions and expected outcomes.',
            ],
            'groups' => [
                [
                    'title' => 'Hiring Strategy Includes',
                    'items' => [
                        'Role and KRA definition',
                        'Location-wise hiring plan',
                        'Candidate sourcing strategy',
                        'Screening and shortlisting',
                        'Background and reference coordination support',
                        'Interview scheduling',
                        'Salary and expectation alignment',
                        'Offer and joining coordination',
                        'Replacement support where applicable',
                        'Weekly hiring dashboard',
                    ],
                ],
                [
                    'title' => 'Retention Strategy Includes',
                    'items' => [
                        'Early employee feedback',
                        'Joining experience review',
                        'Branch-level engagement inputs',
                        'Performance communication structure',
                        'Attrition reason analysis',
                        'Manager feedback system',
                        'Employee satisfaction surveys',
                        'Retention action planning',
                    ],
                ],
            ],
            'image' => 'assets/frontend/img/industries/healthcare-hiring-workforce-strategy.webp',
            'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
            'image_alt' => 'Banking hiring funnel with Trust Fit, Process Fit, Sales Fit and Culture Fit filters',
            'image_secondary' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
            'image_secondary_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
            'image_secondary_alt' => 'Banking hiring and retention strategy support',
            'cta' => [
                'label' => 'Build My Banking Talent Pipeline',
                'href' => '#industry-form',
            ],
        ],
        'compliance' => [
            'label' => 'Compliance & HR Operations',
            'heading' => 'Create documentation discipline across every employee touchpoint',
            'intro' => [
                'In banking, employee documentation and policy clarity are essential. Appointment letters, role expectations, conduct guidelines, exit documents, payroll inputs, attendance records and branch-level communication must be consistent.',
                'Mirashka helps banking businesses create structured documentation and HR operating practices that reduce confusion and improve leadership visibility.',
            ],
            'image' => 'assets/frontend/img/industries/healthcare-compliance-documentation-hr-operations.webp',
            'image_fallback' => 'assets/frontend/img/compliance/cwi-card-policy.png',
            'image_alt' => 'Banking compliance file, employee record dashboard and policy handbook',
            'cta' => 'Request Banking HR Documentation Review',
            'cta_href' => '#industry-form',
            'cards' => [
                [
                    'title' => 'Employee Documentation',
                    'text' => 'Appointment letters, joining forms, employee records, ID proofs, qualification documents and experience records.',
                    'icon' => 'ri-file-list-3-line',
                    'image' => 'assets/frontend/img/compliance/cwi-card-policy.png',
                ],
                [
                    'title' => 'Policy Framework',
                    'text' => 'Leave policy, attendance policy, code of conduct, expense policy, branch behavior guidelines and escalation process.',
                    'icon' => 'ri-book-2-line',
                    'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                    'active' => true,
                ],
                [
                    'title' => 'Payroll Coordination',
                    'text' => 'Attendance inputs, incentive data, reimbursement records, salary change data and payroll communication.',
                    'icon' => 'ri-money-dollar-circle-line',
                    'image' => 'assets/frontend/img/workforce/wfm-card-payroll.png',
                ],
                [
                    'title' => 'Compliance Readiness',
                    'text' => 'HR audit, documentation review, POSH readiness, workplace ethics and corrective action plan.',
                    'icon' => 'ri-shield-check-line',
                    'image' => 'assets/frontend/img/compliance/cwi-integrity.png',
                    'active' => true,
                ],
                [
                    'title' => 'Exit Management',
                    'text' => 'Resignation documentation, handover process, full and final coordination, exit feedback and clearance checklists.',
                    'icon' => 'ri-logout-box-r-line',
                    'image' => 'assets/frontend/img/compliance/cwi-services.png',
                ],
            ],
        ],
        'use_cases' => [
            'label' => 'Banking HR Support in Action',
            'heading' => 'Practical people solutions for banking growth challenges',
            'tags' => ['Faster Hiring', 'Cleaner Records', 'Stronger Leadership', 'Lower Attrition'],
            'cards' => [
                [
                    'tab_id' => 'branch-hiring',
                    'tab_label' => 'Branch Hiring',
                    'title' => 'Case Study 1: Branch Hiring Acceleration',
                    'pane_heading' => 'Location-wise sourcing and weekly hiring dashboard for relationship managers and sales officers.',
                    'challenge' => 'A branch-led banking business needed faster hiring for relationship managers and sales officers across multiple locations.',
                    'approach' => 'Created role clarity, location-wise sourcing plan, candidate screening process and weekly hiring dashboard.',
                    'outcome' => 'Faster shortlisting, better candidate fit and improved hiring visibility for management.',
                    'image' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
                    'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                ],
                [
                    'tab_id' => 'hr-docs',
                    'tab_label' => 'Documentation',
                    'title' => 'Case Study 2: HR Documentation Structuring',
                    'pane_heading' => 'Employee documentation checklist, policy templates and record structure.',
                    'challenge' => 'Employee files, joining documents and policy communication were scattered across branches.',
                    'approach' => 'Designed employee documentation checklist, policy templates, onboarding process and employee record structure.',
                    'outcome' => 'Cleaner employee records, reduced confusion and stronger HR control.',
                    'image' => 'assets/frontend/img/compliance/cwi-card-policy.png',
                    'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
                ],
                [
                    'tab_id' => 'leadership',
                    'tab_label' => 'Leadership',
                    'title' => 'Case Study 3: Leadership Hiring for Branch Expansion',
                    'pane_heading' => 'Leadership expectations, talent mapping and interview evaluation support.',
                    'challenge' => 'The company needed experienced branch leaders who could manage teams, targets and compliance discipline.',
                    'approach' => 'Defined leadership expectations, mapped relevant talent, screened candidates and supported interview evaluation.',
                    'outcome' => 'Improved leadership alignment and stronger branch expansion readiness.',
                    'image' => 'assets/frontend/img/leadership/ldr-board-advisory.png',
                    'image_fallback' => 'assets/frontend/img/workforce/wfm-hero.png',
                ],
                [
                    'tab_id' => 'attrition',
                    'tab_label' => 'Attrition',
                    'title' => 'Case Study 4: Attrition Review for Sales Team',
                    'pane_heading' => 'Hiring fit, onboarding experience and retention action planning.',
                    'challenge' => 'High attrition in frontline sales roles was affecting continuity and branch productivity.',
                    'approach' => 'Reviewed hiring fit, onboarding experience, manager communication, incentive clarity and employee feedback.',
                    'outcome' => 'Clearer retention actions and better understanding of attrition triggers.',
                    'image' => 'assets/frontend/img/hraas/hraas-card-engagement.png',
                    'image_fallback' => 'assets/frontend/img/compliance/cwi-services.png',
                ],
            ],
            'cta' => [
                'label' => 'Discuss a Similar Banking Case',
                'href' => '#industry-form',
            ],
        ],
        'form' => [
            'label' => 'Talk to Mirashka',
            'heading' => 'Build a stronger banking workforce with Mirashka',
            'content' => 'Share your banking HR requirement. Mirashka will help identify whether you need branch hiring, sales team hiring, leadership search, HRaaS, payroll coordination, policy documentation, compliance support or a complete people operating model.',
            'lead_type' => 'banking_hr_enquiry',
            'hidden_industry' => 'Banking — Financial Services',
            'segment_label' => 'Banking Business Type',
            'segment_name' => 'banking_business_type',
            'show_branches' => true,
            'show_call_time' => true,
            'message_label' => 'Key HR Challenge *',
            'message_placeholder' => 'Describe your key HR challenge…',
            'team_size_options' => [
                '1–25 employees',
                '26–100 employees',
                '101–500 employees',
                '500+ employees',
            ],
            'segments' => [
                'Bank',
                'NBFC',
                'Cooperative Bank',
                'Small Finance Institution',
                'Fintech Lending Business',
                'Wealth / Banking Distribution',
                'Other',
            ],
            'services' => [
                'Branch Hiring',
                'Sales Team Hiring',
                'Leadership Hiring',
                'HRaaS / HR Outsourcing',
                'Payroll Coordination',
                'Policy Documentation',
                'Compliance Audit',
                'POSH / Workplace Training',
                'Employee Engagement',
                'HR Technology',
                'Not Sure — Need Consultation',
            ],
            'submit' => 'Submit Banking HR Enquiry',
            'secondary_cta' => [
                'label' => 'Book 30-Minute Banking HR Consultation',
                'href' => 'https://calendly.com/elevateonemedia/30min',
            ],
            'image' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
            'image_fallback' => 'assets/frontend/img/hraas/hraas-page-partner.png',
        ],
        'faq_blog' => [
            'label' => 'Learn More',
            'heading' => 'Banking HR questions answered',
            'faqs' => [
                [
                    'question' => 'What banking roles can Mirashka hire for?',
                    'answer' => 'Mirashka can support hiring for relationship managers, branch managers, sales officers, customer service executives, credit officers, operations executives, compliance support and leadership roles.',
                ],
                [
                    'question' => 'Can Mirashka support branch-level hiring across locations?',
                    'answer' => 'Yes. Mirashka can create location-wise hiring plans and manage candidate sourcing, screening and coordination across branches.',
                ],
                [
                    'question' => 'Can Mirashka help with banking employee documentation?',
                    'answer' => 'Yes. Mirashka can support appointment letters, employee records, joining forms, HR policies, exit documents and compliance checklists.',
                ],
                [
                    'question' => 'Does Mirashka support payroll and incentive coordination?',
                    'answer' => 'Yes. Mirashka can help coordinate payroll inputs, attendance data, incentive records, reimbursement information and salary communication.',
                ],
                [
                    'question' => 'Can Mirashka provide HRaaS for NBFCs and small finance businesses?',
                    'answer' => 'Yes. Mirashka HRaaS is suitable for NBFCs, fintech lenders, cooperative banks and growing financial institutions that need structured HR support.',
                ],
            ],
            'cta' => [
                'label' => 'Read Banking HR Insights',
                'href' => '/blog',
            ],
            'image' => 'assets/frontend/img/industries/industry-form-consultant.webp',
            'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
        ],
    ],
];
