<?php

return [
    'author' => 'Mirashka',
    'categories' => [
        ['id' => 1, 'name' => 'HRaaS', 'count' => 2],
        ['id' => 2, 'name' => 'Compliance', 'count' => 1],
        ['id' => 3, 'name' => 'HR Strategy', 'count' => 1],
        ['id' => 4, 'name' => 'Employee Experience', 'count' => 1],
        ['id' => 5, 'name' => 'Leadership Hiring', 'count' => 1],
        ['id' => 6, 'name' => 'HR Technology', 'count' => 1],
    ],
    'tags' => [
        ['id' => 1, 'name' => 'Startups'],
        ['id' => 2, 'name' => 'MSMEs'],
        ['id' => 3, 'name' => 'Payroll'],
        ['id' => 4, 'name' => 'Compliance'],
        ['id' => 5, 'name' => 'Leadership'],
        ['id' => 6, 'name' => 'HR Tech'],
    ],
    'posts' => [
        [
            'id' => 1,
            'slug' => 'hraas-game-changer-startup-msme',
            'date' => '2025-01-15',
            'category' => 'HRaaS',
            'image' => 'https://mirashka.co.in/wp-content/uploads/2025/02/HR-Outsourcing.png',
            'image_alt' => 'HR as a Service for startups and MSMEs',
            'title' => 'HRaaS - The Game-Changer Every Startup & MSME Needs to Scale Smartly',
            'paragraphs' => [
                'In today\'s fast-paced business environment, startups and MSMEs are under constant pressure to scale quickly while keeping costs low. This is where <strong>HRaaS (Human Resource as a Service)</strong> emerges as a transformative solution. Traditional HR departments often become expensive overhead for small businesses, but with HRaaS, companies can access <strong>on-demand HR expertise</strong>, tailored to their exact needs.',
                'From <strong>hiring and onboarding</strong> to <strong>payroll management, compliance audits,</strong> and <strong>employee engagement programs</strong>, HRaaS offers <strong>end-to-end HR support</strong> at a fraction of the cost of an in-house team. For startups navigating uncertain growth or MSMEs juggling lean operations, this flexibility is invaluable.',
                'Additionally, with experts managing your <strong>compliance checks, POSH training, employee handbook creation,</strong> and <strong>performance management</strong>, founders can focus on what they do best — growing their business. HRaaS is not just a service; it\'s a strategic enabler that ensures people processes are agile, compliant, and future-ready.',
                '<strong>Looking to scale smartly with expert HR support? Contact Mirashka today to explore tailored HRaaS solutions for your business.</strong>',
            ],
        ],
        [
            'id' => 2,
            'slug' => 'compliance-mistakes-cost-business',
            'date' => '2025-02-10',
            'category' => 'Compliance',
            'image' => 'https://mirashka.co.in/wp-content/uploads/2024/06/compliance-and-risk-assessment.webp',
            'image_alt' => 'HR compliance and risk assessment',
            'title' => 'Compliance Mistakes That Can Cost Your Business Big — And How to Avoid Them',
            'paragraphs' => [
                'For many startups and MSMEs, compliance feels like a daunting maze. From <strong>labor law compliance</strong> and <strong>payroll statutory filings</strong> to <strong>workplace safety</strong> and <strong>POSH mandates</strong>, the risks of non-compliance are real and costly.',
                'Common mistakes like incomplete <strong>employee documentation</strong>, outdated <strong>policies</strong>, or improper <strong>termination processes</strong> can lead to hefty fines, legal disputes, and even reputational damage. This is why <strong>proactive HR compliance audits</strong> are not optional — they\'re essential.',
                'Mirashka\'s <strong>Compliance &amp; Workplace Integrity Solutions</strong> cover everything from <strong>employee handbook creation</strong> to <strong>workplace safety audits</strong>, ensuring your business stays legally sound and employee-friendly. Whether it\'s setting up <strong>POSH training</strong> or ensuring <strong>labour law compliance</strong> across states, we make sure your HR backbone is strong.',
                '<strong>Don\'t let compliance mistakes derail your growth. Let Mirashka handle your HR compliance, so you can focus on success.</strong>',
            ],
        ],
        [
            'id' => 3,
            'slug' => 'hiring-vs-outsourcing-hr',
            'date' => '2025-03-05',
            'category' => 'HR Strategy',
            'image' => 'https://mirashka.co.in/wp-content/uploads/2024/06/expert-legal-and-HR-consultation.webp',
            'image_alt' => 'HR outsourcing and expert HR consultation',
            'title' => 'Hiring vs Outsourcing HR - What\'s Right for Your Growing Business?',
            'paragraphs' => [
                'As businesses grow, HR management becomes more complex. Should you build an in-house team or opt for <strong>HR outsourcing</strong> through <strong>HRaaS</strong>? For startups and MSMEs, the answer often lies in <strong>flexibility, expertise, and cost-efficiency.</strong>',
                'Building an internal HR team means recruitment, training, and overhead costs, plus the challenge of keeping up with <strong>labour laws, compliance requirements,</strong> and <strong>best practices.</strong> In contrast, <strong>outsourcing HR to Mirashka</strong> gives you instant access to <strong>expert HR consultants, compliance experts,</strong> and <strong>legal advisors</strong> — all without permanent costs.',
                'Outsourcing covers everything: <strong>hiring, onboarding, payroll management, performance reviews, compliance audits,</strong> and even <strong>employee engagement programs.</strong> With <strong>remote HR solutions,</strong> you get support wherever you are, keeping your business agile and compliant.',
                '<strong>Explore how Mirashka\'s HRaaS can give you flexible, expert HR support tailored to your needs. Let\'s talk.</strong>',
            ],
        ],
        [
            'id' => 4,
            'slug' => 'employee-experience-matters-2025',
            'date' => '2025-04-12',
            'category' => 'Employee Experience',
            'image' => 'https://mirashka.co.in/wp-content/uploads/2025/02/employee-engagement.png',
            'image_alt' => 'Employee engagement and workplace experience',
            'title' => 'Why Employee Experience Matters More Than Ever in 2025',
            'paragraphs' => [
                'In today\'s workplace, employees expect more than just a salary. They want <strong>purpose, growth, flexibility, and recognition.</strong> For startups and MSMEs looking to attract and retain top talent, <strong>employee experience</strong> is a game-changer.',
                'Mirashka\'s <strong>Employee Engagement Solutions</strong> focus on creating a culture of <strong>recognition, feedback, and growth.</strong> From <strong>structured onboarding</strong> and <strong>career development programs</strong> to <strong>employee surveys</strong> and <strong>reward &amp; recognition frameworks,</strong> we design experiences that make employees feel valued.',
                'Additionally, <strong>POSH training</strong> and <strong>workplace ethics programs</strong> foster safe, inclusive environments, while <strong>performance management systems</strong> provide clear growth paths. This holistic approach to <strong>employee experience</strong> drives <strong>higher retention, better engagement,</strong> and <strong>stronger employer branding.</strong>',
                '<strong>Ready to create a workplace your employees love? Partner with Mirashka for people-first HR strategies.</strong>',
            ],
        ],
        [
            'id' => 5,
            'slug' => 'leadership-hiring-first-time-founders',
            'date' => '2025-05-08',
            'category' => 'Leadership Hiring',
            'image' => 'https://mirashka.co.in/wp-content/uploads/2024/06/executive-search-1.png',
            'image_alt' => 'Executive search and leadership hiring',
            'title' => 'Leadership Hiring for First-Time Founders — Secrets to Building Your Dream Team',
            'paragraphs' => [
                'For first-time founders, hiring leaders is both critical and daunting. A strong leadership team shapes your culture, strategy, and scalability. But how do you find leaders who align with your vision and thrive in startup chaos?',
                'Mirashka\'s <strong>Executive Search &amp; Leadership Hiring</strong> service specializes in helping founders identify <strong>growth-ready leaders</strong>. We don\'t just match resumes — we evaluate <strong>cultural fit, leadership agility, and future-readiness</strong>. Whether you need a <strong>COO to build processes</strong> or a <strong>Chief People Officer</strong> to drive culture, we find leaders who fit.',
                'We also guide founders in <strong>structuring leadership roles</strong>, defining <strong>KPIs</strong>, and setting up <strong>succession planning frameworks</strong> to future-proof the leadership bench.',
                '<strong>Need visionary leaders for your startup? Let Mirashka help you hire right from the top. Contact us today.</strong>',
            ],
        ],
        [
            'id' => 6,
            'slug' => 'hr-tech-payroll-compliance-msmes',
            'date' => '2025-05-20',
            'category' => 'HR Technology',
            'image' => 'https://mirashka.co.in/wp-content/uploads/2025/02/HR-Technology-solution.png',
            'image_alt' => 'HR technology for payroll and compliance',
            'title' => 'How HR Tech Transforms Payroll, Compliance & Performance Management for MSMEs',
            'paragraphs' => [
                'Manual HR processes slow down growing businesses. From <strong>payroll errors</strong> to <strong>compliance gaps</strong> and <strong>delayed performance reviews</strong>, outdated systems cost time and money. This is why HR tech adoption is no longer a luxury — it\'s a necessity.',
                'Mirashka\'s <strong>HR Technology Solutions</strong> bring <strong>automation, real-time reporting, and seamless workflows</strong> to MSMEs. Our <strong>digital payroll processing, compliance dashboards, and performance management systems</strong> ensure that founders and HR managers have <strong>full visibility and control</strong> at all times.',
                'With intuitive tools for <strong>leave management, employee records, engagement surveys, and HR audits</strong>, Mirashka helps businesses <strong>reduce manual errors, improve compliance accuracy, and speed up HR processes</strong>.',
                '<strong>Want to future-proof your HR with technology? Let Mirashka set up your digital HR ecosystem. Get started today.</strong>',
            ],
        ],
    ],
];
