<?php

/**
 * Mirashka HR case studies — content + image seed definitions.
 *
 * @return array<int, array<string, mixed>>
 */
return [
    // Case Study 1 — EdTech (existing)
    [
        'slug' => 'edtech-talent-success-vlearn360',
        'image_set' => 'edtech-case-study',
        'download_sources' => false,
        'main_images' => [
            'edtech-cs-featured.png' => 'edtech-cs-featured.webp',
            'edtech-cs-overview.png' => 'edtech-cs-overview.webp',
            'edtech-cs-team.png' => 'edtech-cs-team.webp',
            'edtech-cs-challenge.png' => 'edtech-cs-challenge.webp',
        ],
        'gallery_images' => [
            'edtech-cs-hiring.png' => 'edtech-cs-hiring.webp',
            'edtech-cs-results.png' => 'edtech-cs-results.webp',
            'edtech-cs-overview.png' => 'edtech-cs-platform.webp',
        ],
        'title' => 'Fast-Tracking Talent Success for a Rapidly Scaling EdTech Innovator',
        'client_name' => 'Early-Stage Education Technology Start-Up',
        'industry' => 'EdTech & Online Learning',
        'reach' => '120+ hires in 83 days',
        'short_description' => 'A dynamic online learning start-up built VLearn360, a proprietary real-time interactive learning platform, designed to enhance virtual education experiences for students across India. Despite securing significant funding from angel investors, the start-up faced persistent hiring challenges, especially for permanent roles across technology, content development, sales, and student support teams. As they prepared for rapid national expansion, they urgently required an agile, experienced HR partner who could streamline recruitment, establish standardized hiring frameworks, and reduce over-reliance on fragmented external recruitment vendors.',
        'challenge' => '<ul><li><strong>No Central Talent Acquisition Team:</strong> Each department handled hiring independently, causing inconsistencies and delays.</li><li><strong>Process Fragmentation:</strong> No unified recruitment policy or standardized interview process existed.</li><li><strong>Heavy Reliance on Agencies:</strong> Nearly 65% of hiring was outsourced to multiple uncoordinated agencies.</li><li><strong>Under-Resourced HR Function:</strong> Internal talent acquisition operated at just 30% of required capacity.</li><li><strong>Urgent Hiring Needs:</strong> The business needed 120+ professionals within 90 days for product launches and regional expansion.</li></ul>',
        'solution' => '<p>Mirashka stepped in as the exclusive Recruitment Process Outsourcing (RPO) partner, providing a comprehensive hiring transformation strategy that included:</p><ul><li><strong>Central Talent Hub:</strong> Single-window HR partner for hiring across tech, sales, operations, content, and support.</li><li><strong>Standardized Process Implementation:</strong> Consistent hiring workflows from requisition to onboarding.</li><li><strong>Cost-Effective Bulk Hiring:</strong> Bulk hiring strategies cutting average cost-per-hire by 38%.</li><li><strong>Real-Time Performance Reporting:</strong> Custom dashboards for time-to-fill and offer acceptance rates.</li><li><strong>Employer Branding Support:</strong> Refined employer brand messaging for candidates.</li><li><strong>Vendor Rationalization:</strong> Vendor Scorecard System increasing direct sourcing by 50%.</li></ul>',
        'strategy' => '<p>Mirashka built a scalable talent engine for the client, turning fragmented hiring into a cost-efficient, transparent, and future-ready process.</p><p>By delivering agility, expertise, and structure, Mirashka empowered this fast-growing EdTech innovator to achieve aggressive growth goals while maintaining high-quality hiring standards.</p>',
        'results' => '<p><strong>120 positions closed in 83 days</strong>, spanning technology, content &amp; academics, and sales &amp; student success roles.</p><ul><li><strong>42% reduction</strong> in recruitment costs through centralized RPO.</li><li>External vendor dependency reduced from <strong>65% to 22%</strong>.</li><li><strong>Time-to-Hire</strong> reduced from 42 days to 17 days for high-priority roles.</li><li><strong>34% jump</strong> in offer acceptance rates.</li><li><strong>Process Standardization:</strong> Central hiring playbook created for future scaling.</li></ul>',
        'impact_highlights' => '120+ roles in 83 days. 42% recruitment cost reduction. Vendor dependency 65% to 22%. Time-to-hire 42 to 17 days. 34% higher offer acceptance. Central hiring playbook delivered.',
        'media_coverage' => '<p><strong>Looking to build your workforce with speed, cost efficiency, and quality?</strong> Let Mirashka design your hiring success story too.</p>',
    ],

    // Case Study 2 — Liv India Group
    [
        'slug' => 'liv-india-sales-performance',
        'image_set' => 'liv-india',
        'download_sources' => true,
        'source_urls' => [
            'team.jpg' => 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1600&q=80',
            'challenge.jpg' => 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=1600&q=80',
        ],
        // featured.png & overview.png committed under database/seeders/images/liv-india/sources/
        'main_images' => [
            'featured.png' => 'liv-india-featured.webp',
            'overview.png' => 'liv-india-overview.webp',
            'team.jpg' => 'liv-india-team.webp',
            'challenge.jpg' => 'liv-india-challenge.webp',
        ],
        'gallery_images' => [
            'team.jpg' => 'liv-india-gallery-sales.webp',
            'overview.png' => 'liv-india-gallery-automotive.webp',
            'featured.png' => 'liv-india-gallery-growth.webp',
        ],
        'title' => 'Reigniting Sales Performance for Liv India Group',
        'client_name' => 'Liv India Group (Lords of Detailing & Speed Car Wash)',
        'industry' => 'Automotive Aftercare & Car Detailing Services',
        'reach' => '42% sales productivity increase',
        'short_description' => 'Liv India Group, a leader in automotive detailing and car care, operates renowned brands like Lords of Detailing and Speed Car Wash across India. Despite strong brand equity, their seven-person sales team was underperforming, leading to stagnant revenue growth. With expansion goals set for the next fiscal year, they needed to transform the sales team into a proactive, high-energy force capable of driving lead conversions, franchise sales, and corporate partnerships.',
        'challenge' => '<ul><li><strong>Complacency &amp; Low Motivation:</strong> The team lacked urgency, ownership, and hunger to hit targets.</li><li><strong>No Clear KPIs:</strong> No quarterly or individual performance metrics aligned to business goals.</li><li><strong>Disconnected Management:</strong> Infrequent performance reviews and no structured feedback loops.</li><li><strong>Lack of Process Clarity:</strong> No weekly activity reporting, sales funnel visibility, or consistent CRM usage.</li><li><strong>No Incentive Structure:</strong> No reward mechanism for high performers.</li><li><strong>Training Gaps:</strong> Team not equipped with updated sales scripts and objection-handling techniques.</li></ul>',
        'solution' => '<p>Mirashka designed and implemented a 360° Sales Performance Transformation Program aligned with revenue targets and long-term sales culture enhancement.</p><ul><li><strong>Defining Smart KPIs:</strong> Individual and team KPIs aligned with revenue, franchise onboarding, and B2B partnership goals.</li><li><strong>Weekly Sales Pulse Meetings:</strong> Structured huddles to review performance and pipeline movement.</li><li><strong>One-to-One Performance Coaching:</strong> Biweekly review sessions with personalized feedback and skill development.</li><li><strong>Activity Tracking &amp; CRM Discipline:</strong> Simplified weekly activity reports linked to CRM data.</li><li><strong>Dynamic Incentive Framework:</strong> Performance-based incentives rewarding individual and team excellence.</li><li><strong>Training &amp; Roleplay Labs:</strong> Product knowledge, consultative selling, and customer profiling workshops.</li><li><strong>Management Alignment:</strong> Trained sales managers as coaches with data-driven discussions.</li></ul>',
        'strategy' => '<p>Mirashka embedded a culture of accountability, process discipline, and proactive selling—positioning Liv India\'s sales team as a growth engine for aggressive expansion plans.</p>',
        'results' => '<ul><li><strong>Sales Productivity Increased by 42%</strong> with clearer KPIs and stronger management connection.</li><li><strong>Quarterly Sales Target Exceeded by 28%</strong> in the first quarter post-intervention.</li><li><strong>Franchise Inquiry Conversion Improved by 36%</strong> with better scripts and consultative selling.</li><li><strong>Team Motivation Score Jumped by 60%</strong> post-incentive launch.</li><li><strong>Process Standardization Achieved</strong> with mandatory, streamlined CRM usage.</li><li><strong>Stronger Sales Culture Embedded</strong> through coaching and leadership involvement.</li></ul>',
        'impact_highlights' => '42% sales productivity increase. 28% above quarterly target. 36% better franchise conversions. 60% motivation score jump. CRM and sales culture standardized.',
        'media_coverage' => '<p><strong>Looking to transform your sales team from stagnant to unstoppable?</strong> Let Mirashka do for your business what we did for Liv India Group.</p>',
    ],

    // Case Study 3 — JYogi Technologies
    [
        'slug' => 'jyogi-employee-morale-engagement',
        'image_set' => 'jyogi-tech',
        'download_sources' => true,
        'source_urls' => [
            'featured.jpg' => 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1600&q=80',
            'overview.jpg' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1600&q=80',
            'team.jpg' => 'https://images.unsplash.com/photo-1600880292089-90a7e086ee0c?w=1600&q=80',
            'challenge.jpg' => 'https://images.unsplash.com/photo-1542744173-8e7e53463bb0?w=1600&q=80',
        ],
        'main_images' => [
            'featured.jpg' => 'jyogi-featured.webp',
            'overview.jpg' => 'jyogi-overview.webp',
            'team.jpg' => 'jyogi-team.webp',
            'challenge.jpg' => 'jyogi-challenge.webp',
        ],
        'gallery_images' => [
            'team.jpg' => 'jyogi-gallery-engagement.webp',
            'overview.jpg' => 'jyogi-gallery-office.webp',
            'featured.jpg' => 'jyogi-gallery-culture.webp',
        ],
        'title' => 'Boosting Employee Morale & Engagement at JYogi Technologies',
        'client_name' => 'JYogi Technologies Private Limited',
        'industry' => 'IT Services & Software Solutions',
        'reach' => '62% morale score improvement',
        'short_description' => 'JYogi Technologies, a rapidly evolving IT services company, had built a strong reputation for delivering cutting-edge software solutions. While client success was impressive, internal employee morale was dipping and management sensed a disconnect between leadership and the workforce. They wanted an unbiased HR partner to uncover real issues and rebuild a high-energy, motivated culture ahead of expansion plans.',
        'challenge' => '<ul><li><strong>Low Employee Engagement:</strong> Employees disconnected from company vision with lower enthusiasm in projects.</li><li><strong>Communication Barriers:</strong> Feedback rarely flowed upwards, leaving management in the dark.</li><li><strong>Recognition Gap:</strong> Employees felt undervalued with limited recognition avenues.</li><li><strong>Unclear Growth Path:</strong> Lack of visibility into career progression.</li><li><strong>Remote Work Strain:</strong> Hybrid model left many employees feeling isolated.</li></ul>',
        'solution' => '<p>Mirashka launched a 360° Employee Morale Revamp Program blending confidential insight gathering, leadership coaching, and tangible action plans.</p><ul><li><strong>Confidential Employee Sentiment Analysis:</strong> One-on-one interviews across all teams.</li><li><strong>Morale Health Scorecard:</strong> Customized ranking of satisfaction, growth clarity, and belonging.</li><li><strong>Management Insight Report:</strong> Anonymized feedback with prioritized action items.</li><li><strong>Recognition &amp; Appreciation Framework:</strong> Monthly programs celebrating performance and values.</li><li><strong>Leadership Engagement Training:</strong> Active listening and empathetic leadership coaching.</li><li><strong>Feedback Loops &amp; Pulse Checks:</strong> Quarterly anonymous employee surveys.</li><li><strong>Career Pathing &amp; Upskilling Roadmaps:</strong> Progression frameworks for every department.</li></ul>',
        'strategy' => '<p>Mirashka transformed internal culture into a more transparent, appreciative, and future-focused environment with long-term engagement practices as core pillars.</p>',
        'results' => '<ul><li><strong>Employee Morale Score Improved by 62%</strong> six months after intervention.</li><li><strong>Leadership-Employee Connect Strengthened</strong> through regular feedback sessions.</li><li><strong>85% of employees</strong> cited better appreciation and recognition.</li><li><strong>90%+ participation</strong> in pulse surveys showing renewed ownership.</li><li><strong>78% of employees</strong> saw clearer career progression and development opportunities.</li></ul>',
        'impact_highlights' => '62% morale improvement. Stronger leadership connect. 85% better recognition sentiment. 90%+ survey participation. 78% clearer career paths.',
        'media_coverage' => '<p><strong>Struggling with low morale in your team?</strong> Let Mirashka help you rebuild an engaged, motivated, and high-performance workforce.</p>',
    ],

    // Category 1 — FinTech compliance
    [
        'slug' => 'fintech-hr-compliance-startup',
        'image_set' => 'fintech-compliance',
        'download_sources' => true,
        'source_urls' => [
            'featured.jpg' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1600&q=80',
            'overview.jpg' => 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1600&q=80',
            'team.jpg' => 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=1600&q=80',
            'challenge.jpg' => 'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=1600&q=80',
        ],
        'main_images' => [
            'featured.jpg' => 'fintech-featured.webp',
            'overview.jpg' => 'fintech-overview.webp',
            'team.jpg' => 'fintech-team.webp',
            'challenge.jpg' => 'fintech-challenge.webp',
        ],
        'gallery_images' => [
            'overview.jpg' => 'fintech-gallery-legal.webp',
            'team.jpg' => 'fintech-gallery-team.webp',
            'featured.jpg' => 'fintech-gallery-data.webp',
        ],
        'title' => 'Ensuring Compliance Confidence for a FinTech Startup',
        'client_name' => 'Fast-Growing FinTech Startup (35 Employees)',
        'industry' => 'FinTech (Startup)',
        'reach' => '70% legal risk reduction',
        'short_description' => 'A fast-growing FinTech startup faced compliance confusion with employment contracts, leave policies, and termination procedures as they expanded across multiple states. With founders focused on product development and investor relations, HR compliance was overlooked—leaving the company vulnerable to legal risks.',
        'challenge' => '<ul><li><strong>Ambiguous employment contracts</strong> with missing statutory clauses.</li><li><strong>No proper leave and attendance policy.</strong></li><li><strong>Misinterpretation of termination clauses</strong> under Shops &amp; Establishment Act.</li><li><strong>Founders lacked real-time legal guidance,</strong> delaying critical decisions.</li></ul>',
        'solution' => '<ul><li><strong>On-demand legal consultations</strong> clarifying compliance for each state.</li><li><strong>Redrafted employment contracts</strong> aligned with labour laws and best practices.</li><li><strong>Founder-friendly Compliance Guide</strong> with step-by-step HR legal checklists.</li><li><strong>Monthly legal review calendar</strong> to anticipate compliance risks proactively.</li></ul>',
        'strategy' => '<p>Mirashka delivered Expert Legal &amp; HR Consultations to turn compliance from a blind spot into a structured, founder-friendly operating rhythm.</p>',
        'results' => '<ul><li><strong>Reduced legal risk exposure by 70%.</strong></li><li><strong>Saved founders 10+ hours per month</strong> by eliminating legal guesswork.</li><li><strong>Streamlined onboarding and exits</strong> with legal consistency across all hires.</li></ul>',
        'impact_highlights' => '70% lower legal risk. 10+ founder hours saved monthly. Consistent onboarding and exit compliance.',
        'media_coverage' => '<p><strong>Need compliance confidence as you scale?</strong> Mirashka keeps your FinTech HR legally sound and founder-focused.</p>',
    ],

    // Category 1 — E-commerce policies
    [
        'slug' => 'ecommerce-hr-policy-documentation',
        'image_set' => 'ecommerce-policies',
        'download_sources' => true,
        'source_urls' => [
            'featured.jpg' => 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=1600&q=80',
            'overview.jpg' => 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=1600&q=80',
            'team.jpg' => 'https://images.unsplash.com/photo-1551836022-d5d88cd4d0b3?w=1600&q=80',
            'challenge.jpg' => 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=1600&q=80',
        ],
        'main_images' => [
            'featured.jpg' => 'ecommerce-featured.webp',
            'overview.jpg' => 'ecommerce-overview.webp',
            'team.jpg' => 'ecommerce-team.webp',
            'challenge.jpg' => 'ecommerce-challenge.webp',
        ],
        'gallery_images' => [
            'overview.jpg' => 'ecommerce-gallery-ops.webp',
            'team.jpg' => 'ecommerce-gallery-handbook.webp',
            'featured.jpg' => 'ecommerce-gallery-retail.webp',
        ],
        'title' => 'Structuring Policies for a Fast-Scaling E-commerce SME',
        'client_name' => 'Pan-India E-commerce Business (120 Employees)',
        'industry' => 'E-commerce (MSME)',
        'reach' => '40% fewer employee grievances',
        'short_description' => 'An e-commerce business with pan-India operations lacked formal HR policies, leading to inconsistent handling of leave, working hours, remote work norms, and disciplinary actions. This drove frequent grievances and rising attrition due to perceived unfair treatment.',
        'challenge' => '<ul><li><strong>No comprehensive employee handbook.</strong></li><li><strong>Managers interpreted policies differently</strong> across locations.</li><li><strong>Employees lacked clarity</strong> on benefits, holidays, and disciplinary measures.</li><li><strong>New joiners received no structured policy orientation.</strong></li></ul>',
        'solution' => '<ul><li><strong>Customized Employee Handbook</strong> aligned with labour laws and company culture.</li><li><strong>Standardized policies</strong> for leave, work hours, probation, rewards, and separation.</li><li><strong>Digital policy acknowledgment</strong> during onboarding.</li><li><strong>Policy orientation workshops</strong> for managers on uniform application.</li></ul>',
        'strategy' => '<p>Mirashka delivered Policy &amp; Documentation Excellence to create one clear rulebook for a distributed e-commerce workforce.</p>',
        'results' => '<ul><li><strong>Employee grievances reduced by 40%.</strong></li><li><strong>Faster dispute resolution</strong> with documented, accessible policies.</li><li><strong>35% improvement</strong> in new joiner onboarding satisfaction.</li></ul>',
        'impact_highlights' => '40% fewer grievances. Faster disputes resolution. 35% better onboarding clarity.',
        'media_coverage' => '<p><strong>Scaling fast without HR policy chaos?</strong> Mirashka builds handbooks your teams actually follow.</p>',
    ],

    // Category 1 — Manufacturing compliance
    [
        'slug' => 'manufacturing-hr-compliance-audit',
        'image_set' => 'manufacturing-compliance',
        'download_sources' => true,
        'source_urls' => [
            'featured.jpg' => 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1600&q=80',
            'overview.jpg' => 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=1600&q=80',
            'team.jpg' => 'https://images.unsplash.com/photo-1565793298595-6a879b1cbcca?w=1600&q=80',
            'challenge.jpg' => 'https://images.unsplash.com/photo-1533117874729-ce7b390a397b?w=1600&q=80',
        ],
        'main_images' => [
            'featured.jpg' => 'manufacturing-featured.webp',
            'overview.jpg' => 'manufacturing-overview.webp',
            'team.jpg' => 'manufacturing-team.webp',
            'challenge.jpg' => 'manufacturing-challenge.webp',
        ],
        'gallery_images' => [
            'featured.jpg' => 'manufacturing-gallery-factory.webp',
            'overview.jpg' => 'manufacturing-gallery-safety.webp',
            'team.jpg' => 'manufacturing-gallery-compliance.webp',
        ],
        'title' => 'Proactive Risk Management for a Manufacturing MSME',
        'client_name' => 'Mid-Sized Industrial Manufacturing Firm (85 Employees)',
        'industry' => 'Manufacturing (MSME)',
        'reach' => '100% compliant employee files in 60 days',
        'short_description' => 'A mid-sized industrial manufacturing firm had grown organically without formal HR audits or compliance reviews. When the factory underwent a surprise labour inspection, documentation gaps were exposed, risking financial penalties and reputational damage.',
        'challenge' => '<ul><li><strong>Incomplete employee files</strong> (missing KYC, PF, and ESI forms).</li><li><strong>No formal Health &amp; Safety policy.</strong></li><li><strong>POSH Committee not constituted</strong> despite 10+ female employees.</li><li><strong>Outdated standing orders</strong> and employment terms.</li></ul>',
        'solution' => '<ul><li><strong>Comprehensive HR compliance audit.</strong></li><li><strong>Compliance Heatmap</strong> highlighting high-risk areas.</li><li><strong>Standardized employee documentation</strong> across departments.</li><li><strong>Workplace safety policies</strong> tailored to factory operations.</li><li><strong>Compliant POSH Committee</strong> with mandatory training.</li></ul>',
        'strategy' => '<p>Mirashka delivered Compliance &amp; Risk Assessments to shift the client from reactive firefighting to proactive, dashboard-driven compliance.</p>',
        'results' => '<ul><li><strong>Cleared follow-up labour inspection</strong> without penalties.</li><li><strong>100% compliance in employee files</strong> within 60 days.</li><li><strong>Living compliance dashboard</strong> for leadership visibility.</li><li><strong>Proactive compliance culture</strong> across HR and Admin teams.</li></ul>',
        'impact_highlights' => 'Passed labour inspection. 100% file compliance in 60 days. Compliance dashboard live. Proactive HR culture built.',
        'media_coverage' => '<p><strong>Worried about your next labour inspection?</strong> Mirashka builds factory-ready compliance you can prove.</p>',
    ],

    // Category 1 — IT POSH
    [
        'slug' => 'it-startup-posh-workplace-ethics',
        'image_set' => 'it-posh',
        'download_sources' => true,
        'source_urls' => [
            'featured.jpg' => 'https://images.unsplash.com/photo-1573164713714-d95e436ab8d6?w=1600&q=80',
            'overview.jpg' => 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1600&q=80',
            'team.jpg' => 'https://images.unsplash.com/photo-1521737711867-e3b973750110?w=1600&q=80',
            'challenge.jpg' => 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=1600&q=80',
        ],
        'main_images' => [
            'featured.jpg' => 'it-posh-featured.webp',
            'overview.jpg' => 'it-posh-overview.webp',
            'team.jpg' => 'it-posh-team.webp',
            'challenge.jpg' => 'it-posh-challenge.webp',
        ],
        'gallery_images' => [
            'team.jpg' => 'it-posh-gallery-training.webp',
            'overview.jpg' => 'it-posh-gallery-inclusive.webp',
            'featured.jpg' => 'it-posh-gallery-safe.webp',
        ],
        'title' => 'Cultivating a Respectful Workplace for an IT Startup',
        'client_name' => 'Fast-Growing IT Startup (45 Employees)',
        'industry' => 'IT Services (Startup)',
        'reach' => '100% POSH training completion in 30 days',
        'short_description' => 'As a young, fast-growing IT startup, leadership wanted a modern, inclusive, and safe workplace—especially with more women joining the team. Employees were unclear about acceptable conduct, reporting mechanisms, and the company\'s stance on workplace harassment.',
        'challenge' => '<ul><li><strong>No formal POSH policy.</strong></li><li><strong>Employees unaware</strong> of rights and responsibilities under POSH.</li><li><strong>Managers lacked training</strong> on handling complaints sensitively and legally.</li><li><strong>No Internal Complaints Committee (ICC)</strong> formed.</li></ul>',
        'solution' => '<ul><li><strong>POSH Policy</strong> aligned with legal mandates and company culture.</li><li><strong>Mandatory POSH Awareness Training</strong> with case studies and roleplays.</li><li><strong>Internal Complaints Committee (ICC)</strong> with orientation training.</li><li><strong>Confidential reporting mechanisms</strong> with escalation matrices.</li><li><strong>POSH acknowledgment integrated into onboarding.</strong></li></ul>',
        'strategy' => '<p>Mirashka delivered Workplace Ethics &amp; Prevention Training (POSH) to embed safety and inclusion into the startup\'s growth DNA.</p>',
        'results' => '<ul><li><strong>100% of employees completed POSH training</strong> within 30 days.</li><li><strong>ICC trained and functional.</strong></li><li><strong>Improved employee confidence</strong> in workplace safety per engagement surveys.</li><li><strong>Founders gained peace of mind</strong> on legal compliance and inclusive culture.</li></ul>',
        'impact_highlights' => '100% POSH training in 30 days. Functional ICC. Higher safety confidence. Legally compliant inclusive workplace.',
        'media_coverage' => '<p><strong>Building a startup culture that is safe by design?</strong> Mirashka makes POSH compliance practical and people-first.</p>',
    ],

    // Case Study 5 — Workplace bullying
    [
        'slug' => 'workplace-bullying-safe-environment',
        'image_set' => 'workplace-bullying',
        'download_sources' => true,
        'source_urls' => [
            'featured.jpg' => 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=1600&q=80',
            'overview.jpg' => 'https://images.unsplash.com/photo-1581092160562-40aa08ed65c8?w=1600&q=80',
            'team.jpg' => 'https://images.unsplash.com/photo-1556761175-b413da4baf72?w=1600&q=80',
            'challenge.jpg' => 'https://images.unsplash.com/photo-1551836022-d5d88cd4d0b3?w=1600&q=80',
        ],
        'main_images' => [
            'featured.jpg' => 'bullying-featured.webp',
            'overview.jpg' => 'bullying-overview.webp',
            'team.jpg' => 'bullying-team.webp',
            'challenge.jpg' => 'bullying-challenge.webp',
        ],
        'gallery_images' => [
            'team.jpg' => 'bullying-gallery-safety.webp',
            'overview.jpg' => 'bullying-gallery-policy.webp',
            'featured.jpg' => 'bullying-gallery-factory.webp',
        ],
        'title' => 'Resolving Workplace Bullying & Restoring a Safe Work Environment',
        'client_name' => 'Confidential Mid-Sized Manufacturing Company',
        'industry' => 'Manufacturing & Industrial Services',
        'reach' => 'Risk-free separation in 14 days',
        'short_description' => 'A reputed manufacturing firm with over 150 employees faced an escalating crisis caused by an aggressive employee with threatening behavior toward supervisors and colleagues. After verbal threats and a police complaint by the supervisor, the employer\'s HR infrastructure had no formal disciplinary policy, grievance process, or documentation framework to handle the incident objectively.',
        'challenge' => '<ul><li><strong>Risk of Legal Repercussions:</strong> Immediate termination could trigger wrongful termination claims.</li><li><strong>Toxic Work Environment:</strong> Allowing the employee to stay eroded morale and collaboration.</li><li><strong>Absence of Formal Processes:</strong> No disciplinary policies or documented counseling for legal defensibility.</li><li><strong>Supervisor Confidence Collapse:</strong> Leaders concerned for safety if unresolved.</li></ul>',
        'solution' => '<ul><li><strong>Urgent Situation Analysis</strong> via confidential interviews.</li><li><strong>Policy &amp; Documentation Fast-Track:</strong> Anti-bullying standards and progressive disciplinary process.</li><li><strong>Constructive Exit Strategy:</strong> Structured voluntary separation with legal representative consultation.</li><li><strong>Legal Risk Mitigation:</strong> Separation agreement with waiver of future claims.</li><li><strong>Supervisor Reassurance &amp; Training</strong> on de-escalation and documentation.</li><li><strong>Workplace Behavior Recalibration</strong> with company-wide conduct training.</li></ul>',
        'strategy' => '<p>Mirashka blended compliance expertise, employee relations, and conflict resolution to defuse crisis and future-proof culture and processes.</p>',
        'results' => '<ul><li><strong>Risk-Free Separation in 14 days</strong> with no legal challenges.</li><li><strong>Team morale recovered</strong>—safety scores improved 55% in pulse survey.</li><li><strong>Full disciplinary and anti-bullying policies</strong> now in place.</li><li><strong>Supervisory confidence restored</strong> with clear processes and HR support.</li><li><strong>Cultural reset achieved</strong> with zero-tolerance conduct training.</li></ul>',
        'impact_highlights' => '14-day risk-free exit. 55% safety score improvement. Policy infrastructure built. Supervisor confidence restored. Respectful culture reset.',
        'media_coverage' => '<p><strong>Facing behavioral challenges in your team?</strong> Let Mirashka transform conflict into culture-building opportunities.</p>',
    ],

    // Case Study 6 — Family business
    [
        'slug' => 'family-business-succession-governance',
        'image_set' => 'family-business',
        'download_sources' => true,
        'source_urls' => [
            'featured.jpg' => 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=1600&q=80',
            'overview.jpg' => 'https://images.unsplash.com/photo-1556761175-5973dc0f32e7?w=1600&q=80',
            'team.jpg' => 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1600&q=80',
            'challenge.jpg' => 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1600&q=80',
        ],
        'main_images' => [
            'featured.jpg' => 'family-biz-featured.webp',
            'overview.jpg' => 'family-biz-overview.webp',
            'team.jpg' => 'family-biz-team.webp',
            'challenge.jpg' => 'family-biz-challenge.webp',
        ],
        'gallery_images' => [
            'team.jpg' => 'family-biz-gallery-leadership.webp',
            'overview.jpg' => 'family-biz-gallery-governance.webp',
            'featured.jpg' => 'family-biz-gallery-succession.webp',
        ],
        'title' => 'Structuring Decision-Making & Succession in a Family-Owned Business',
        'client_name' => 'Confidential Multi-Generational Family Business',
        'industry' => 'Manufacturing & Trading (Family-Owned)',
        'reach' => 'Decision-makers reduced from 8 to 3',
        'short_description' => 'A second-generation family-owned business operating for over two decades reached a critical crossroads—defining succession plans and a structured leadership framework balancing family interests with business sustainability. Multiple family members in decision-making caused delays, diluted decisions, and growing management tension.',
        'challenge' => '<ul><li><strong>Too Many Decision Makers:</strong> 8+ family members in daily decisions causing confusion and delays.</li><li><strong>Blurry Roles &amp; Responsibilities:</strong> Overlapping family roles left employees uncertain whom to follow.</li><li><strong>Lack of Succession Clarity:</strong> No roadmap for leadership and ownership transfer.</li><li><strong>Resistance to External Talent:</strong> Fear of losing control when hiring professionals.</li><li><strong>Change Management Concerns:</strong> Deep-rooted legacy practices made change sensitive.</li></ul>',
        'solution' => '<ul><li><strong>Family Business Diagnostic</strong> via confidential interviews.</li><li><strong>Future State Organizational Blueprint</strong> with clear role boundaries and decision rights.</li><li><strong>Succession Planning Framework</strong> based on capability, not lineage alone.</li><li><strong>Role Clarity &amp; Job Descriptions</strong> for every leadership role.</li><li><strong>Professionalizing Governance</strong> with family council vs management team separation.</li><li><strong>Change Management Support</strong> for newly appointed General Manager.</li><li><strong>Quarterly Town Hall Meetings</strong> for transparent communication.</li></ul>',
        'strategy' => '<p>Mirashka respected family legacy while embedding professional governance—future-proofing leadership without eroding family values.</p>',
        'results' => '<ul><li><strong>Decision-makers reduced from 8 to 3</strong> with defined escalation points.</li><li><strong>Succession clarity achieved</strong> for family and employees.</li><li><strong>70% increase in role clarity</strong> post-restructure surveys.</li><li><strong>34% reduction in voluntary attrition</strong> within 6 months.</li><li><strong>Cultural shift towards professionalism</strong> acknowledged by family leadership.</li><li><strong>Seamless GM transition</strong> with ongoing HR coaching.</li></ul>',
        'impact_highlights' => '8 to 3 decision-makers. Succession roadmap live. 70% clearer roles. 34% lower attrition. Professional governance without losing family values.',
        'media_coverage' => '<p><strong>Family business facing succession dilemmas?</strong> Let Mirashka help you build a future-ready legacy.</p>',
    ],

    // Case Study 7 — 3 Vision Consulting
    [
        'slug' => '3vision-consulting-hr-transformation',
        'image_set' => '3vision-consulting',
        'download_sources' => true,
        'source_urls' => [
            'featured.jpg' => 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=1600&q=80',
            'overview.jpg' => 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=1600&q=80',
            'team.jpg' => 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=1600&q=80',
            'challenge.jpg' => 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1600&q=80',
        ],
        'main_images' => [
            'featured.jpg' => '3vision-featured.webp',
            'overview.jpg' => '3vision-overview.webp',
            'team.jpg' => '3vision-team.webp',
            'challenge.jpg' => '3vision-challenge.webp',
        ],
        'gallery_images' => [
            'team.jpg' => '3vision-gallery-hrms.webp',
            'overview.jpg' => '3vision-gallery-consulting.webp',
            'featured.jpg' => '3vision-gallery-hraas.webp',
        ],
        'title' => 'Transforming HR Operations for 3 Vision Consulting',
        'client_name' => '3 Vision Consulting Group of Companies',
        'industry' => 'Process Consulting, Engineering & IT Services',
        'reach' => '65% engagement score increase',
        'short_description' => '3 Vision Consulting, a diversified group with 100+ employees across process consulting, engineering, and IT, struggled with fragmented HR processes despite an internal HR team. Co-founders spent 30% of their time on people issues. They partnered with Mirashka to turn HR from a headache into a strategic growth enabler through HRaaS.',
        'challenge' => '<ul><li><strong>Inexperienced Internal HR Team</strong> lacking strategic expertise for multi-business operations.</li><li><strong>Founder Time Drain:</strong> 30% of co-founder time on day-to-day people issues.</li><li><strong>Fragmented HR Processes</strong> across business units with no common policies.</li><li><strong>No Performance Culture:</strong> No structured PMS or clear career paths.</li><li><strong>Limited Employee Engagement</strong> and no structured feedback.</li><li><strong>Poor Employer Branding</strong> and no digital HR platform.</li></ul>',
        'solution' => '<ul><li><strong>Full HR Department Setup</strong> with roles, processes, and policies across verticals.</li><li><strong>Unified HR Policy Framework</strong> for recruitment through offboarding.</li><li><strong>KPI-driven Performance Management</strong> linked to rewards and growth.</li><li><strong>HR Process Digitization</strong> via centralized HRMS platform.</li><li><strong>Ongoing Managed HR Services</strong> with dedicated HR Manager.</li><li><strong>Employee Experience Revamp</strong> with induction, engagement, and surveys.</li><li><strong>Talent Attraction &amp; Employer Branding</strong> across recruitment channels.</li><li><strong>Leadership Advisory</strong> on succession and organizational structuring.</li></ul>',
        'strategy' => '<p>Mirashka deployed HRaaS combining strategy, technology, and operational excellence—making HR an agile, scalable engine for future growth.</p>',
        'results' => '<ul><li><strong>Employee Engagement Score Increased by 65%.</strong></li><li><strong>30% of founder time reclaimed</strong> for strategy and client acquisition.</li><li><strong>HR standardization achieved</strong> across all business divisions.</li><li><strong>Time-to-hire reduced by 40%</strong> with stronger employer brand.</li><li><strong>Performance-driven culture embedded</strong> with KPIs and feedback.</li><li><strong>Real-time HR data</strong> via HRMS dashboards.</li></ul>',
        'impact_highlights' => '65% engagement lift. 30% founder time saved. Unified HR policies. 40% faster hiring. Performance culture and HRMS in place.',
        'media_coverage' => '<p><strong>Want to turn HR from a cost center to a growth driver?</strong> Let Mirashka design your HR success story.</p>',
    ],
];
