<?php

return [
    'meta' => [
        'title' => 'Industries We Serve',
        'positioning' => 'People Solutions Built Around the Realities of Every Industry',
        'purpose' => 'This page should help visitors understand that Mirashka is not offering generic HR services. Mirashka understands how hiring, compliance, leadership, payroll, workforce management and HRaaS needs change from industry to industry.',
    ],

    'hero' => [
        'label' => 'Industries We Serve',
        'heading' => 'HR, Talent and Workforce Solutions for Industry-Led Growth',
        'subheading' => [
            'Every industry has a different workforce challenge. Financial services need compliance-ready talent. Healthcare needs reliability and sensitivity. Technology needs speed. Retail needs scale. Manufacturing needs discipline. Automobile businesses need trained, customer-facing teams.',
            'Mirashka helps businesses across sectors build people systems that are aligned with industry needs, business growth and operational realities.',
        ],
        'ctas' => [
            ['label' => 'Explore Industries', 'href' => '#industries-grid'],
            ['label' => 'Book Industry HR Consultation', 'href' => '#industry-form'],
        ],
        'image' => 'assets/frontend/img/industries/industries-we-serve-hero-mirashka.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
    ],

    'reality' => [
        'before_title' => 'Why Industry Context Matters',
        'label' => 'Why Industry Context Matters',
        'heading' => 'The same HR model cannot work for every business',
        'paragraphs' => [
            'A hiring process for a bank cannot be the same as hiring for a hospital. A payroll structure for a manufacturing plant cannot be handled like a SaaS company. A leadership role in insurance is different from a leadership role in automobile services.',
            'Mirashka builds HR and talent solutions with industry context. We study the business model, workforce structure, compliance needs, role complexity, hiring urgency, customer-facing requirements and leadership expectations before designing the right HR solution.',
        ],
        'pain_points_label' => 'Pain Points',
        'pain_points' => [
            'Industry-specific hiring gaps',
            'High attrition in operational roles',
            'Compliance and documentation risks',
            'Weak leadership pipeline',
            'Skill mismatch in hiring',
            'Delayed onboarding',
            'Payroll and attendance complexity',
            'Lack of structured employee engagement',
        ],
        'cta' => 'Get Industry HR Assessment',
        'cta_href' => '#industry-form',
        'image' => 'assets/frontend/img/industries/industries-we-serve-hero-mirashka.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
        'image_alt' => 'Split visual showing six industries with different HR challenges mapped to one Mirashka solution layer',
    ],

    'approach' => [
        'label' => 'Our Industry Approach',
        'heading' => 'We do not begin with resumes. We begin with business understanding.',
        'content' => 'Mirashka’s industry approach begins by understanding how your business operates, what type of talent it needs, which roles are mission-critical, what compliance risks exist, how workforce productivity is measured and where people systems can improve business performance.',
        'steps' => [
            [
                'number' => '1',
                'title' => 'Understand the Industry',
                'text' => 'We study business model, customer type, role complexity, workforce size and operating environment.',
                'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'icon_class' => 'ri-building-2-line',
            ],
            [
                'number' => '2',
                'title' => 'Map Workforce Needs',
                'text' => 'We identify frontline, operational, technical, managerial and leadership requirements.',
                'image' => 'assets/frontend/img/compliance/cwi-services.png',
                'icon_class' => 'ri-team-line',
            ],
            [
                'number' => '3',
                'title' => 'Build HR Systems',
                'text' => 'We create hiring, payroll, compliance, documentation, engagement and HR technology structures.',
                'image' => 'assets/frontend/img/compliance/cwi-risk.png',
                'icon_class' => 'ri-settings-3-line',
            ],
            [
                'number' => '4',
                'title' => 'Support Growth',
                'text' => 'We work as an extended HR partner to improve workforce quality, stability and performance.',
                'image' => 'assets/frontend/img/compliance/cwi-integrity.png',
                'icon_class' => 'ri-line-chart-line',
            ],
        ],
    ],

    'industries_grid' => [
        'label' => 'Industries Covered',
        'heading' => 'HR and talent solutions across six major industry clusters',
        'content' => 'Mirashka supports businesses across financial services, healthcare, technology, consumer and retail, industrial and energy, and automobile sectors. Each industry cluster has dedicated service thinking, role understanding and HR operating models.',
        'cards' => [
            [
                'title' => 'Financial Services',
                'subcategories' => ['Banking', 'Insurance', 'Asset Management'],
                'description' => 'Compliance-driven talent solutions for institutions where trust, accuracy, documentation and customer responsibility matter deeply.',
                'cta' => 'Explore Financial Services',
                'route' => 'bfsifintech',
                'icon' => 'icon-bank',
                'image' => 'assets/frontend/img/compliance/cwi-risk.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-integrity.png',
            ],
            [
                'title' => 'Healthcare',
                'subcategories' => ['Pharmaceuticals', 'Hospitals & Clinics', 'Medical Devices'],
                'description' => 'People solutions for healthcare businesses where reliability, empathy, process discipline and regulatory awareness are essential.',
                'cta' => 'Explore Healthcare',
                'route' => 'healthwellness',
                'icon' => 'icon-pharmacy',
                'image' => 'asassets/frontend/img/compliance/cwi-integrity.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-hero.png',
            ],
            [
                'title' => 'Technology',
                'subcategories' => ['Software & SaaS', 'Hardware & Infrastructure', 'Emerging Technologies'],
                'description' => 'Fast, skill-led hiring and HR systems for technology companies where speed, specialization and retention drive growth.',
                'cta' => 'Explore Technology',
                'route' => 'enterprisetechsaas',
                'icon' => 'icon-cpu',
                'image' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-risk.png',
            ],
            [
                'title' => 'Consumer & Retail',
                'subcategories' => ['E-commerce', 'Fashion & Apparel', 'Food & Beverage'],
                'description' => 'Scalable workforce solutions for customer-facing businesses where speed, service quality and operational consistency define success.',
                'cta' => 'Explore Consumer & Retail',
                'route' => 'luxurybrands',
                'icon' => 'icon-shopping-cart',
                'image' => 'assets/frontend/img/compliance/cwi-hero.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-services.png',
            ],
            [
                'title' => 'Industrial & Energy',
                'subcategories' => ['Manufacturing', 'Oil & Gas', 'Renewable Energy'],
                'description' => 'Structured HR, staffing and compliance support for operations-heavy industries where safety, productivity and skill reliability matter.',
                'cta' => 'Explore Industrial & Energy',
                'route' => 'infrastructureenergy',
                'icon' => 'icon-factory',
                'image' => 'assets/frontend/img/compliance/cwi-integrity.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
            ],
            [
                'title' => 'Automobile',
                'subcategories' => ['Automobile Accessories', 'Automobile Services', 'Automobile Dealerships & Mobility'],
                'description' => 'Talent and HR solutions for automobile businesses where technical skill, customer service, process discipline and local market execution are critical.',
                'cta' => 'Explore Automobile',
                'route' => 'whoweserve',
                'icon' => 'icon-car',
                'image' => 'assets/frontend/img/compliance/cwi-risk.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-hero.png',
            ],
        ],
    ],

    'pulse' => [
        'label' => 'PULSE for Industry HR',
        'heading' => 'One people framework adapted to every industry',
        'content' => 'Mirashka applies its PULSE Framework across industries. The framework gives every business a structured way to protect the organization, unify HR operations, build leadership, source talent and empower growth.',
        'cards' => [
            [
                'letter' => 'P',
                'title' => 'Protect',
                'text' => 'Industry-specific compliance, policy documentation, POSH, workplace ethics and risk management.',
                'image' => 'assets/frontend/img/compliance/cwi-card-policy.png',
                'image_fallback' => 'assets/frontend/img/compliance/cwi-card-audit.png',
            ],
            [
                'letter' => 'U',
                'title' => 'Unify',
                'text' => 'Payroll, employee records, onboarding, attendance, documentation and remote HR operations.',
                'image' => 'assets/frontend/img/workforce/wfm-card-payroll.png',
                'image_fallback' => 'assets/frontend/img/workforce/wfm-services-center.png',
            ],
            [
                'letter' => 'L',
                'title' => 'Lead',
                'text' => 'Leadership hiring, succession planning, family business governance and board advisory.',
                'image' => 'assets/frontend/img/leadership/ldr-board-advisory.png',
                'image_fallback' => 'assets/frontend/img/leadership/ldr-hero-boardroom.png',
            ],
            [
                'letter' => 'S',
                'title' => 'Source',
                'text' => 'Staffing, recruitment, IT hiring, RPO, apprenticeships and executive search.',
                'image' => 'assets/frontend/img/talent-acquisition/ta-card-executive-search.png',
                'image_fallback' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
            ],
            [
                'letter' => 'E',
                'title' => 'Empower',
                'text' => 'HRaaS, employer branding, employee engagement, surveys, retention and HR technology.',
                'image' => 'assets/frontend/img/hraas/hraas-card-engagement.png',
                'image_fallback' => 'assets/frontend/img/hraas/hraas-card-branding.png',
            ],
        ],
        'cta' => ['label' => 'Apply PULSE to My Industry', 'href' => '#industry-form'],
        'image' => 'assets/frontend/img/industries/pulse-framework-for-industries.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
    ],

    'services' => [
        'label' => 'What We Deliver',
        'heading' => 'Every industry can start with one HR need and scale into a complete people system',
        'content' => 'Some businesses approach Mirashka for hiring. Some need compliance. Some need payroll discipline. Some need leadership search. Some need a complete HRaaS model. Mirashka allows every business to start where the pressure is highest and then expand into a complete people operating system.',
        'image' => 'assets/frontend/img/home/home-why-mirashka-hero.png',
        'image_fallback' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
        'image_secondary' => 'assets/frontend/img/leadership/ldr-hero-boardroom.png',
        'image_secondary_fallback' => 'assets/frontend/img/hraas/hraas-page-partner.png',
        'cards' => [
            ['title' => 'HRaaS & HR Outsourcing', 'text' => 'Dedicated HR support for growing companies.', 'icon' => 'ri-customer-service-2-line'],
            ['title' => 'Recruitment & Staffing', 'text' => 'IT staffing, general staffing, executive search and RPO.', 'icon' => 'ri-user-search-line'],
            ['title' => 'Payroll & Administration', 'text' => 'Payroll coordination, attendance, records and documentation.', 'icon' => 'ri-money-dollar-circle-line'],
            ['title' => 'Compliance & Workplace Integrity', 'text' => 'Policies, audits, legal guidance and workplace training.', 'icon' => 'ri-shield-check-line'],
            ['title' => 'Leadership Hiring', 'text' => 'CXO, senior leadership and strategic role hiring.', 'icon' => 'ri-user-star-line'],
            ['title' => 'Employee Engagement', 'text' => 'Surveys, retention, performance systems and employee communication.', 'icon' => 'ri-emotion-happy-line'],
            ['title' => 'HR Technology', 'text' => 'HR tools, dashboards, automation and reporting.', 'icon' => 'ri-computer-line'],
            ['title' => 'Talent Strategy Advisory', 'text' => 'Workforce planning, restructuring, succession and growth alignment.', 'icon' => 'ri-line-chart-line'],
        ],
        'cta' => ['label' => 'Explore Mirashka HR Services', 'href' => 'whatwedo'],
    ],

    'challenges' => [
        'label' => 'Common Workforce Challenges',
        'heading' => 'Different sectors. Similar people challenges. Different solutions.',
        'content' => 'Though every industry is different, many businesses face common HR problems. Mirashka helps identify the root cause and design solutions that match the sector’s working style.',
        'blocks' => [
            ['title' => 'High Attrition', 'text' => 'Common in retail, automobile services, sales teams and frontline roles.'],
            ['title' => 'Skill Shortage', 'text' => 'Common in technology, healthcare, manufacturing and automobile technical roles.'],
            ['title' => 'Compliance Risk', 'text' => 'Critical in financial services, healthcare, manufacturing and organized workforce setups.'],
            ['title' => 'Leadership Gap', 'text' => 'Seen in family businesses, growing companies and founder-led organizations.'],
            ['title' => 'Payroll Complexity', 'text' => 'Common in shift-based, branch-based, field-based and multi-location operations.'],
            ['title' => 'Weak Employer Brand', 'text' => 'Affects hiring quality, retention and candidate interest across industries.'],
        ],
        'cta' => ['label' => 'Discuss My Industry Challenge', 'href' => '#industry-form'],
    ],

    'use_cases' => [
        'label' => 'How Mirashka Creates Impact',
        'heading' => 'Practical HR outcomes across industry situations',
        'tags' => ['Faster Hiring', 'Cleaner Payroll', 'Lower Risk', 'Better Retention'],
        'cards' => [
            [
                'number' => '1',
                'title' => 'Scaling Hiring for a Growth Business',
                'text' => 'Mirashka builds role clarity, sourcing strategy, screening process and interview coordination to close hiring faster.',
            ],
            [
                'number' => '2',
                'title' => 'Structuring HR for a Founder-Led Company',
                'text' => 'Mirashka creates policies, employee records, onboarding systems, payroll coordination and reporting discipline.',
            ],
            [
                'number' => '3',
                'title' => 'Leadership Hiring for Expansion',
                'text' => 'Mirashka identifies senior professionals who understand both strategy and execution.',
            ],
            [
                'number' => '4',
                'title' => 'Compliance Readiness for a Regulated Business',
                'text' => 'Mirashka conducts HR audits, policy review, documentation correction and risk mitigation.',
            ],
            [
                'number' => '5',
                'title' => 'Employee Engagement for Retention',
                'text' => 'Mirashka sets up employee surveys, feedback systems, KRAs and performance communication.',
            ],
            [
                'number' => '6',
                'title' => 'HRaaS for Lean Teams',
                'text' => 'Mirashka works as the external HR office for companies that need expert support without building a large internal team.',
            ],
        ],
        'cta' => ['label' => 'View Industry Case Studies', 'href' => '/case-studies'],
    ],

    'video' => [
        'label' => 'Watch Industry HR in Action',
        'heading' => 'How Mirashka adapts HR solutions for different industries',
        'content' => 'A short explainer video can show how Mirashka understands business realities across sectors and converts industry-specific workforce problems into structured HR solutions.',
        'storyline_title' => 'Video Storyline',
        'storyline' => [
            'Every industry has unique people challenges',
            'Informal HR creates risk and delay',
            'Mirashka studies the business and workforce model',
            'PULSE framework is adapted to each sector',
            'Services are deployed as per business priority',
            'HR becomes measurable, structured and growth-aligned',
        ],
        'ctas' => [
            ['label' => 'Watch Video', 'href' => 'https://www.youtube.com/embed/-VK0axfge4A', 'video' => true],
            ['label' => 'Book Industry HR Consultation', 'href' => '#industry-form'],
        ],
        'image' => 'assets/frontend/img/industries/industries-video-thumbnail-mirashka-hr.webp',
        'image_fallback' => 'assets/frontend/images/about/about-8.jpg',
    ],

    'health_check' => [
        'label' => 'Start With Diagnosis',
        'heading' => 'Not sure what your industry-specific HR gaps are?',
        'content' => 'Mirashka’s Industry HR Health Check helps businesses identify gaps in hiring, payroll, compliance, documentation, leadership, employee engagement and HR technology based on their sector and business stage.',
        'covers' => [
            'Hiring process',
            'Role clarity',
            'Payroll structure',
            'Employee documentation',
            'Compliance exposure',
            'Policy gaps',
            'Leadership readiness',
            'Retention risk',
            'HR technology readiness',
            'Industry-specific workforce risks',
        ],
        'output' => 'A practical industry HR roadmap with priority actions, risk areas and recommended Mirashka service plan.',
        'cta' => ['label' => 'Request Industry HR Health Check', 'href' => '#industry-form'],
        'image' => 'assets/frontend/img/industries/industry-hr-health-dashboard.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-meeting.png',
    ],

    'form' => [
        'label' => 'Talk to Mirashka',
        'heading' => 'Tell us your industry. We will help you build the right people system.',
        'content' => 'Share your business type, current team size and HR challenge. Mirashka will help identify whether you need hiring support, HRaaS, payroll, compliance, leadership hiring, employee engagement or a complete HR operating model.',
        'lead_type' => 'industry_hr_enquiry',
        'industries' => [
            'Financial Services' => ['Banking', 'Insurance', 'Asset Management'],
            'Healthcare' => ['Pharmaceuticals', 'Hospitals & Clinics', 'Medical Devices'],
            'Technology' => ['Software & SaaS', 'Hardware & Infrastructure', 'Emerging Technologies'],
            'Consumer & Retail' => ['E-commerce', 'Fashion & Apparel', 'Food & Beverage'],
            'Industrial & Energy' => ['Manufacturing', 'Oil & Gas', 'Renewable Energy'],
            'Automobile' => ['Automobile Accessories', 'Automobile Services', 'Automobile Dealerships & Mobility'],
            'Other' => ['Other'],
        ],
        'services' => [
            'HRaaS / HR Outsourcing',
            'Recruitment / Staffing',
            'Leadership Hiring',
            'Payroll Support',
            'Compliance Audit',
            'Policy Documentation',
            'POSH / Workplace Training',
            'Employee Engagement',
            'HR Technology',
            'Not Sure — Need Consultation',
        ],
        'submit' => 'Submit Industry HR Enquiry',
        'secondary_cta' => ['label' => 'Book 30-Minute Consultation', 'href' => 'https://calendly.com/elevateonemedia/30min'],
        'image' => 'assets/frontend/img/industries/industry-form-consultant.webp',
        'image_fallback' => 'assets/frontend/img/compliance/cwi-bento-advisor.png',
    ],

    'faq_blog' => [
        'label' => 'Learn More',
        'heading' => 'Questions businesses ask before choosing industry HR support',
        'faqs' => [
            [
                'question' => 'What makes Mirashka’s industry HR approach different?',
                'answer' => 'Mirashka studies the industry, workforce structure, role requirements and compliance realities before designing HR solutions.',
            ],
            [
                'question' => 'Can Mirashka support multi-location businesses?',
                'answer' => 'Yes. Mirashka can support standardized HR processes, hiring, payroll coordination and reporting across multiple locations.',
            ],
            [
                'question' => 'Can we start with only recruitment?',
                'answer' => 'Yes. A business can begin with recruitment, staffing, payroll, compliance audit or HRaaS and later expand into a complete HR model.',
            ],
            [
                'question' => 'Does Mirashka handle leadership hiring?',
                'answer' => 'Yes. Mirashka supports executive search, CXO hiring, leadership assessment, succession planning and board advisory.',
            ],
            [
                'question' => 'Does Mirashka provide HRaaS for small businesses?',
                'answer' => 'Yes. Mirashka HRaaS is designed for startups, MSMEs and growing businesses that need HR expertise without building a large internal HR team.',
            ],
        ],
        'blogs' => [
            'Why Industry-Specific HR Matters for Growing Businesses',
            'How PULSE Framework Helps Companies Build Better People Systems',
            'Hiring, Payroll and Compliance: The Three HR Gaps Founders Ignore',
            'Why Automobile, Retail and Healthcare Businesses Need Structured Workforce Systems',
        ],
        'cta' => ['label' => 'Read HR Insights', 'href' => '/blog'],
    ],
];
