<?php

/** @var callable build_sub_service */
/** @var callable build_category_page */

$subShared = fn (
    string $parentRoute,
    string $parentLabel,
    string $ctaHeading,
    string $ctaContent,
    string $ctaBtn,
    string $secondary,
    string $ctaImage = 'assets/admin/image/case-study/jyogi-team.webp',
    string $ctaBg = 'assets/admin/image/banner/hr-advisory.webp',
) => [
    'shared' => [
        'parent_route' => $parentRoute,
        'parent_label' => $parentLabel,
        'cta' => [
            'heading' => $ctaHeading,
            'content' => $ctaContent,
            'button' => $ctaBtn,
            'secondary' => $secondary,
            'image' => $ctaImage,
            'bg_image' => $ctaBg,
        ],
    ],
    'services' => [],
];

// --- WORKFORCE ---
$workforceCategory = build_category_page([
    'meta_title' => 'Workforce Management & Process Optimization | Mirashka',
    'meta_description' => 'Streamline HR operations with policy design, payroll administration and remote HR support. Structured, accurate and scalable people operations.',
    'meta_keywords' => 'workforce management, hr operations, payroll outsourcing, remote hr, policy audit, mirashka',
    'label' => 'Workforce Management',
    'title' => 'Workforce Management & Process Optimization',
    'tagline' => 'Streamlining HR operations to drive efficiency, compliance and business growth.',
    'content' => 'Mirashka helps companies move from person-dependent HR operations to process-driven HR systems. We design policies, manage payroll, optimize employee records and provide remote HR support so leadership can focus on business growth.',
    'headline' => 'Make HR operations structured, accurate and scalable',
    'primary_cta' => 'Optimize Your HR Operations',
    'secondary_cta' => 'Speak to an HR Advisor',
    'risk_before' => 'Operations Reality',
    'risk_heading' => 'Manual HR creates delays, errors and confusion',
    'risk_lead' => 'When HR lives in spreadsheets, memory and ad-hoc messages, payroll slips, documentation gaps and employee queries pile up fast.',
    'risk_content' => 'Growing teams need repeatable processes — not heroic effort from one overloaded HR person. Mirashka builds the operating rhythm, records and reporting your leadership can trust.',
    'risks' => [
        'Payroll inputs scattered across email and chat',
        'Policies that managers interpret differently',
        'Employee records without version control',
        'Compliance follow-ups missed in busy months',
        'No monthly HR visibility for leadership',
        'Onboarding and exits handled inconsistently',
    ],
    'services_heading' => 'Structured support across core HR operations',
    'services_content' => 'From policy audits and payroll coordination to a dedicated remote HR desk — one integrated path to scalable people operations.',
    'service_items' => [
        ['title' => 'Policy Design & Compliance Audit', 'text' => 'Create, review and audit HR policies that stay legally aligned and practical for managers.', 'icon' => 'ri-file-shield-2-line'],
        ['title' => 'Payroll Outsourcing & Administration', 'text' => 'Accurate payroll coordination, statutory inputs, payslips and structured reporting.', 'icon' => 'ri-money-dollar-circle-line'],
        ['title' => 'Remote HR Solutions', 'text' => 'Your external HR desk for onboarding, records, compliance follow-ups and monthly reporting.', 'icon' => 'ri-computer-line'],
    ],
    'framework_before' => 'HR Process Map',
    'framework_heading' => 'Policy, payroll, records, reporting',
    'framework_content' => 'A clear HR process map that connects everyday operations to leadership visibility — built for growing Indian businesses.',
    'framework_steps' => [
        ['title' => 'Policy', 'subtitle' => 'Foundation', 'text' => 'Gap review, creation, revision and manager implementation guides with a review calendar.', 'icon' => 'ri-file-shield-2-line'],
        ['title' => 'Payroll', 'subtitle' => 'Accuracy', 'text' => 'Input collection, salary coordination, compliance inputs and query resolution.', 'icon' => 'ri-calculator-line'],
        ['title' => 'Records', 'subtitle' => 'Control', 'text' => 'Employee master data, documentation, onboarding and exit workflows.', 'icon' => 'ri-folder-user-line'],
        ['title' => 'Reporting', 'subtitle' => 'Visibility', 'text' => 'Monthly HR dashboards leadership can act on — not scattered updates.', 'icon' => 'ri-bar-chart-box-line'],
    ],
    'integrity_eyebrow' => 'Remote HR Desk',
    'integrity_heading' => 'Your extended HR team — without full-time overhead',
    'integrity_content' => 'Mirashka acts as your remote HR desk: dedicated coordination, employee communication, compliance follow-ups and monthly reporting so founders stay focused on growth.',
    'integrity_features' => [
        ['title' => 'Dedicated HR coordinator', 'text' => 'A named point of contact for employee queries, documentation and monthly rhythm.', 'icon' => 'ri-user-voice-line'],
        ['title' => 'Lifecycle support', 'text' => 'Recruitment coordination, onboarding, records management and structured exits.', 'icon' => 'ri-loop-left-line'],
    ],
    'integrity_float_cards' => [
        ['title' => 'Onboarding & exits', 'text' => 'Checklists, documentation and communication templates executed consistently.', 'icon' => 'ri-user-add-line', 'link' => null],
        ['title' => 'Monthly HR reporting', 'text' => 'Headcount, compliance status, open items and workforce insights for leadership.', 'icon' => 'ri-pie-chart-line', 'link' => null],
    ],
    'deliverables_heading' => 'Payroll, documentation and operational clarity',
    'deliverables_content' => 'Deliverables your finance, HR and leadership teams can rely on — not scattered files and last-minute firefighting.',
    'deliverable_cards' => [
        ['style' => 'standard', 'title' => 'Policy & audit outputs', 'text' => 'Reviewed policies, gap reports and implementation guides managers can follow.', 'icon' => 'ri-book-2-line', 'image' => img_at(0), 'bullets' => ['Policy gap review', 'Compliance alignment', 'Review calendar']],
        ['style' => 'featured', 'title' => 'Payroll & administration pack', 'text' => 'Structured payroll inputs, payslip support, statutory coordination and query resolution.', 'image' => img_at(1)],
        ['style' => 'standard', 'title' => 'Remote HR desk reporting', 'text' => 'Monthly HR summaries, employee records hygiene and compliance follow-up trackers.', 'icon' => 'ri-dashboard-line', 'image' => img_at(3), 'bullets' => ['Monthly HR report', 'Employee record management', 'Compliance follow-ups']],
    ],
    'suitable_heading' => 'Built for teams outgrowing informal HR',
    'suitable_segments' => [
        ['step' => '01', 'label' => 'Startups', 'icon' => 'ri-rocket-line', 'text' => 'Establish payroll rhythm, policies and HR documentation before complexity compounds.'],
        ['step' => '02', 'label' => 'SMEs', 'icon' => 'ri-building-2-line', 'text' => 'Standardize HR operations as headcount and locations grow.'],
        ['step' => '03', 'label' => 'Franchises', 'icon' => 'ri-store-2-line', 'text' => 'Consistent payroll, policies and remote HR support across units.'],
        ['step' => '04', 'label' => 'Scaling Companies', 'icon' => 'ri-line-chart-line', 'text' => 'Process-driven HR that frees leadership to focus on revenue and strategy.'],
    ],
    'cta_content' => 'A focused review of your HR processes, payroll workflow and documentation — with a practical plan to make operations structured and scalable.',
    'trust_role' => 'Workforce management & HR operations specialists',
]);

$wfSubs = [
    'policy-design-compliance-audit' => [
        'title' => 'Policy Design & Compliance Audit',
        'meta_title' => 'Policy Design & Compliance Audit | Mirashka',
        'meta_description' => 'Design policies that work in real business situations. Gap review, creation, compliance alignment and manager implementation guides.',
        'meta_keywords' => 'hr policy audit, policy design, compliance alignment, hr policies, mirashka',
        'hero_heading' => 'Design policies that work in real business situations',
        'hero_content' => 'We create, review and audit HR policies so they remain legally aligned, practical for managers and clear for employees — with a review calendar your team can maintain.',
        'primary_cta' => 'Audit My HR Policies',
        'secondary_cta' => 'Optimize Your HR Operations',
        'process_heading' => 'From policy gaps to an audit-ready HR foundation',
        'process_steps' => [
            ['title' => 'Policy Gap Review', 'text' => 'Assess existing policies, registers and manager practices against statutory and business needs.', 'icon' => 'ri-search-eye-line'],
            ['title' => 'Policy Creation & Revision', 'text' => 'Draft or update policies that reflect how your business actually operates.', 'icon' => 'ri-file-edit-line'],
            ['title' => 'Compliance Alignment', 'text' => 'Align documentation with labour law, industry norms and your headcount stage.', 'icon' => 'ri-scales-3-line'],
            ['title' => 'Manager Implementation Guide', 'text' => 'Practical playbooks so leaders apply policies consistently across teams.', 'icon' => 'ri-team-line'],
            ['title' => 'Review Calendar', 'text' => 'Scheduled reviews when laws, roles or operating models change.', 'icon' => 'ri-calendar-check-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Gap Review', 'content' => 'Structured assessment of policy coverage, documentation quality and implementation risk.'],
            ['label' => 'Policy Suite', 'content' => 'Handbooks, codes of conduct, leave, discipline and role-specific addenda tailored to you.'],
            ['label' => 'Compliance', 'content' => 'Statutory alignment checks with prioritized remediation actions.'],
            ['label' => 'Implementation', 'content' => 'Rollout communication, acknowledgements and manager briefing support.'],
        ],
        'sidebar_items' => [
            ['label' => 'Policy gap assessment report', 'icon' => 'ri-file-search-line'],
            ['label' => 'Custom policy creation & revision', 'icon' => 'ri-file-shield-2-line'],
            ['label' => 'Manager implementation guide', 'icon' => 'ri-book-open-line'],
            ['label' => 'Annual review calendar', 'icon' => 'ri-calendar-line'],
        ],
        'focus_title' => 'Policy documents with approval workflow — audit-ready and manager-friendly',
        'focus_content' => 'We balance legal requirements with language your teams understand, so policies protect the business and guide everyday decisions.',
    ],
    'payroll-outsourcing-administration' => [
        'title' => 'Payroll Outsourcing & Administration',
        'meta_title' => 'Payroll Outsourcing & Administration | Mirashka',
        'meta_description' => 'Accurate payroll, timely processing and smoother administration. Salary coordination, statutory inputs and reporting.',
        'meta_keywords' => 'payroll outsourcing, payroll administration, salary processing, mirashka hr',
        'hero_heading' => 'Accurate payroll, timely processing and smoother administration',
        'hero_content' => 'Mirashka manages payroll coordination, salary processing support, statutory inputs, employee data, leave inputs, reimbursement records and payroll reporting with structured accuracy.',
        'primary_cta' => 'Outsource Payroll Operations',
        'secondary_cta' => 'Speak to an HR Advisor',
        'image' => img_at(1),
        'process_heading' => 'Payroll rhythm your finance and HR teams can trust',
        'process_steps' => [
            ['title' => 'Payroll Input Collection', 'text' => 'Structured collection of attendance, leave, reimbursements and variable pay inputs.', 'icon' => 'ri-inbox-line'],
            ['title' => 'Salary Processing Coordination', 'text' => 'Timely coordination with your payroll provider or internal process for accurate runs.', 'icon' => 'ri-money-dollar-circle-line'],
            ['title' => 'Compliance Inputs', 'text' => 'PF, ESI, PT, TDS and other statutory inputs tracked and validated each cycle.', 'icon' => 'ri-shield-check-line'],
            ['title' => 'Payslip & Report Support', 'text' => 'Payslip distribution, payroll summaries and cost-centre reporting for leadership.', 'icon' => 'ri-file-chart-line'],
            ['title' => 'Query Resolution', 'text' => 'Employee payroll queries handled with documentation and closure tracking.', 'icon' => 'ri-customer-service-2-line'],
        ],
        'dash_before' => 'Payroll Dashboard',
        'dash_tabs' => [
            ['label' => 'Inputs', 'content' => 'Centralized input collection with validation before processing begins.'],
            ['label' => 'Processing', 'content' => 'Salary run coordination with audit trail and approval checkpoints.'],
            ['label' => 'Statutory', 'content' => 'Compliance inputs, filings support and register hygiene.'],
            ['label' => 'Reports', 'content' => 'Payslips, summaries and leadership-ready payroll insights.'],
        ],
        'sidebar_items' => [
            ['label' => 'Monthly payroll coordination', 'icon' => 'ri-calendar-check-line'],
            ['label' => 'Statutory input management', 'icon' => 'ri-government-line'],
            ['label' => 'Payslip & report distribution', 'icon' => 'ri-mail-send-line'],
            ['label' => 'Employee query desk', 'icon' => 'ri-question-answer-line'],
        ],
        'focus_title' => 'Payroll dashboard with salary, tax, attendance and benefits visibility',
        'focus_content' => 'Structured administration that reduces errors, delays and month-end stress for HR and finance.',
    ],
    'remote-hr-solutions' => [
        'title' => 'Remote HR Solutions',
        'meta_title' => 'Remote HR Solutions | Mirashka',
        'meta_description' => 'Your external HR desk for everyday people operations — onboarding, records, compliance and monthly reporting.',
        'meta_keywords' => 'remote hr, hr outsourcing desk, virtual hr team, mirashka',
        'hero_heading' => 'Your external HR desk for everyday people operations',
        'hero_content' => 'Mirashka acts as your remote HR team, supporting recruitment coordination, onboarding, documentation, employee records, communication, compliance follow-ups and monthly HR reporting.',
        'primary_cta' => 'Build My Remote HR Desk',
        'secondary_cta' => 'Optimize Your HR Operations',
        'image' => img_at(3),
        'process_heading' => 'Dedicated remote HR without building a full department',
        'process_steps' => [
            ['title' => 'What Remote HR Covers', 'text' => 'Scope definition across hiring support, lifecycle, compliance and reporting.', 'icon' => 'ri-list-check-2'],
            ['title' => 'Dedicated HR Coordinator Model', 'text' => 'Named coordinator for employees, managers and leadership queries.', 'icon' => 'ri-user-star-line'],
            ['title' => 'Employee Record Management', 'text' => 'Master data, documents, acknowledgements and audit-ready files.', 'icon' => 'ri-folder-user-line'],
            ['title' => 'Onboarding and Exit Support', 'text' => 'Structured checklists, communication and documentation for every transition.', 'icon' => 'ri-user-shared-line'],
            ['title' => 'Monthly HR Reporting', 'text' => 'Workforce snapshot, open compliance items and operational priorities.', 'icon' => 'ri-bar-chart-grouped-line'],
        ],
        'dash_tabs' => [
            ['label' => 'HR Desk', 'content' => 'Virtual HR desk covering day-to-day people operations and employee communication.'],
            ['label' => 'Onboarding', 'content' => 'Joining kits, documentation, induction coordination and first-week check-ins.'],
            ['label' => 'Records', 'content' => 'Employee files, policy acknowledgements and document version control.'],
            ['label' => 'Reporting', 'content' => 'Monthly leadership report with headcount, risks and action items.'],
        ],
        'sidebar_items' => [
            ['label' => 'Dedicated HR coordinator', 'icon' => 'ri-headphone-line'],
            ['label' => 'Recruitment & onboarding support', 'icon' => 'ri-user-add-line'],
            ['label' => 'Compliance follow-up tracking', 'icon' => 'ri-shield-line'],
            ['label' => 'Monthly HR leadership report', 'icon' => 'ri-file-chart-line'],
        ],
        'focus_title' => 'Virtual HR desk connecting employees, managers and leadership',
        'focus_content' => 'Remote HR that feels present — responsive coordination, clear documentation and monthly visibility.',
    ],
];

$workforceSubServices = $subShared('workforce', 'Workforce Management', 'Optimize Your HR Operations', 'Structured HR operations review with practical recommendations for policy, payroll and remote HR desk setup.', 'Optimize Your HR Operations', 'Speak to an HR Advisor', 'assets/frontend/img/workforce/wfm-cta-person-v2.png', 'assets/frontend/img/workforce/wfm-cta-bg-v2.png');
$workforceSubServices['services'] = [];
foreach ($wfSubs as $slug => $d) {
    $d = apply_sub_service_images($d, 'workforce', $slug);
    $workforceSubServices['services'][$slug] = apply_sub_extra_sections(build_sub_service($d), $d, 'workforce', $slug);
}

// --- LEADERSHIP ---
$leadershipCategory = build_category_page([
    'meta_title' => 'Leadership & Organizational Excellence | Mirashka',
    'meta_description' => 'Executive search, board advisory, succession planning, leadership assessment and talent strategy for growth-focused organizations.',
    'meta_keywords' => 'executive search, leadership hiring, ceo succession, leadership assessment, talent strategy, mirashka',
    'label' => 'Leadership & Organization',
    'title' => 'Leadership & Organizational Excellence Solutions',
    'tagline' => 'Empowering businesses with visionary leadership, future-ready strategies and inclusive growth.',
    'content' => 'Leadership determines the quality of decisions, culture and execution. Mirashka helps organizations identify, assess, develop and transition leaders who can drive growth, governance, transformation and long-term business continuity.',
    'headline' => 'Build leadership that can carry your next stage of growth',
    'primary_cta' => 'Start Leadership Readiness Review',
    'secondary_cta' => 'Speak to a Leadership Advisor',
    'risk_heading' => 'When business outgrows existing structure',
    'risk_lead' => 'Promotions based on tenure, unclear succession and leaders stretched beyond their current capability slow execution and culture.',
    'risk_content' => 'Mirashka brings structure to leadership hiring, board advisory, succession and assessment — so your next stage of growth has the right people at the top.',
    'risks' => [
        'Key roles filled without structured assessment',
        'No succession plan for CEO or functional heads',
        'Board and management misaligned on priorities',
        'Leadership pipeline undefined',
        'Culture drift after rapid growth',
        'Family or founder dynamics blocking professionalization',
    ],
    'services_heading' => 'Leadership support across the executive lifecycle',
    'services_content' => 'From executive search and board advisory to succession, assessment and talent strategy — integrated leadership excellence.',
    'service_items' => [
        ['title' => 'Executive Search & Leadership Hiring', 'text' => 'Senior leadership hiring through role mapping, evaluation and culture-fit assessment.', 'icon' => 'ri-user-search-line'],
        ['title' => 'Board & CEO Advisory', 'text' => 'Governance, decision systems, performance reviews and strategic planning for leadership teams.', 'icon' => 'ri-briefcase-4-line'],
        ['title' => 'CEO Succession & Performance', 'text' => 'Structured succession, transition calendars and 90-day performance acceleration.', 'icon' => 'ri-arrow-up-circle-line'],
        ['title' => 'Leadership Assessment & Consulting', 'text' => 'Evaluate capability, role readiness and development roadmaps before critical appointments.', 'icon' => 'ri-mental-health-line'],
        ['title' => 'HR & Talent Strategy Advisory', 'text' => 'Workforce planning, talent pipelines and culture initiatives aligned to business goals.', 'icon' => 'ri-route-line'],
    ],
    'framework_before' => 'Leadership Capability Framework',
    'framework_heading' => 'Identify, assess, develop, transition',
    'framework_content' => 'A disciplined approach to leadership decisions — from mandate definition through onboarding and performance rhythm.',
    'framework_steps' => [
        ['title' => 'Identify', 'subtitle' => 'Mandate', 'text' => 'Role definition, market mapping and culture-fit criteria for critical leadership seats.', 'icon' => 'ri-focus-3-line'],
        ['title' => 'Assess', 'subtitle' => 'Evidence', 'text' => 'Behavioral, strategic and role-readiness evaluation before you commit.', 'icon' => 'ri-clipboard-line'],
        ['title' => 'Develop', 'subtitle' => 'Pipeline', 'text' => 'Coaching, development roadmaps and talent strategy aligned to growth.', 'icon' => 'ri-seedling-line'],
        ['title' => 'Transition', 'subtitle' => 'Continuity', 'text' => 'Succession planning, CEO transitions and structured onboarding for new leaders.', 'icon' => 'ri-exchange-line'],
    ],
    'integrity_eyebrow' => 'Board & CEO Advisory',
    'integrity_heading' => 'Governance and strategy leadership can trust',
    'integrity_content' => 'We help boards and CEOs strengthen governance rhythm, decision systems and performance architecture — so leadership stays aligned as the business scales.',
    'integrity_features' => [
        ['title' => 'Board advisory scope', 'text' => 'Governance cadence, risk visibility and strategic planning workshops.', 'icon' => 'ri-government-line'],
        ['title' => 'CEO decision support', 'text' => 'Structured performance reviews, org design and long-term planning facilitation.', 'icon' => 'ri-vip-crown-line'],
    ],
    'integrity_float_cards' => [
        ['title' => 'Succession readiness', 'text' => 'Audit successor readiness, role clarity and transition calendars.', 'icon' => 'ri-calendar-todo-line', 'link' => null],
        ['title' => 'Leadership assessment tools', 'text' => 'Competency frameworks and evaluation reports management can act on.', 'icon' => 'ri-bar-chart-horizontal-line', 'link' => null],
    ],
    'deliverables_heading' => 'Leadership outcomes you can defend',
    'deliverables_content' => 'Structured outputs for boards, CEOs and HR — not informal networks and gut-feel appointments alone.',
    'deliverable_cards' => [
        ['style' => 'standard', 'title' => 'Executive search deliverables', 'text' => 'Role maps, shortlists, evaluation reports and onboarding support.', 'icon' => 'ri-user-star-line', 'image' => img_at(0), 'bullets' => ['Leadership role definition', 'Culture & business fit assessment', 'Offer support']],
        ['style' => 'featured', 'title' => 'Succession & transition plan', 'text' => 'Readiness audit, transition calendar and 90-day performance framework.', 'image' => img_at(4)],
        ['style' => 'standard', 'title' => 'Talent strategy roadmap', 'text' => 'Workforce planning, gap analysis and pipeline design aligned to strategy.', 'icon' => 'ri-map-2-line', 'image' => img_at(5), 'bullets' => ['Workforce planning', 'Talent gap analysis', 'Culture & performance strategy']],
    ],
    'suitable_heading' => 'For organizations investing in leadership quality',
    'suitable_segments' => [
        ['step' => '01', 'label' => 'Growth Companies', 'icon' => 'ri-line-chart-line', 'text' => 'Build leadership bench strength before complexity outpaces capability.'],
        ['step' => '02', 'label' => 'Family Businesses', 'icon' => 'ri-home-heart-line', 'text' => 'Professionalize leadership and succession without losing founder legacy.'],
        ['step' => '03', 'label' => 'Boards & Investors', 'icon' => 'ri-funds-line', 'text' => 'Strengthen governance, CEO performance and leadership accountability.'],
        ['step' => '04', 'label' => 'Transforming Orgs', 'icon' => 'ri-refresh-line', 'text' => 'Restructure with clarity, empathy and leadership alignment to new realities.'],
    ],
    'cta_content' => 'A leadership readiness review covering succession, pipeline gaps and advisory priorities — with clear next steps for your board and CEO.',
    'trust_role' => 'Leadership & organizational excellence specialists',
]);

$ldSubs = [
    'executive-search-leadership-hiring' => [
        'title' => 'Executive Search & Leadership Hiring',
        'meta_title' => 'Executive Search & Leadership Hiring | Mirashka',
        'meta_description' => 'Find leaders who match ambition, culture and execution needs. Role mapping, evaluation and onboarding support.',
        'meta_keywords' => 'executive search, leadership hiring, senior hiring, mirashka',
        'hero_heading' => 'Find leaders who match ambition, culture and execution needs',
        'hero_content' => 'Mirashka supports senior leadership hiring through role mapping, market research, candidate sourcing, evaluation, culture-fit assessment and onboarding support.',
        'primary_cta' => 'Start Executive Search',
        'secondary_cta' => 'Speak to a Leadership Advisor',
        'process_heading' => 'Leadership hiring with rigor and confidentiality',
        'process_steps' => [
            ['title' => 'Leadership Role Definition', 'text' => 'Mandate, success profile, compensation band and stakeholder alignment.', 'icon' => 'ri-file-user-line'],
            ['title' => 'Market Mapping', 'text' => 'Target company and candidate landscape research for your sector.', 'icon' => 'ri-global-line'],
            ['title' => 'Candidate Evaluation', 'text' => 'Structured interviews, references and competency-based assessment.', 'icon' => 'ri-user-search-line'],
            ['title' => 'Culture & Business Fit', 'text' => 'Alignment to values, governance style and growth stage realities.', 'icon' => 'ri-heart-line'],
            ['title' => 'Offer & Onboarding Support', 'text' => 'Offer negotiation support and first-90-day onboarding rhythm.', 'icon' => 'ri-handshake-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Role Map', 'content' => 'Clear mandate and evaluation criteria before search begins.'],
            ['label' => 'Shortlist', 'content' => 'Confidential outreach and curated leadership candidate panels.'],
            ['label' => 'Evaluation', 'content' => 'Assessment reports your board and CEO can compare objectively.'],
            ['label' => 'Onboarding', 'content' => 'Transition support so new leaders land with momentum.'],
        ],
        'sidebar_items' => [
            ['label' => 'Confidential executive search', 'icon' => 'ri-lock-line'],
            ['label' => 'Culture-fit assessment', 'icon' => 'ri-team-line'],
            ['label' => 'Board-ready evaluation reports', 'icon' => 'ri-file-chart-line'],
            ['label' => 'Onboarding coordination', 'icon' => 'ri-rocket-line'],
        ],
        'focus_title' => 'Executive candidate shortlist dashboard — leadership profiles that match your mandate',
        'focus_content' => 'We help you hire leaders who can execute today and scale with your next chapter.',
        'image' => 'assets/frontend/img/leadership/ldr-card-executive-search.png',
        'focus_image' => 'assets/frontend/img/leadership/ldr-deliverable-search.png',
    ],
    'board-ceo-advisory' => [
        'title' => 'Board & CEO Advisory',
        'meta_title' => 'Board & CEO Advisory | Mirashka',
        'meta_description' => 'Strategic advisory for boards, CEOs and growth-focused leadership teams. Governance, performance and planning.',
        'meta_keywords' => 'board advisory, ceo advisory, governance, strategic planning, mirashka',
        'hero_heading' => 'Strategic advisory for boards, CEOs and growth-focused leadership teams',
        'hero_content' => 'We help leadership teams strengthen governance, decision systems, performance reviews, organizational structure and long-term strategic planning.',
        'primary_cta' => 'Speak to a Leadership Advisor',
        'secondary_cta' => 'Start Leadership Readiness Review',
        'process_heading' => 'Advisory rhythm boards and CEOs can rely on',
        'process_steps' => [
            ['title' => 'Board Advisory Scope', 'text' => 'Define governance priorities, risk visibility and meeting cadence.', 'icon' => 'ri-government-line'],
            ['title' => 'CEO Decision Support', 'text' => 'Facilitation on org design, leadership team performance and key decisions.', 'icon' => 'ri-vip-crown-line'],
            ['title' => 'Governance Rhythm', 'text' => 'Agenda design, reporting packs and accountability loops.', 'icon' => 'ri-calendar-event-line'],
            ['title' => 'Performance Review Architecture', 'text' => 'Executive and leadership team review frameworks that drive outcomes.', 'icon' => 'ri-bar-chart-box-line'],
            ['title' => 'Strategic Planning Workshops', 'text' => 'Facilitated sessions aligning people strategy with business priorities.', 'icon' => 'ri-presentation-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Governance', 'content' => 'Board packs, risk dashboards and compliance visibility for directors.'],
            ['label' => 'CEO Support', 'content' => 'Decision frameworks for restructuring, hiring and performance.'],
            ['label' => 'Performance', 'content' => 'Review cadence, KPIs and leadership accountability.'],
            ['label' => 'Strategy', 'content' => 'Workshops connecting growth plans to organization design.'],
        ],
        'sidebar_items' => [
            ['label' => 'Board meeting facilitation support', 'icon' => 'ri-discuss-line'],
            ['label' => 'CEO performance architecture', 'icon' => 'ri-trophy-line'],
            ['label' => 'Governance rhythm design', 'icon' => 'ri-time-line'],
            ['label' => 'Strategic planning workshops', 'icon' => 'ri-lightbulb-line'],
        ],
        'focus_title' => 'Boardroom strategy session with leadership alignment charts',
        'focus_content' => 'Practical advisory that strengthens how your board and CEO lead — not slide decks without follow-through.',
        'image' => 'assets/frontend/img/leadership/ldr-card-board-advisory.png',
        'focus_image' => 'assets/frontend/img/leadership/ldr-board-advisory.png',
    ],
    'ceo-succession-performance-acceleration' => [
        'title' => 'CEO Succession & Performance Acceleration',
        'meta_title' => 'CEO Succession & Performance | Mirashka',
        'meta_description' => 'Structured CEO succession, transition calendars and 90-day performance plans with coaching support.',
        'meta_keywords' => 'ceo succession, leadership transition, performance acceleration, mirashka',
        'hero_heading' => 'Make leadership transitions structured, smooth and performance-led',
        'hero_content' => 'Mirashka helps companies plan CEO succession, transition responsibilities, define performance expectations and support new leaders during the critical early months.',
        'primary_cta' => 'Plan CEO Succession',
        'secondary_cta' => 'Speak to a Leadership Advisor',
        'process_heading' => 'Succession with continuity and measurable early wins',
        'process_steps' => [
            ['title' => 'Succession Readiness Audit', 'text' => 'Assess internal and external successor readiness and risk exposure.', 'icon' => 'ri-search-eye-line'],
            ['title' => 'Successor Role Clarity', 'text' => 'Define mandate, authority, reporting and stakeholder expectations.', 'icon' => 'ri-file-list-3-line'],
            ['title' => 'Transition Calendar', 'text' => 'Phased handover of relationships, decisions and critical initiatives.', 'icon' => 'ri-calendar-line'],
            ['title' => '90-Day Performance Plan', 'text' => 'Prioritized outcomes, metrics and stakeholder communication.', 'icon' => 'ri-flag-line'],
            ['title' => 'Leadership Coaching Support', 'text' => 'Coaching for incoming and outgoing leaders through the transition window.', 'icon' => 'ri-user-voice-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Readiness', 'content' => 'Succession audit with risk flags and recommendation paths.'],
            ['label' => 'Transition', 'content' => 'Calendar of handovers, announcements and stakeholder touchpoints.'],
            ['label' => '90-Day Plan', 'content' => 'Performance priorities with review cadence and success metrics.'],
            ['label' => 'Coaching', 'content' => 'Executive coaching support during the critical early months.'],
        ],
        'sidebar_items' => [
            ['label' => 'Succession readiness audit', 'icon' => 'ri-clipboard-line'],
            ['label' => 'Transition calendar & communications', 'icon' => 'ri-mail-line'],
            ['label' => '90-day performance framework', 'icon' => 'ri-speed-line'],
            ['label' => 'Leadership coaching', 'icon' => 'ri-mental-health-line'],
        ],
        'focus_title' => 'Leadership transition timeline — from announcement to sustained performance',
        'focus_content' => 'We reduce succession risk with structure, empathy and clear performance expectations.',
        'image' => 'assets/frontend/img/leadership/ldr-card-succession.png',
        'focus_image' => 'assets/frontend/img/leadership/ldr-deliverable-succession.png',
    ],
    'leadership-assessment-consulting' => [
        'title' => 'Leadership Assessment & Consulting',
        'meta_title' => 'Leadership Assessment & Consulting | Mirashka',
        'meta_description' => 'Assess leadership capability before critical decisions. Behavioral evaluation and development roadmaps.',
        'meta_keywords' => 'leadership assessment, executive assessment, role readiness, mirashka',
        'hero_heading' => 'Assess leadership capability before making critical decisions',
        'hero_content' => 'We evaluate leadership strengths, gaps, decision maturity, team influence, communication style and role readiness to help companies build stronger leadership pipelines.',
        'primary_cta' => 'Assess Leadership Capability',
        'secondary_cta' => 'Start Leadership Readiness Review',
        'process_heading' => 'Evidence-based leadership decisions',
        'process_steps' => [
            ['title' => 'Leadership Assessment Framework', 'text' => 'Competency model aligned to role level and business context.', 'icon' => 'ri-layout-grid-line'],
            ['title' => 'Behavioral & Strategic Evaluation', 'text' => 'Interviews, tools and scenarios revealing decision and influence patterns.', 'icon' => 'ri-psychotherapy-line'],
            ['title' => 'Role Readiness Mapping', 'text' => 'Fit scoring against mandate, team dynamics and growth stage.', 'icon' => 'ri-map-pin-line'],
            ['title' => 'Development Roadmap', 'text' => 'Targeted coaching, exposure and learning paths for high-potential leaders.', 'icon' => 'ri-road-map-line'],
            ['title' => 'Review with Management', 'text' => 'Facilitated debrief with board or CEO on findings and recommendations.', 'icon' => 'ri-group-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Framework', 'content' => 'Custom competency matrix for your leadership context.'],
            ['label' => 'Evaluation', 'content' => 'Structured assessment with documented evidence.'],
            ['label' => 'Readiness', 'content' => 'Role-fit analysis for promotions and external hires.'],
            ['label' => 'Development', 'content' => 'Individual and pipeline development recommendations.'],
        ],
        'sidebar_items' => [
            ['label' => 'Leadership competency framework', 'icon' => 'ri-grid-line'],
            ['label' => 'Assessment reports for management', 'icon' => 'ri-file-chart-line'],
            ['label' => 'Role readiness scoring', 'icon' => 'ri-star-line'],
            ['label' => 'Development roadmap', 'icon' => 'ri-seedling-line'],
        ],
        'focus_title' => 'Leadership competency matrix — assess before you appoint',
        'focus_content' => 'Reduce costly leadership mismatches with structured assessment and clear development paths.',
        'image' => 'assets/frontend/img/leadership/ldr-card-assessment.png',
        'focus_image' => 'assets/frontend/img/leadership/ldr-card-assessment.png',
    ],
    'hr-talent-strategy-advisory' => [
        'title' => 'HR & Talent Strategy Advisory',
        'meta_title' => 'HR & Talent Strategy Advisory | Mirashka',
        'meta_description' => 'Align people strategy with business strategy. Workforce planning, talent pipelines and culture initiatives.',
        'meta_keywords' => 'talent strategy, workforce planning, hr advisory, people strategy, mirashka',
        'hero_heading' => 'Align people strategy with business strategy',
        'hero_content' => 'Mirashka helps organizations plan workforce structure, talent pipelines, succession layers, performance systems, culture initiatives and hiring roadmaps aligned with business goals.',
        'primary_cta' => 'Build Talent Strategy',
        'secondary_cta' => 'Speak to a Leadership Advisor',
        'process_heading' => 'People strategy your leadership can execute',
        'process_steps' => [
            ['title' => 'Workforce Planning', 'text' => 'Headcount, skills and structure aligned to revenue and expansion plans.', 'icon' => 'ri-team-line'],
            ['title' => 'Talent Gap Analysis', 'text' => 'Identify critical roles, skills shortages and succession vulnerabilities.', 'icon' => 'ri-pie-chart-2-line'],
            ['title' => 'Organization Structure', 'text' => 'Design spans, layers and accountability for the next growth phase.', 'icon' => 'ri-organization-chart'],
            ['title' => 'Culture & Performance Strategy', 'text' => 'Connect values, engagement and performance systems to business outcomes.', 'icon' => 'ri-heart-2-line'],
            ['title' => 'Talent Pipeline Roadmap', 'text' => 'Hiring, development and retention priorities with timelines.', 'icon' => 'ri-route-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Workforce Plan', 'content' => '12–24 month workforce view linked to business milestones.'],
            ['label' => 'Gap Analysis', 'content' => 'Critical role and skills gap visibility for leadership.'],
            ['label' => 'Org Design', 'content' => 'Structure recommendations with transition considerations.'],
            ['label' => 'Roadmap', 'content' => 'Integrated hiring, development and culture action plan.'],
        ],
        'sidebar_items' => [
            ['label' => 'Workforce planning workshop', 'icon' => 'ri-presentation-line'],
            ['label' => 'Talent gap & pipeline analysis', 'icon' => 'ri-filter-3-line'],
            ['label' => 'Organization structure advisory', 'icon' => 'ri-node-tree'],
            ['label' => '12-month talent roadmap', 'icon' => 'ri-calendar-check-line'],
        ],
        'focus_title' => 'People strategy roadmap connecting business goals to hiring and culture',
        'focus_content' => 'We translate strategy into workforce decisions your HR and leadership teams can implement quarter by quarter.',
        'image' => 'assets/frontend/img/leadership/ldr-card-talent-strategy.png',
        'focus_image' => 'assets/frontend/img/leadership/ldr-deliverable-talent.png',
    ],
];

$leadershipSubServices = $subShared('leadership-organization', 'Leadership & Organization', 'Start Leadership Readiness Review', 'Review succession readiness, leadership pipeline gaps and advisory priorities with actionable recommendations.', 'Start Leadership Readiness Review', 'Speak to a Leadership Advisor', 'assets/frontend/img/leadership/ldr-cta-advisory.png', 'assets/frontend/img/leadership/ldr-hero-boardroom.png');
$leadershipSubServices['services'] = [];
foreach ($ldSubs as $slug => $d) {
    $d = apply_sub_service_images($d, 'leadership', $slug);
    $leadershipSubServices['services'][$slug] = apply_sub_extra_sections(build_sub_service($d), $d, 'leadership', $slug);
}

// --- TALENT ACQUISITION ---
$talentCategory = build_category_page([
    'meta_title' => 'Talent Acquisition & Staffing Excellence | Mirashka',
    'meta_description' => 'Flexible, scalable hiring — IT staffing, general staffing, apprenticeships, RPO and executive search focused on quality and fit.',
    'meta_keywords' => 'talent acquisition, it staffing, recruitment, rpo, executive search, mirashka',
    'label' => 'Talent Acquisition & Staffing',
    'title' => 'Talent Acquisition & Staffing Excellence',
    'tagline' => 'Flexible, scalable hiring solutions to power your workforce.',
    'content' => 'Mirashka helps businesses hire faster and smarter through IT staffing, general staffing, apprenticeship support, specialist recruitment, RPO and executive search. We work as an extended hiring engine focused on quality, speed and cultural fit.',
    'headline' => 'Talent matched to your timeline',
    'primary_cta' => 'Start Hiring Support',
    'secondary_cta' => 'Speak to a Hiring Advisor',
    'risk_heading' => 'Good talent is available, but finding fit is difficult',
    'risk_lead' => 'Open roles stay vacant, hiring managers lose time to screening, and mis-hires create costly rework.',
    'risk_content' => 'Mirashka brings structured sourcing, screening and reporting so you hire people who fit skills, culture and timeline — not just résumés.',
    'risks' => [
        'Long time-to-fill on critical roles',
        'Inconsistent screening across hiring managers',
        'Weak employer brand limiting applicant quality',
        'No pipeline for recurring role families',
        'Offer-stage drop-offs without follow-up discipline',
        'Executive hires without structured evaluation',
    ],
    'services_heading' => 'Hiring models for every workforce need',
    'services_content' => 'From IT and general staffing to apprenticeships, specialist recruitment, RPO and executive search — one partner for hiring excellence.',
    'service_items' => [
        ['title' => 'IT Staffing', 'text' => 'Developers, cloud, data, cybersecurity and support engineers deployed with continuity.', 'icon' => 'ri-code-box-line'],
        ['title' => 'General Staffing', 'text' => 'Sales, operations, admin, customer support and field teams across industries.', 'icon' => 'ri-group-line'],
        ['title' => 'NAPS Apprenticeship Support', 'text' => 'Apprenticeship-based workforce models with sourcing and documentation coordination.', 'icon' => 'ri-graduation-cap-line'],
        ['title' => 'IT Recruitment', 'text' => 'Specialist technology hiring with technical evaluation coordination.', 'icon' => 'ri-cpu-line'],
        ['title' => 'Recruitment Process Outsourcing', 'text' => 'End-to-end recruitment operations with dedicated recruiter support.', 'icon' => 'ri-loop-left-line'],
        ['title' => 'Executive Search', 'text' => 'Senior leaders with strategic direction, discipline and cultural alignment.', 'icon' => 'ri-vip-crown-line'],
    ],
    'framework_before' => 'Recruitment Funnel',
    'framework_heading' => 'Source, screen, select, onboard',
    'framework_content' => 'A repeatable hiring funnel with candidate quality standards, interview discipline and weekly visibility.',
    'framework_steps' => [
        ['title' => 'Source', 'subtitle' => 'Pipeline', 'text' => 'Role mapping, channels and curated candidate pipelines.', 'icon' => 'ri-user-search-line'],
        ['title' => 'Screen', 'subtitle' => 'Quality', 'text' => 'Structured screening, skill checks and culture-fit filters.', 'icon' => 'ri-filter-3-line'],
        ['title' => 'Select', 'subtitle' => 'Fit', 'text' => 'Interview coordination, evaluation and offer-stage support.', 'icon' => 'ri-checkbox-circle-line'],
        ['title' => 'Onboard', 'subtitle' => 'Retention', 'text' => 'Joining support, documentation and early retention check-ins.', 'icon' => 'ri-user-add-line'],
    ],
    'integrity_eyebrow' => 'Candidate Quality Framework',
    'integrity_heading' => 'Hire for fit — not just availability',
    'integrity_content' => 'We evaluate skills, motivation, communication and culture alignment so hiring managers spend time only on candidates worth interviewing.',
    'integrity_features' => [
        ['title' => 'Structured screening', 'text' => 'Role-specific scorecards and shortlist discipline before interviews.', 'icon' => 'ri-file-list-3-line'],
        ['title' => 'Hiring dashboards', 'text' => 'Weekly pipeline visibility, SLA tracking and offer-stage follow-up.', 'icon' => 'ri-dashboard-3-line'],
    ],
    'integrity_float_cards' => [
        ['title' => 'Staffing models', 'text' => 'Contract, permanent, RPO and executive search aligned to role urgency.', 'icon' => 'ri-stack-line', 'link' => null],
        ['title' => 'Replacement continuity', 'text' => 'IT staffing replacement support to protect project timelines.', 'icon' => 'ri-refresh-line', 'link' => null],
    ],
    'deliverables_heading' => 'Hiring outputs with speed and accountability',
    'deliverables_content' => 'Shortlists, interview coordination, joining support and hiring reports — not endless inbox threads.',
    'deliverable_cards' => [
        ['style' => 'standard', 'title' => 'Candidate shortlists', 'text' => 'Screened candidates with fit notes and interview readiness.', 'icon' => 'ri-user-follow-line', 'image' => img_at(1), 'bullets' => ['Role requirement mapping', 'Screening scorecards', 'Pipeline reporting']],
        ['style' => 'featured', 'title' => 'RPO hiring command center', 'text' => 'Dedicated recruiter, pipeline management and weekly hiring dashboard.', 'image' => img_at(2)],
        ['style' => 'standard', 'title' => 'Executive search pack', 'text' => 'Confidential outreach, evaluation reports and selection support.', 'icon' => 'ri-briefcase-line', 'image' => img_at(0), 'bullets' => ['Market mapping', 'Confidential outreach', 'Final selection support']],
    ],
    'suitable_heading' => 'For teams that need hiring velocity without chaos',
    'suitable_segments' => [
        ['step' => '01', 'label' => 'Tech Companies', 'icon' => 'ri-code-s-slash-line', 'text' => 'IT staffing and recruitment for product, engineering and support teams.'],
        ['step' => '02', 'label' => 'Operations-Heavy SMEs', 'icon' => 'ri-building-line', 'text' => 'General staffing for sales, field and back-office scale-up.'],
        ['step' => '03', 'label' => 'High-Volume Hiring', 'icon' => 'ri-stack-line', 'text' => 'RPO for consistent funnel management and reporting.'],
        ['step' => '04', 'label' => 'Leadership Teams', 'icon' => 'ri-vip-line', 'text' => 'Executive search for roles that shape business direction.'],
    ],
    'cta_content' => 'Hiring support assessment with role prioritization, channel strategy and recommended staffing model for your timeline.',
    'trust_role' => 'Talent acquisition & staffing specialists',
]);

$taSubs = [
    'it-staffing' => [
        'title' => 'IT Staffing',
        'meta_title' => 'IT Staffing | Mirashka',
        'meta_description' => 'Skilled technology talent for developers, cloud, data, cybersecurity and support roles.',
        'meta_keywords' => 'it staffing, tech staffing, developers, cloud engineers, mirashka',
        'hero_heading' => 'Skilled technology talent for modern business needs',
        'hero_content' => 'Mirashka supports IT staffing for developers, testers, cloud engineers, data specialists, cybersecurity roles, support engineers and emerging technology profiles.',
        'primary_cta' => 'Hire IT Talent',
        'secondary_cta' => 'Start Hiring Support',
        'process_heading' => 'Technology talent deployed with continuity',
        'process_steps' => [
            ['title' => 'Role Requirement Mapping', 'text' => 'Stack, seniority, project context and deployment timeline clarity.', 'icon' => 'ri-file-code-line'],
            ['title' => 'Tech Skill Screening', 'text' => 'Structured technical screening before client interviews.', 'icon' => 'ri-code-box-line'],
            ['title' => 'Candidate Shortlisting', 'text' => 'Curated panels with skill notes and availability.', 'icon' => 'ri-list-check'],
            ['title' => 'Deployment Support', 'text' => 'Joining coordination, documentation and day-one readiness.', 'icon' => 'ri-rocket-line'],
            ['title' => 'Replacement & Continuity', 'text' => 'Backup and replacement protocols to protect delivery timelines.', 'icon' => 'ri-refresh-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Tech Roles', 'content' => 'Developers, QA, DevOps, data and security profiles.'],
            ['label' => 'Screening', 'content' => 'Skill validation aligned to your technical bar.'],
            ['label' => 'Deployment', 'content' => 'Onboarding and project integration support.'],
            ['label' => 'Continuity', 'content' => 'Replacement SLAs and bench strength planning.'],
        ],
        'sidebar_items' => [
            ['label' => 'Full-stack & specialist developers', 'icon' => 'ri-code-s-slash-line'],
            ['label' => 'Cloud & DevOps profiles', 'icon' => 'ri-cloud-line'],
            ['label' => 'Data & cybersecurity talent', 'icon' => 'ri-database-2-line'],
            ['label' => 'Replacement continuity', 'icon' => 'ri-shield-check-line'],
        ],
        'focus_title' => 'Tech talent profile cards — skills matched to your delivery timeline',
        'focus_content' => 'IT staffing that keeps projects moving with vetted technical talent and structured deployment.',
        'image' => 'assets/frontend/img/talent-acquisition/ta-card-it-staffing.png',
        'focus_image' => 'assets/frontend/img/talent-acquisition/ta-card-it-staffing.png',
    ],
    'general-staffing' => [
        'title' => 'General Staffing',
        'meta_title' => 'General Staffing | Mirashka',
        'meta_description' => 'Reliable manpower for sales, operations, admin, customer support and field teams.',
        'meta_keywords' => 'general staffing, manpower, business staffing, mirashka',
        'hero_heading' => 'Reliable manpower for business operations',
        'hero_content' => 'We support hiring for sales, operations, administration, customer support, field teams, back-office, accounts and other non-technical roles across industries.',
        'primary_cta' => 'Build My Workforce',
        'secondary_cta' => 'Start Hiring Support',
        'process_heading' => 'Operational hiring with consistent quality',
        'process_steps' => [
            ['title' => 'Role Understanding', 'text' => 'KPIs, work environment and manager expectations documented upfront.', 'icon' => 'ri-file-text-line'],
            ['title' => 'Candidate Sourcing', 'text' => 'Multi-channel sourcing tuned to location and role family.', 'icon' => 'ri-user-search-line'],
            ['title' => 'Screening & Coordination', 'text' => 'Phone screens, coordination and shortlists hiring managers trust.', 'icon' => 'ri-phone-line'],
            ['title' => 'Joining Support', 'text' => 'Offer follow-up, documentation and day-one communication.', 'icon' => 'ri-user-add-line'],
            ['title' => 'Staffing Reports', 'text' => 'Pipeline and fill-rate reporting for operations leadership.', 'icon' => 'ri-file-chart-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Operations', 'content' => 'Sales, admin, accounts and back-office hiring.'],
            ['label' => 'Customer', 'content' => 'Support and front-line customer-facing roles.'],
            ['label' => 'Field', 'content' => 'Field teams with location and mobility requirements.'],
            ['label' => 'Reporting', 'content' => 'Weekly staffing metrics and open role visibility.'],
        ],
        'sidebar_items' => [
            ['label' => 'Sales & operations hiring', 'icon' => 'ri-briefcase-line'],
            ['label' => 'Customer support staffing', 'icon' => 'ri-customer-service-line'],
            ['label' => 'Field team recruitment', 'icon' => 'ri-map-pin-line'],
            ['label' => 'Staffing performance reports', 'icon' => 'ri-bar-chart-line'],
        ],
        'focus_title' => 'Business operations team — reliable hires for everyday scale',
        'focus_content' => 'General staffing that understands operational roles, not just generic job descriptions.',
        'image' => 'assets/frontend/img/talent-acquisition/ta-card-general-staffing.png',
        'focus_image' => 'assets/frontend/img/talent-acquisition/ta-card-general-staffing.png',
    ],
    'naps-apprenticeship-support' => [
        'title' => 'NAPS Apprenticeship Support',
        'meta_title' => 'NAPS Apprenticeship Support | Mirashka',
        'meta_description' => 'Build future-ready talent through apprenticeship models with sourcing and documentation support.',
        'meta_keywords' => 'naps, apprenticeship hiring, apprentice staffing, mirashka',
        'hero_heading' => 'Build future-ready talent through apprenticeship models',
        'hero_content' => 'Mirashka helps companies explore apprenticeship-based workforce models, candidate sourcing, onboarding support and documentation coordination under NAPS-aligned talent development structures.',
        'primary_cta' => 'Explore Apprenticeship Hiring',
        'secondary_cta' => 'Start Hiring Support',
        'process_heading' => 'Apprenticeship hiring with compliance coordination',
        'process_steps' => [
            ['title' => 'Apprenticeship Need Mapping', 'text' => 'Role families, batch size and training outcomes aligned to operations.', 'icon' => 'ri-compass-3-line'],
            ['title' => 'Candidate Identification', 'text' => 'Sourcing young talent with motivation and basic skill fit.', 'icon' => 'ri-user-search-line'],
            ['title' => 'Documentation Support', 'text' => 'Coordination on NAPS-aligned paperwork and onboarding records.', 'icon' => 'ri-file-paper-2-line'],
            ['title' => 'Training Coordination', 'text' => 'Alignment with training partners and workplace induction schedules.', 'icon' => 'ri-graduation-cap-line'],
            ['title' => 'Reporting Support', 'text' => 'Progress tracking and workforce reporting for program sponsors.', 'icon' => 'ri-bar-chart-box-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Program Design', 'content' => 'Map apprenticeship needs to operational roles and batches.'],
            ['label' => 'Sourcing', 'content' => 'Identify motivated apprentice candidates at scale.'],
            ['label' => 'Documentation', 'content' => 'Support NAPS-aligned documentation and onboarding.'],
            ['label' => 'Reporting', 'content' => 'Training progress and workforce outcome reporting.'],
        ],
        'sidebar_items' => [
            ['label' => 'NAPS-aligned documentation support', 'icon' => 'ri-file-shield-line'],
            ['label' => 'Apprentice candidate sourcing', 'icon' => 'ri-user-add-line'],
            ['label' => 'Training coordination', 'icon' => 'ri-book-open-line'],
            ['label' => 'Program reporting', 'icon' => 'ri-pie-chart-line'],
        ],
        'focus_title' => 'Apprentices in workplace training — building tomorrow\'s workforce today',
        'focus_content' => 'Structured apprenticeship support that connects talent development to real business roles.',
        'image' => 'assets/frontend/img/talent-acquisition/ta-card-naps.png',
        'focus_image' => 'assets/frontend/img/talent-acquisition/ta-card-naps.png',
    ],
    'it-recruitment' => [
        'title' => 'IT Recruitment',
        'meta_title' => 'IT Recruitment | Mirashka',
        'meta_description' => 'Specialist hiring for technology roles with focused sourcing, screening and offer support.',
        'meta_keywords' => 'it recruitment, tech hiring, developer recruitment, mirashka',
        'hero_heading' => 'Specialist hiring for technology and innovation roles',
        'hero_content' => 'Mirashka helps businesses recruit high-quality technology professionals through focused sourcing, screening, technical evaluation coordination and offer-stage support.',
        'primary_cta' => 'Start IT Recruitment',
        'secondary_cta' => 'Hire IT Talent',
        'process_heading' => 'Permanent and specialist tech hiring done right',
        'process_steps' => [
            ['title' => 'Tech Hiring Strategy', 'text' => 'Channel mix, employer pitch and timeline for hard-to-fill roles.', 'icon' => 'ri-lightbulb-line'],
            ['title' => 'Sourcing Channels', 'text' => 'Networks, platforms and referral paths for niche skills.', 'icon' => 'ri-links-line'],
            ['title' => 'Screening Process', 'text' => 'Structured screens before technical interview coordination.', 'icon' => 'ri-filter-line'],
            ['title' => 'Interview Coordination', 'text' => 'Panel scheduling, feedback loops and candidate experience.', 'icon' => 'ri-calendar-check-line'],
            ['title' => 'Offer Closure Support', 'text' => 'Negotiation support and join-date follow-through.', 'icon' => 'ri-handshake-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Strategy', 'content' => 'Hiring plan for critical tech roles and timelines.'],
            ['label' => 'Sourcing', 'content' => 'Targeted outreach for niche technology profiles.'],
            ['label' => 'Interviews', 'content' => 'Coordination and feedback discipline across panels.'],
            ['label' => 'Offers', 'content' => 'Closure support to reduce drop-offs at the finish line.'],
        ],
        'sidebar_items' => [
            ['label' => 'Niche technology sourcing', 'icon' => 'ri-search-eye-line'],
            ['label' => 'Technical screen coordination', 'icon' => 'ri-code-box-line'],
            ['label' => 'Interview scheduling desk', 'icon' => 'ri-calendar-line'],
            ['label' => 'Offer closure support', 'icon' => 'ri-check-double-line'],
        ],
        'focus_title' => 'Tech hiring dashboard — from sourcing to signed offer',
        'focus_content' => 'IT recruitment with the rigor technology leaders expect and the speed growth companies need.',
        'image' => 'assets/frontend/img/talent-acquisition/ta-card-it-recruitment.png',
        'focus_image' => 'assets/frontend/img/talent-acquisition/ta-card-it-recruitment.png',
    ],
    'recruitment-process-outsourcing' => [
        'title' => 'Recruitment Process Outsourcing',
        'meta_title' => 'Recruitment Process Outsourcing (RPO) | Mirashka',
        'meta_description' => 'Your extended recruitment team for full-cycle hiring with dedicated recruiter support.',
        'meta_keywords' => 'rpo, recruitment outsourcing, hiring pipeline, mirashka',
        'hero_heading' => 'Your extended recruitment team for full-cycle hiring',
        'hero_content' => 'Mirashka manages end-to-end recruitment operations including job descriptions, sourcing, screening, interview coordination, candidate communication, tracking and hiring reports.',
        'primary_cta' => 'Outsource Recruitment',
        'secondary_cta' => 'Start Hiring Support',
        'process_heading' => 'RPO that feels in-house — with external scale',
        'process_steps' => [
            ['title' => 'RPO Engagement Model', 'text' => 'Scope, SLAs, roles in scope and reporting cadence agreed upfront.', 'icon' => 'ri-contract-line'],
            ['title' => 'Dedicated Recruiter Support', 'text' => 'Named recruiters embedded in your hiring rhythm.', 'icon' => 'ri-user-star-line'],
            ['title' => 'Hiring Pipeline Management', 'text' => 'Stage discipline, aging alerts and candidate communication.', 'icon' => 'ri-git-branch-line'],
            ['title' => 'Interview & Follow-up System', 'text' => 'Scheduling, reminders and feedback capture every time.', 'icon' => 'ri-calendar-event-line'],
            ['title' => 'Weekly Hiring Dashboard', 'text' => 'Open roles, funnel metrics and offer pipeline for leadership.', 'icon' => 'ri-dashboard-3-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Engagement', 'content' => 'RPO model tailored to volume, roles and hiring managers.'],
            ['label' => 'Pipeline', 'content' => 'Full-funnel tracking with SLA accountability.'],
            ['label' => 'Coordination', 'content' => 'Interview and candidate communication managed end-to-end.'],
            ['label' => 'Dashboard', 'content' => 'Weekly hiring command center for leadership.'],
        ],
        'sidebar_items' => [
            ['label' => 'Dedicated recruiter team', 'icon' => 'ri-team-line'],
            ['label' => 'JD writing & job marketing', 'icon' => 'ri-article-line'],
            ['label' => 'Candidate communication desk', 'icon' => 'ri-mail-send-line'],
            ['label' => 'Weekly hiring dashboard', 'icon' => 'ri-bar-chart-grouped-line'],
        ],
        'focus_title' => 'Recruitment command center — full-cycle hiring visibility',
        'focus_content' => 'RPO that gives you recruiting capacity without building a large internal team overnight.',
        'image' => 'assets/frontend/img/talent-acquisition/ta-card-rpo.png',
        'focus_image' => 'assets/frontend/img/talent-acquisition/ta-deliverable-rpo.png',
    ],
    'executive-search' => [
        'title' => 'Executive Search',
        'meta_title' => 'Executive Search | Mirashka',
        'meta_description' => 'Leadership hiring for roles that shape the business. Confidential outreach and structured evaluation.',
        'meta_keywords' => 'executive search, senior leadership hiring, c-suite hiring, mirashka',
        'hero_heading' => 'Leadership hiring for roles that shape the business',
        'hero_content' => 'We identify and place senior leaders who can bring strategic direction, operational discipline, cultural alignment and measurable business impact.',
        'primary_cta' => 'Begin Executive Search',
        'secondary_cta' => 'Speak to a Leadership Advisor',
        'process_heading' => 'Confidential search for business-critical leaders',
        'process_steps' => [
            ['title' => 'Leadership Mandate Understanding', 'text' => 'Strategic outcomes, stakeholder map and success profile.', 'icon' => 'ri-focus-3-line'],
            ['title' => 'Market Mapping', 'text' => 'Target sectors, companies and passive candidate landscapes.', 'icon' => 'ri-global-line'],
            ['title' => 'Confidential Outreach', 'text' => 'Discreet approach to high-caliber leaders not on job boards.', 'icon' => 'ri-lock-line'],
            ['title' => 'Evaluation & Shortlisting', 'text' => 'Structured assessment and board-ready comparison reports.', 'icon' => 'ri-file-chart-line'],
            ['title' => 'Final Selection Support', 'text' => 'References, offer alignment and onboarding transition.', 'icon' => 'ri-checkbox-circle-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Mandate', 'content' => 'Define what success looks like for the role and the business.'],
            ['label' => 'Market', 'content' => 'Mapping and long-list development with confidentiality.'],
            ['label' => 'Evaluate', 'content' => 'Assessment and shortlist discipline.'],
            ['label' => 'Close', 'content' => 'Selection support through offer and transition.'],
        ],
        'sidebar_items' => [
            ['label' => 'Confidential executive outreach', 'icon' => 'ri-lock-2-line'],
            ['label' => 'Board-ready assessment reports', 'icon' => 'ri-file-chart-line'],
            ['label' => 'Strategic fit evaluation', 'icon' => 'ri-star-line'],
            ['label' => 'Transition & onboarding support', 'icon' => 'ri-rocket-line'],
        ],
        'focus_title' => 'Senior leader profile selection — leaders who shape outcomes',
        'focus_content' => 'Executive search for roles where the wrong hire is far costlier than the search investment.',
        'image' => 'assets/frontend/img/talent-acquisition/ta-card-executive-search.png',
        'focus_image' => 'assets/frontend/img/talent-acquisition/ta-deliverable-executive.png',
    ],
];

$talentSubServices = $subShared('talent-acquisition', 'Talent Acquisition & Staffing', 'Start Hiring Support', 'Hiring assessment with role prioritization, recommended channels and staffing model for your timeline and budget.', 'Start Hiring Support', 'Speak to a Hiring Advisor', 'assets/frontend/img/talent-acquisition/ta-cta-hiring.png', 'assets/frontend/img/talent-acquisition/ta-hero-hiring.png');
$talentSubServices['services'] = [];
foreach ($taSubs as $slug => $d) {
    $d = apply_sub_service_images($d, 'talent-acquisition', $slug);
    $talentSubServices['services'][$slug] = apply_sub_extra_sections(build_sub_service($d), $d, 'talent-acquisition', $slug);
}

// --- HR AS A SERVICE ---
$hraasCategory = build_category_page([
    'meta_title' => 'HR as a Service | Mirashka',
    'meta_description' => 'Your dedicated HR partner on demand. HR outsourcing, employer branding, engagement, surveys and HR technology.',
    'meta_keywords' => 'hr as a service, hraas, hr outsourcing, employer branding, employee engagement, mirashka',
    'label' => 'HR as a Service',
    'title' => 'HR as a Service',
    'tagline' => 'Your dedicated HR partner, on demand.',
    'content' => 'Mirashka HRaaS gives businesses access to a complete HR function without building a full internal department from day one. We manage HR operations, hiring support, employer branding, engagement, surveys, retention and HR technology implementation through a flexible service model.',
    'headline' => 'A complete HR office without the full-time overhead',
    'primary_cta' => 'Build My HRaaS Plan',
    'secondary_cta' => 'Speak to an HR Advisor',
    'risk_before' => 'Why HRaaS',
    'risk_heading' => 'Scale people systems as the business grows',
    'risk_lead' => 'Building a full HR department too early is expensive; waiting too long creates compliance, culture and hiring risk.',
    'risk_content' => 'HR as a Service gives you flexible capacity — operations, branding, engagement and technology — scaled to your stage and growth plan.',
    'risks' => [
        'HR leader hire delayed but workload is not',
        'Employer brand weak while competitors attract talent',
        'No pulse on engagement or retention drivers',
        'HR tools purchased but not adopted',
        'Hiring support inconsistent month to month',
        'Leadership lacks monthly people metrics',
    ],
    'services_heading' => 'Full HR function — modular and flexible',
    'services_content' => 'Outsourcing, branding, sourcing, engagement, surveys and HR tech — compose the HR office you need today and expand tomorrow.',
    'service_items' => [
        ['title' => 'HR Outsourcing', 'text' => 'Day-to-day HR operations, lifecycle support and monthly reviews.', 'icon' => 'ri-building-line'],
        ['title' => 'Employer Branding', 'text' => 'EVP, career content and social hiring that attracts the right people.', 'icon' => 'ri-megaphone-line'],
        ['title' => 'Candidate Sourcing', 'text' => 'Curated pipelines by role, skill, location and culture fit.', 'icon' => 'ri-user-search-line'],
        ['title' => 'Employee Engagement & Performance', 'text' => 'Programs, KRAs, review cadence and manager feedback loops.', 'icon' => 'ri-emotion-happy-line'],
        ['title' => 'Employee Surveys & Retention', 'text' => 'Pulse checks, exit analysis and retention action planning.', 'icon' => 'ri-survey-line'],
        ['title' => 'HR Technology Solutions', 'text' => 'Tool selection, implementation and workflow automation.', 'icon' => 'ri-computer-line'],
    ],
    'framework_before' => 'HRaaS Operating Model',
    'framework_heading' => 'Partner, operate, measure, improve',
    'framework_content' => 'A flexible HRaaS rhythm with dedicated partner support, monthly reporting and continuous improvement.',
    'framework_steps' => [
        ['title' => 'Partner', 'subtitle' => 'Dedicated', 'text' => 'Named HR partner aligned to your business context and growth stage.', 'icon' => 'ri-user-heart-line'],
        ['title' => 'Operate', 'subtitle' => 'Delivery', 'text' => 'HR ops, hiring support, branding and engagement modules as needed.', 'icon' => 'ri-settings-3-line'],
        ['title' => 'Measure', 'subtitle' => 'Insight', 'text' => 'Monthly reporting on workforce, hiring, engagement and compliance.', 'icon' => 'ri-bar-chart-box-line'],
        ['title' => 'Improve', 'subtitle' => 'Scale', 'text' => 'Quarterly reviews to add modules, tools and capacity as you grow.', 'icon' => 'ri-arrow-up-line'],
    ],
    'integrity_eyebrow' => 'Dedicated HR Partner',
    'integrity_heading' => 'Human expertise with operational discipline',
    'integrity_content' => 'Your HRaaS partner combines advisory judgment with structured delivery — so people operations keep pace with business ambition.',
    'integrity_features' => [
        ['title' => 'Monthly HR review', 'text' => 'Leadership-ready reporting on workforce priorities and risks.', 'icon' => 'ri-calendar-check-line'],
        ['title' => 'Modular engagement', 'text' => 'Start with what you need; expand into branding, tech and engagement.', 'icon' => 'ri-stack-line'],
    ],
    'integrity_float_cards' => [
        ['title' => 'Plans & engagement models', 'text' => 'Flexible scopes from startup HR desk to scaled HRaaS.', 'icon' => 'ri-price-tag-3-line', 'link' => null],
        ['title' => 'HR technology layer', 'text' => 'Tools and automation that make service delivery visible.', 'icon' => 'ri-apps-line', 'link' => null],
    ],
    'deliverables_heading' => 'HR office outputs — without building everything in-house',
    'deliverables_content' => 'Operations packs, brand assets, engagement frameworks, survey insights and tech roadmaps — delivered as a service.',
    'deliverable_cards' => [
        ['style' => 'standard', 'title' => 'HR operations pack', 'text' => 'Lifecycle support, documentation, payroll coordination and monthly review.', 'icon' => 'ri-folder-shield-line', 'image' => img_at(1), 'bullets' => ['Employee lifecycle support', 'Documentation management', 'Monthly HR review']],
        ['style' => 'featured', 'title' => 'Employer brand & engagement', 'text' => 'EVP, career content, performance frameworks and pulse insights.', 'image' => img_at(5)],
        ['style' => 'standard', 'title' => 'HR technology roadmap', 'text' => 'Assessment, tool selection, implementation and analytics setup.', 'icon' => 'ri-cpu-line', 'image' => img_at(3), 'bullets' => ['HR tech assessment', 'Implementation roadmap', 'Workflow automation']],
    ],
    'suitable_heading' => 'For businesses building HR without a large internal team',
    'suitable_segments' => [
        ['step' => '01', 'label' => 'Startups', 'icon' => 'ri-rocket-line', 'text' => 'Foundational HR office — ops, hiring support and compliance rhythm.'],
        ['step' => '02', 'label' => 'SMEs', 'icon' => 'ri-building-2-line', 'text' => 'Scale HR capacity with branding, engagement and reporting.'],
        ['step' => '03', 'label' => 'High-Growth Teams', 'icon' => 'ri-line-chart-line', 'text' => 'Modular HRaaS that expands with headcount and complexity.'],
        ['step' => '04', 'label' => 'HR-Light Organizations', 'icon' => 'ri-team-line', 'text' => 'Complete HR function on demand without full-time overhead.'],
    ],
    'cta_content' => 'Build a tailored HRaaS plan — scope, modules, reporting rhythm and technology priorities aligned to your growth stage.',
    'trust_role' => 'HR as a Service specialists',
]);

$hrSubs = [
    'hr-outsourcing' => [
        'title' => 'HR Outsourcing',
        'meta_title' => 'HR Outsourcing | Mirashka',
        'meta_description' => 'Outsource HR operations without losing control. Lifecycle, payroll coordination and monthly reviews.',
        'meta_keywords' => 'hr outsourcing, hr operations, employee lifecycle, mirashka hraas',
        'hero_heading' => 'Outsource your HR function without losing control',
        'hero_content' => 'Mirashka manages day-to-day HR operations including documentation, employee lifecycle support, payroll coordination, compliance follow-ups, onboarding, exits and HR reporting.',
        'primary_cta' => 'Outsource HR Operations',
        'secondary_cta' => 'Build My HRaaS Plan',
        'process_heading' => 'Controlled outsourcing with leadership visibility',
        'process_steps' => [
            ['title' => 'HR Outsourcing Scope', 'text' => 'Define modules, authority levels and escalation paths with leadership.', 'icon' => 'ri-file-list-3-line'],
            ['title' => 'Employee Lifecycle Support', 'text' => 'Hire-to-retire coordination with documented checkpoints.', 'icon' => 'ri-loop-left-line'],
            ['title' => 'Payroll & Compliance Coordination', 'text' => 'Payroll inputs, statutory follow-ups and register hygiene.', 'icon' => 'ri-shield-check-line'],
            ['title' => 'Documentation Management', 'text' => 'Contracts, policies, acknowledgements and employee files.', 'icon' => 'ri-folder-shield-line'],
            ['title' => 'Monthly HR Review', 'text' => 'Leadership session on workforce metrics, risks and priorities.', 'icon' => 'ri-calendar-check-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Operations', 'content' => 'Day-to-day HR desk for employee and manager queries.'],
            ['label' => 'Lifecycle', 'content' => 'Onboarding, changes, exits and documentation.'],
            ['label' => 'Compliance', 'content' => 'Follow-ups, filings support and audit readiness.'],
            ['label' => 'Reporting', 'content' => 'Monthly HR summary leadership can act on.'],
        ],
        'sidebar_items' => [
            ['label' => 'Dedicated HR outsourcing desk', 'icon' => 'ri-customer-service-line'],
            ['label' => 'Payroll & compliance coordination', 'icon' => 'ri-money-dollar-circle-line'],
            ['label' => 'Documentation control', 'icon' => 'ri-file-shield-2-line'],
            ['label' => 'Monthly leadership review', 'icon' => 'ri-presentation-line'],
        ],
        'focus_title' => 'External HR desk with process dashboard — control without building a department',
        'focus_content' => 'HR outsourcing that keeps founders informed and employees supported every day.',
    ],
    'employer-branding' => [
        'title' => 'Employer Branding',
        'meta_title' => 'Employer Branding | Mirashka',
        'meta_description' => 'Position your company where good people want to work. EVP, career pages and employee storytelling.',
        'meta_keywords' => 'employer branding, evp, career page, hiring brand, mirashka',
        'hero_heading' => 'Position your company as a place where good people want to work',
        'hero_content' => 'We help businesses communicate their culture, growth opportunities, leadership vision, employee stories and workplace strengths across hiring channels and digital platforms.',
        'primary_cta' => 'Build Employer Brand',
        'secondary_cta' => 'Build My HRaaS Plan',
        'process_heading' => 'Employer brand that attracts fit — not just volume',
        'process_steps' => [
            ['title' => 'Employer Brand Audit', 'text' => 'Review careers touchpoints, messaging and competitor positioning.', 'icon' => 'ri-search-eye-line'],
            ['title' => 'EVP Development', 'text' => 'Define employee value proposition authentic to your culture.', 'icon' => 'ri-heart-line'],
            ['title' => 'Career Page Content', 'text' => 'Roles, culture proof points and conversion-focused careers content.', 'icon' => 'ri-window-line'],
            ['title' => 'Social Hiring Content', 'text' => 'Posts, campaigns and stories that reach passive candidates.', 'icon' => 'ri-share-line'],
            ['title' => 'Employee Storytelling', 'text' => 'Real stories and visuals that build trust with applicants.', 'icon' => 'ri-chat-quote-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Audit', 'content' => 'Gap analysis across careers site, social and hiring collateral.'],
            ['label' => 'EVP', 'content' => 'Messaging framework for culture, growth and leadership.'],
            ['label' => 'Careers', 'content' => 'Career page structure and content that converts.'],
            ['label' => 'Stories', 'content' => 'Employee stories for social and interview conversations.'],
        ],
        'sidebar_items' => [
            ['label' => 'Employer brand audit', 'icon' => 'ri-clipboard-line'],
            ['label' => 'EVP & messaging framework', 'icon' => 'ri-megaphone-line'],
            ['label' => 'Career page content', 'icon' => 'ri-layout-line'],
            ['label' => 'Social hiring campaigns', 'icon' => 'ri-instagram-line'],
        ],
        'focus_title' => 'Career page mockup with employee testimonials — brand candidates believe',
        'focus_content' => 'Employer branding that makes your hiring story consistent, credible and differentiated.',
    ],
    'candidate-sourcing' => [
        'title' => 'Candidate Sourcing',
        'meta_title' => 'Candidate Sourcing | Mirashka',
        'meta_description' => 'Curated candidate pipelines for your hiring needs. Research, shortlists and pipeline reporting.',
        'meta_keywords' => 'candidate sourcing, recruitment pipeline, talent sourcing, mirashka',
        'hero_heading' => 'Curated candidate pipelines for your hiring needs',
        'hero_content' => 'Mirashka identifies and builds relevant candidate pipelines based on role requirements, skill fit, location, salary expectations and organizational culture.',
        'primary_cta' => 'Source Candidates',
        'secondary_cta' => 'Start Hiring Support',
        'process_heading' => 'Pipelines built before urgency hits',
        'process_steps' => [
            ['title' => 'Role Mapping', 'text' => 'Skills, experience band, location and compensation alignment.', 'icon' => 'ri-map-2-line'],
            ['title' => 'Candidate Research', 'text' => 'Targeted search across networks, databases and referrals.', 'icon' => 'ri-search-line'],
            ['title' => 'Shortlist Creation', 'text' => 'Screened candidates with fit notes for hiring managers.', 'icon' => 'ri-list-check-2'],
            ['title' => 'Screening Support', 'text' => 'Phone screens and coordination before client interviews.', 'icon' => 'ri-phone-line'],
            ['title' => 'Pipeline Reporting', 'text' => 'Weekly pipeline health, aging and conversion metrics.', 'icon' => 'ri-bar-chart-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Mapping', 'content' => 'Role definitions and sourcing strategy per hire family.'],
            ['label' => 'Research', 'content' => 'Active and passive candidate identification.'],
            ['label' => 'Shortlist', 'content' => 'Ready-to-interview panels with screening notes.'],
            ['label' => 'Pipeline', 'content' => 'Reporting on volume, quality and time-to-shortlist.'],
        ],
        'sidebar_items' => [
            ['label' => 'Role-based pipeline building', 'icon' => 'ri-filter-3-line'],
            ['label' => 'Screened shortlists', 'icon' => 'ri-user-follow-line'],
            ['label' => 'Passive candidate outreach', 'icon' => 'ri-mail-line'],
            ['label' => 'Weekly pipeline reports', 'icon' => 'ri-file-chart-line'],
        ],
        'focus_title' => 'Candidate database with filters and shortlist tags',
        'focus_content' => 'Sourcing that gives hiring managers head start — not a blank inbox when roles open.',
    ],
    'employee-engagement-performance' => [
        'title' => 'Employee Engagement & Performance',
        'meta_title' => 'Employee Engagement & Performance | Mirashka',
        'meta_description' => 'Engagement programs, performance frameworks, KRAs and feedback systems that improve productivity and retention.',
        'meta_keywords' => 'employee engagement, performance management, kra design, mirashka',
        'hero_heading' => 'Keep teams aligned, motivated and accountable',
        'hero_content' => 'We design engagement programs, performance review structures, goal-setting frameworks, feedback systems and manager communication routines to improve employee productivity and retention.',
        'primary_cta' => 'Improve Team Performance',
        'secondary_cta' => 'Build My HRaaS Plan',
        'process_heading' => 'Engagement and performance that managers actually use',
        'process_steps' => [
            ['title' => 'Engagement Diagnostic', 'text' => 'Baseline on drivers, manager practices and team sentiment.', 'icon' => 'ri-pulse-line'],
            ['title' => 'Performance Framework', 'text' => 'Review cycles, ratings approach and documentation standards.', 'icon' => 'ri-award-line'],
            ['title' => 'Goal & KRA Design', 'text' => 'Cascading goals aligned to business outcomes and role clarity.', 'icon' => 'ri-focus-2-line'],
            ['title' => 'Review Cadence', 'text' => 'Monthly check-ins, quarterly reviews and annual summaries.', 'icon' => 'ri-calendar-event-line'],
            ['title' => 'Feedback Loops', 'text' => '360, peer and upward feedback where appropriate.', 'icon' => 'ri-feedback-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Engagement', 'content' => 'Programs, rituals and communications that build belonging.'],
            ['label' => 'Goals', 'content' => 'KRA templates and goal libraries by role family.'],
            ['label' => 'Reviews', 'content' => 'Performance review workflows and manager guides.'],
            ['label' => 'Feedback', 'content' => 'Continuous feedback tools and team routines.'],
        ],
        'sidebar_items' => [
            ['label' => 'Engagement program design', 'icon' => 'ri-emotion-line'],
            ['label' => 'KRA & goal frameworks', 'icon' => 'ri-target-line'],
            ['label' => 'Performance review system', 'icon' => 'ri-file-chart-line'],
            ['label' => 'Manager communication playbooks', 'icon' => 'ri-book-open-line'],
        ],
        'focus_title' => 'Team performance dashboard with goals and feedback',
        'focus_content' => 'Practical engagement and performance systems — not annual paperwork exercises alone.',
    ],
    'employee-surveys-retention' => [
        'title' => 'Employee Surveys & Retention',
        'meta_title' => 'Employee Surveys & Retention | Mirashka',
        'meta_description' => 'Listen early with pulse checks, satisfaction studies, exit analysis and retention action plans.',
        'meta_keywords' => 'employee surveys, retention strategy, exit interviews, pulse survey, mirashka',
        'hero_heading' => 'Listen early. Act before good people leave.',
        'hero_content' => 'Mirashka creates employee surveys, pulse checks, satisfaction studies, exit analysis and retention action plans to help leadership understand workforce sentiment.',
        'primary_cta' => 'Run Employee Survey',
        'secondary_cta' => 'Build My HRaaS Plan',
        'process_heading' => 'From sentiment data to retention action',
        'process_steps' => [
            ['title' => 'Survey Design', 'text' => 'Questions aligned to drivers of engagement and retention risk.', 'icon' => 'ri-survey-line'],
            ['title' => 'Employee Pulse Checks', 'text' => 'Lightweight frequent pulses between annual studies.', 'icon' => 'ri-pulse-line'],
            ['title' => 'Retention Risk Analysis', 'text' => 'Identify teams and roles with elevated flight risk.', 'icon' => 'ri-alert-line'],
            ['title' => 'Exit Feedback Review', 'text' => 'Structured exit interviews and theme analysis.', 'icon' => 'ri-door-open-line'],
            ['title' => 'Action Planning', 'text' => 'Leadership workshops turning insights into owned initiatives.', 'icon' => 'ri-task-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Surveys', 'content' => 'Annual and pulse survey programs with anonymity norms.'],
            ['label' => 'Analysis', 'content' => 'Heat maps, themes and manager-level insights.'],
            ['label' => 'Exit', 'content' => 'Exit interview protocols and trend reporting.'],
            ['label' => 'Action', 'content' => 'Retention plans with owners and timelines.'],
        ],
        'sidebar_items' => [
            ['label' => 'Custom survey design', 'icon' => 'ri-questionnaire-line'],
            ['label' => 'Pulse check programs', 'icon' => 'ri-heart-pulse-line'],
            ['label' => 'Exit interview analysis', 'icon' => 'ri-chat-poll-line'],
            ['label' => 'Retention action workshops', 'icon' => 'ri-group-line'],
        ],
        'focus_title' => 'Employee sentiment dashboard with satisfaction and risk scores',
        'focus_content' => 'Surveys that drive decisions — not reports that sit unread on shared drives.',
    ],
    'hr-technology-solutions' => [
        'title' => 'HR Technology Solutions',
        'meta_title' => 'HR Technology Solutions | Mirashka',
        'meta_description' => 'Digitize HR with tool selection, implementation, workflow automation and analytics.',
        'meta_keywords' => 'hr technology, hr software, hr automation, hr analytics, mirashka',
        'hero_heading' => 'Digitize HR processes with the right tools and workflows',
        'hero_content' => 'Mirashka helps companies select, implement and optimize HR software, recruitment tools, employee databases, HR analytics dashboards and automation workflows.',
        'primary_cta' => 'Digitize My HR',
        'secondary_cta' => 'Build My HRaaS Plan',
        'process_heading' => 'HR tech that teams adopt — not shelfware',
        'process_steps' => [
            ['title' => 'HR Tech Need Assessment', 'text' => 'Map processes, pain points and integration requirements.', 'icon' => 'ri-search-eye-line'],
            ['title' => 'Tool Selection Support', 'text' => 'Shortlist vendors against budget, scale and India compliance needs.', 'icon' => 'ri-apps-line'],
            ['title' => 'Implementation Roadmap', 'text' => 'Phased rollout, data migration and change communication.', 'icon' => 'ri-road-map-line'],
            ['title' => 'Workflow Automation', 'text' => 'Automate onboarding, leave, approvals and hiring handoffs.', 'icon' => 'ri-flow-chart'],
            ['title' => 'Analytics & Reporting', 'text' => 'Dashboards leadership and HR use every month.', 'icon' => 'ri-bar-chart-box-line'],
        ],
        'dash_tabs' => [
            ['label' => 'Assessment', 'content' => 'Current-state process and tool gap analysis.'],
            ['label' => 'Selection', 'content' => 'Vendor comparison and recommendation memo.'],
            ['label' => 'Implement', 'content' => 'Rollout plan, training and adoption support.'],
            ['label' => 'Automate', 'content' => 'Workflow design connecting HR, hiring and payroll.'],
        ],
        'sidebar_items' => [
            ['label' => 'HR tech needs assessment', 'icon' => 'ri-clipboard-line'],
            ['label' => 'Vendor selection support', 'icon' => 'ri-store-2-line'],
            ['label' => 'Implementation & training', 'icon' => 'ri-graduation-cap-line'],
            ['label' => 'HR analytics dashboards', 'icon' => 'ri-dashboard-line'],
        ],
        'focus_title' => 'HR tech stack visual with connected apps and automation flows',
        'focus_content' => 'Technology advisory grounded in how Indian SMEs actually hire, pay and engage people.',
    ],
];

$hraasSubServices = $subShared('hr-as-a-service', 'HR as a Service', 'Build My HRaaS Plan', 'Tailored HRaaS scope with modules, reporting rhythm and technology priorities for your growth stage.', 'Build My HRaaS Plan', 'Speak to an HR Advisor', 'assets/frontend/img/hraas/hraas-v3-cta-person.png', 'assets/frontend/img/hraas/hraas-v3-cta-bg.png');
$hraasSubServices['services'] = [];
foreach ($hrSubs as $slug => $d) {
    $d = apply_sub_service_images($d, 'hraas', $slug);
    $hraasSubServices['services'][$slug] = apply_sub_extra_sections(build_sub_service($d), $d, 'hraas', $slug);
}
