<?php

/**
 * Content-aligned images for What We Do sub-service pages.
 * Each page: hero, focus, card (nav/related only), steps[] (dashboard tabs).
 * No image repeats within a single page (hero/focus/tabs/bottom_cta are distinct).
 */
return [
    'compliance' => [
        'expert-legal-hr-consultations' => [
            'hero' => 'assets/frontend/img/compliance/cwi-hero.png',
            'focus' => 'assets/frontend/img/compliance/cwi-integrity.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/compliance/cwi-card-legal.png',
            'steps' => [
                'assets/frontend/img/compliance/cwi-services.png',
                'assets/frontend/img/compliance/cwi-risk.png',
                'assets/frontend/img/compliance/cwi-deliverable-audit.png',
                'assets/frontend/img/compliance/cwi-deliverable-policy.png',
            ],
            'bottom_cta' => 'assets/frontend/img/compliance/cwi-card-legal.png',
        ],
        'policy-documentation-excellence' => [
            'hero' => 'assets/frontend/img/compliance/cwi-card-policy.png',
            'focus' => 'assets/frontend/img/compliance/cwi-deliverable-policy.png',
            'focus_position' => 'center top',
            'card' => 'assets/frontend/img/compliance/cwi-card-policy.png',
            'steps' => [
                'assets/frontend/img/compliance/cwi-hero.png',
                'assets/frontend/img/compliance/cwi-card-legal.png',
                'assets/frontend/img/compliance/cwi-integrity.png',
                'assets/frontend/img/compliance/cwi-services.png',
                'assets/frontend/img/compliance/cwi-risk.png',
            ],
            'bottom_cta' => 'assets/frontend/img/compliance/cwi-deliverable-audit.png',
        ],
        'compliance-risk-assessments' => [
            'hero' => 'assets/frontend/img/compliance/cwi-card-audit.png',
            'focus' => 'assets/frontend/img/compliance/cwi-deliverable-audit.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/compliance/cwi-card-audit.png',
            'steps' => [
                'assets/frontend/img/compliance/cwi-risk.png',
                'assets/frontend/img/compliance/cwi-hero.png',
                'assets/frontend/img/compliance/cwi-integrity.png',
                'assets/frontend/img/compliance/cwi-services.png',
                'assets/frontend/img/compliance/cwi-card-legal.png',
            ],
            'bottom_cta' => 'assets/frontend/img/compliance/cwi-deliverable-policy.png',
        ],
        'workplace-ethics-training' => [
            'hero' => 'assets/frontend/img/compliance/cwi-card-training.png',
            'focus' => 'assets/frontend/img/compliance/cwi-deliverable-training.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/compliance/cwi-card-training.png',
            'steps' => [
                'assets/frontend/img/compliance/cwi-integrity.png',
                'assets/frontend/img/compliance/cwi-hero.png',
                'assets/frontend/img/compliance/cwi-services.png',
                'assets/frontend/img/compliance/cwi-risk.png',
                'assets/frontend/img/compliance/cwi-card-audit.png',
            ],
            'bottom_cta' => 'assets/frontend/img/compliance/cwi-card-legal.png',
        ],
    ],
    'workforce' => [
        'policy-design-compliance-audit' => [
            'hero' => 'assets/frontend/img/workforce/wfm-hero.png',
            'focus' => 'assets/frontend/img/workforce/wfm-card-policy.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/workforce/wfm-card-policy.png',
            'steps' => [
                'assets/frontend/img/workforce/wfm-services-center.png',
                'assets/frontend/img/workforce/wfm-risk.png',
                'assets/frontend/img/workforce/wfm-reporting-team-work.png',
                'assets/frontend/img/workforce/wfm-reporting-team-hands.png',
                'assets/frontend/img/workforce/wfm-remote-feature.png',
            ],
            'bottom_cta' => 'assets/frontend/img/workforce/wfm-card-remote.png',
        ],
        'payroll-outsourcing-administration' => [
            'hero' => 'assets/frontend/img/workforce/wfm-hero.png',
            'focus' => 'assets/frontend/img/workforce/wfm-payroll-v2-salary.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/workforce/wfm-card-payroll.png',
            'steps' => [
                'assets/frontend/img/workforce/wfm-payroll-v2-input.png',
                'assets/frontend/img/workforce/wfm-payroll-tab-salary.png',
                'assets/frontend/img/workforce/wfm-payroll-tab-records.png',
                'assets/frontend/img/workforce/wfm-payroll-tab-queries.png',
                'assets/frontend/img/workforce/wfm-reporting-team-work.png',
            ],
            'bottom_cta' => 'assets/frontend/img/workforce/wfm-cta-person-v2.png',
        ],
        'remote-hr-solutions' => [
            'hero' => 'assets/frontend/img/workforce/wfm-card-remote.png',
            'focus' => 'assets/frontend/img/workforce/wfm-remote-feature.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/workforce/wfm-card-remote.png',
            'steps' => [
                'assets/frontend/img/workforce/wfm-reporting-team-hands.png',
                'assets/frontend/img/workforce/wfm-reporting-team-work.png',
                'assets/frontend/img/workforce/wfm-payroll-tab-records.png',
                'assets/frontend/img/workforce/wfm-services-center.png',
                'assets/frontend/img/workforce/wfm-risk.png',
            ],
            'bottom_cta' => 'assets/frontend/img/workforce/wfm-card-policy.png',
        ],
    ],
    'leadership' => [
        'executive-search-leadership-hiring' => [
            'hero' => 'assets/frontend/img/leadership/ldr-hero-boardroom.png',
            'focus' => 'assets/frontend/img/leadership/ldr-deliverable-search.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/leadership/ldr-card-executive-search.png',
            'steps' => [
                'assets/frontend/img/leadership/ldr-card-executive-search.png',
                'assets/frontend/img/leadership/ldr-services-lifecycle.png',
                'assets/frontend/img/leadership/ldr-board-advisory.png',
                'assets/frontend/img/leadership/ldr-cta-advisory.png',
                'assets/frontend/img/leadership/ldr-risk-org-growth.png',
            ],
            'bottom_cta' => 'assets/frontend/img/leadership/ldr-deliverable-succession.png',
        ],
        'board-ceo-advisory' => [
            'hero' => 'assets/frontend/img/leadership/ldr-board-advisory.png',
            'focus' => 'assets/frontend/img/leadership/ldr-cta-advisory.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/leadership/ldr-card-board-advisory.png',
            'steps' => [
                'assets/frontend/img/leadership/ldr-hero-boardroom.png',
                'assets/frontend/img/leadership/ldr-card-board-advisory.png',
                'assets/frontend/img/leadership/ldr-services-lifecycle.png',
                'assets/frontend/img/leadership/ldr-deliverable-talent.png',
                'assets/frontend/img/leadership/ldr-risk-org-growth.png',
            ],
            'bottom_cta' => 'assets/frontend/img/leadership/ldr-deliverable-search.png',
        ],
        'ceo-succession-performance-acceleration' => [
            'hero' => 'assets/frontend/img/leadership/ldr-hero-boardroom.png',
            'focus' => 'assets/frontend/img/leadership/ldr-deliverable-succession.png',
            'focus_position' => 'center 35%',
            'card' => 'assets/frontend/img/leadership/ldr-card-succession.png',
            'steps' => [
                'assets/frontend/img/leadership/ldr-card-succession.png',
                'assets/frontend/img/leadership/ldr-card-assessment.png',
                'assets/frontend/img/leadership/ldr-board-advisory.png',
                'assets/frontend/img/leadership/ldr-services-lifecycle.png',
                'assets/frontend/img/leadership/ldr-risk-org-growth.png',
            ],
            'bottom_cta' => 'assets/frontend/img/leadership/ldr-deliverable-talent.png',
        ],
        'leadership-assessment-consulting' => [
            'hero' => 'assets/frontend/img/leadership/ldr-card-assessment.png',
            'focus' => 'assets/frontend/img/leadership/ldr-services-lifecycle.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/leadership/ldr-card-assessment.png',
            'steps' => [
                'assets/frontend/img/leadership/ldr-deliverable-search.png',
                'assets/frontend/img/leadership/ldr-deliverable-search.png',
                'assets/frontend/img/leadership/ldr-risk-org-growth.png',
                'assets/frontend/img/leadership/ldr-deliverable-talent.png',
                'assets/frontend/img/leadership/ldr-hero-boardroom.png',
            ],
            'bottom_cta' => 'assets/frontend/img/leadership/ldr-board-advisory.png',
        ],
        'hr-talent-strategy-advisory' => [
            'hero' => 'assets/frontend/img/leadership/ldr-card-talent-strategy.png',
            'focus' => 'assets/frontend/img/leadership/ldr-deliverable-talent.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/leadership/ldr-card-talent-strategy.png',
            'steps' => [
                'assets/frontend/img/leadership/ldr-deliverable-talent.png',
                'assets/frontend/img/leadership/ldr-risk-org-growth.png',
                'assets/frontend/img/leadership/ldr-services-lifecycle.png',
                'assets/frontend/img/leadership/ldr-card-executive-search.png',
                'assets/frontend/img/leadership/ldr-deliverable-search.png',
            ],
            'bottom_cta' => 'assets/frontend/img/leadership/ldr-hero-boardroom.png',
        ],
    ],
    'talent-acquisition' => [
        'it-staffing' => [
            'hero' => 'assets/frontend/img/talent-acquisition/ta-hero-hiring.png',
            'focus' => 'assets/frontend/img/talent-acquisition/ta-card-it-staffing.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/talent-acquisition/ta-card-it-staffing.png',
            'steps' => [
                'assets/frontend/img/talent-acquisition/ta-deliverable-shortlists.png',
                'assets/frontend/img/talent-acquisition/ta-card-it-recruitment.png',
                'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
                'assets/frontend/img/talent-acquisition/ta-candidate-quality.png',
                'assets/frontend/img/talent-acquisition/ta-card-rpo.png',
            ],
            'bottom_cta' => 'assets/frontend/img/talent-acquisition/ta-deliverable-executive.png',
        ],
        'general-staffing' => [
            'hero' => 'assets/frontend/img/talent-acquisition/ta-card-general-staffing.png',
            'focus' => 'assets/frontend/img/talent-acquisition/ta-candidate-quality.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/talent-acquisition/ta-card-general-staffing.png',
            'steps' => [
                'assets/frontend/img/talent-acquisition/ta-hero-hiring.png',
                'assets/frontend/img/talent-acquisition/ta-deliverable-shortlists.png',
                'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
                'assets/frontend/img/talent-acquisition/ta-card-naps.png',
                'assets/frontend/img/talent-acquisition/ta-cta-hiring.png',
            ],
            'bottom_cta' => 'assets/frontend/img/talent-acquisition/ta-card-rpo.png',
        ],
        'naps-apprenticeship-support' => [
            'hero' => 'assets/frontend/img/talent-acquisition/ta-card-naps.png',
            'focus' => 'assets/frontend/img/talent-acquisition/ta-candidate-quality.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/talent-acquisition/ta-card-naps.png',
            'steps' => [
                'assets/frontend/img/talent-acquisition/ta-hero-hiring.png',
                'assets/frontend/img/talent-acquisition/ta-candidate-quality.png',
                'assets/frontend/img/talent-acquisition/ta-deliverable-shortlists.png',
                'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
                'assets/frontend/img/talent-acquisition/ta-card-general-staffing.png',
            ],
            'bottom_cta' => 'assets/frontend/img/talent-acquisition/ta-cta-hiring.png',
        ],
        'it-recruitment' => [
            'hero' => 'assets/frontend/img/talent-acquisition/ta-card-it-recruitment.png',
            'focus' => 'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/talent-acquisition/ta-card-it-recruitment.png',
            'steps' => [
                'assets/frontend/img/talent-acquisition/ta-deliverable-shortlists.png',
                'assets/frontend/img/talent-acquisition/ta-card-it-staffing.png',
                'assets/frontend/img/talent-acquisition/ta-candidate-quality.png',
                'assets/frontend/img/talent-acquisition/ta-hero-hiring.png',
                'assets/frontend/img/talent-acquisition/ta-card-rpo.png',
            ],
            'bottom_cta' => 'assets/frontend/img/talent-acquisition/ta-deliverable-rpo.png',
        ],
        'recruitment-process-outsourcing' => [
            'hero' => 'assets/frontend/img/talent-acquisition/ta-card-rpo.png',
            'focus' => 'assets/frontend/img/talent-acquisition/ta-deliverable-rpo.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/talent-acquisition/ta-card-rpo.png',
            'steps' => [
                'assets/frontend/img/talent-acquisition/ta-hero-hiring.png',
                'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
                'assets/frontend/img/talent-acquisition/ta-deliverable-shortlists.png',
                'assets/frontend/img/talent-acquisition/ta-candidate-quality.png',
                'assets/frontend/img/talent-acquisition/ta-cta-hiring.png',
            ],
            'bottom_cta' => 'assets/frontend/img/talent-acquisition/ta-hero-hiring.png',
        ],
        'executive-search' => [
            'hero' => 'assets/frontend/img/talent-acquisition/ta-card-executive-search.png',
            'focus' => 'assets/frontend/img/talent-acquisition/ta-deliverable-executive.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/talent-acquisition/ta-card-executive-search.png',
            'steps' => [
                'assets/frontend/img/talent-acquisition/ta-hero-hiring.png',
                'assets/frontend/img/talent-acquisition/ta-card-executive-search.png',
                'assets/frontend/img/talent-acquisition/ta-candidate-quality.png',
                'assets/frontend/img/talent-acquisition/ta-deliverable-shortlists.png',
                'assets/frontend/img/talent-acquisition/ta-services-recruitment.png',
            ],
            'bottom_cta' => 'assets/frontend/img/talent-acquisition/ta-cta-hiring.png',
        ],
    ],
    'hraas' => [
        'hr-outsourcing' => [
            'hero' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
            'focus' => 'assets/frontend/img/hraas/hraas-v3-deliverable-ops.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/hraas/hraas-v3-card-outsourcing.png',
            'steps' => [
                'assets/frontend/img/hraas/hraas-v3-partner.png',
                'assets/frontend/img/hraas/hraas-expert-digital.webp',
                'assets/frontend/img/hraas/hraas-hr-dashboard.webp',
                'assets/frontend/img/hraas/hraas-v3-deliverable-tech.png',
                'assets/frontend/img/hraas/hraas-growth-engine.webp',
            ],
            'bottom_cta' => 'assets/frontend/img/hraas/hraas-v3-cta-person.png',
        ],
        'employer-branding' => [
            'hero' => 'assets/frontend/img/hraas/hraas-v3-card-branding.png',
            'focus' => 'assets/frontend/img/hraas/hraas-v3-deliverable-brand.png',
            'focus_position' => 'center top',
            'card' => 'assets/frontend/img/hraas/hraas-v3-card-branding.png',
            'steps' => [
                'assets/frontend/img/hraas/hraas-employer-brand.webp',
                'assets/frontend/img/hraas/hraas-v3-services.png',
                'assets/frontend/img/hraas/hraas-v3-partner.png',
                'assets/frontend/img/hraas/hraas-leadership-spotlight.webp',
                'assets/frontend/img/hraas/hraas-v3-risk.png',
            ],
            'bottom_cta' => 'assets/frontend/img/hraas/hraas-v3-cta-person.png',
        ],
        'candidate-sourcing' => [
            'hero' => 'assets/frontend/img/hraas/hraas-v3-card-sourcing.png',
            'focus' => 'assets/frontend/img/hraas/hraas-expert-digital.webp',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/hraas/hraas-v3-card-sourcing.png',
            'steps' => [
                'assets/frontend/img/hraas/hraas-v3-hero.png',
                'assets/frontend/img/hraas/hraas-v3-services.png',
                'assets/frontend/img/hraas/hraas-problem-dashboard.webp',
                'assets/frontend/img/hraas/hraas-v3-deliverable-ops.png',
                'assets/frontend/img/hraas/hraas-process-timeline.webp',
            ],
            'bottom_cta' => 'assets/frontend/img/hraas/hraas-v3-partner.png',
        ],
        'employee-engagement-performance' => [
            'hero' => 'assets/frontend/img/hraas/hraas-v3-hero.png',
            'focus' => 'assets/frontend/img/hraas/hraas-employer-brand.webp',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/hraas/hraas-v3-card-engagement.png',
            'steps' => [
                'assets/frontend/img/hraas/hraas-v3-services.png',
                'assets/frontend/img/hraas/hraas-v3-deliverable-brand.png',
                'assets/frontend/img/hraas/hraas-growth-engine.webp',
                'assets/frontend/img/hraas/hraas-hr-dashboard.webp',
                'assets/frontend/img/hraas/hraas-v3-partner.png',
            ],
            'bottom_cta' => 'assets/frontend/img/hraas/hraas-v3-cta-person.png',
        ],
        'employee-surveys-retention' => [
            'hero' => 'assets/frontend/img/hraas/hraas-v3-card-surveys.png',
            'focus' => 'assets/frontend/img/hraas/hraas-v3-risk.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/hraas/hraas-v3-card-surveys.png',
            'steps' => [
                'assets/frontend/img/hraas/hraas-problem-dashboard.webp',
                'assets/frontend/img/hraas/hraas-hr-dashboard.webp',
                'assets/frontend/img/hraas/hraas-v3-deliverable-ops.png',
                'assets/frontend/img/hraas/hraas-leadership-spotlight.webp',
                'assets/frontend/img/hraas/hraas-v3-partner.png',
            ],
            'bottom_cta' => 'assets/frontend/img/hraas/hraas-v3-cta-person.png',
        ],
        'hr-technology-solutions' => [
            'hero' => 'assets/frontend/img/hraas/hraas-v3-card-tech.png',
            'focus' => 'assets/frontend/img/hraas/hraas-v3-deliverable-tech.png',
            'focus_position' => 'center center',
            'card' => 'assets/frontend/img/hraas/hraas-v3-card-tech.png',
            'steps' => [
                'assets/frontend/img/hraas/hraas-expert-digital.webp',
                'assets/frontend/img/hraas/hraas-v3-services.png',
                'assets/frontend/img/hraas/hraas-v3-deliverable-ops.png',
                'assets/frontend/img/hraas/hraas-process-timeline.webp',
                'assets/frontend/img/hraas/hraas-growth-engine.webp',
            ],
            'bottom_cta' => 'assets/frontend/img/hraas/hraas-v3-cta-person.png',
        ],
    ],
];
